REPORT ZZPATCH_COA_BKTXT.

DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: N1 TYPE I, N2 TYPE I, N3 TYPE I, N4 TYPE I,
      N5 TYPE I, N6 TYPE I, N7 TYPE I.
DATA: F_ORD TYPE C, F_CMP TYPE C.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMI_COA_F01'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED', SY-SUBRC.
  RETURN.
ENDIF.

LOOP AT LT_SRC.
  L = LT_SRC-LINE.

  IF L = 'FORM GET_VALID_ORDER_FROM_MSEG USING P_CHARG CHANGING P_AUFNR.'.
  PERFORM A USING '* BKTXT dokumen GR (101) yang sedang di-trace. Di-set oleh GET_VALID_ORDER_FROM_MSEG,'.
  PERFORM A USING '* dibaca GET_VALID_COMPONENT_FROM_MSEG. BKTXT = identitas transaksi / nomor roll, dan'.
  PERFORM A USING '* merupakan penghubung yang benar antara posting 101 dan 261 dalam SATU production order.'.
  PERFORM A USING 'DATA: GV_TRACE_BKTXT TYPE MKPF-BKTXT.'.
  PERFORM A USING ''.
    N1 = N1 + 1.
    F_ORD = 'X'.
    PERFORM A USING L.
    CONTINUE.
  ENDIF.

  IF L = 'FORM GET_VALID_COMPONENT_FROM_MSEG USING P_AUFNR CHANGING P_CHARG.'.
    PERFORM A USING L.
  PERFORM A USING '  DATA: BEGIN OF LT_MKPF OCCURS 0,'.
  PERFORM A USING '          MBLNR LIKE MKPF-MBLNR,'.
  PERFORM A USING '          MJAHR LIKE MKPF-MJAHR,'.
  PERFORM A USING '          BKTXT LIKE MKPF-BKTXT,'.
  PERFORM A USING '        END OF LT_MKPF.'.
    N4 = N4 + 1.
    F_CMP = 'X'.
    CONTINUE.
  ENDIF.

  IF F_ORD = 'X' AND
     L = '        LT_CANC TYPE TABLE OF MSEG WITH HEADER LINE.'.
    PERFORM A USING L.
  PERFORM A USING '  DATA: LV_COMBINE LIKE AFPO-AUFNR.'.
    N3 = N3 + 1.
    CONTINUE.
  ENDIF.

  IF F_ORD = 'X' AND L = '      P_AUFNR = LT_MSEG-AUFNR.'.
    PERFORM A USING L.
  PERFORM A USING ''.
  PERFORM A USING '      " Fix A (user 18/07/2026): ambil BKTXT dokumen GR (101) ini, dipakai'.
  PERFORM A USING '      " GET_VALID_COMPONENT_FROM_MSEG untuk memilih komponen 261 pasangan roll ini.'.
  PERFORM A USING '      " Bukti: order 100000072887 punya 8 posting 261 / 4 batch berbeda, dibedakan'.
  PERFORM A USING '      " HANYA oleh BKTXT. Logic lama ambil MBLNR terbesar - salah roll tanpa gejala.'.
  PERFORM A USING '      SELECT SINGLE BKTXT INTO GV_TRACE_BKTXT'.
  PERFORM A USING '        FROM MKPF'.
  PERFORM A USING '        WHERE MBLNR = LT_MSEG-MBLNR'.
  PERFORM A USING '          AND MJAHR = LT_MSEG-MJAHR.'.
  PERFORM A USING ''.
  PERFORM A USING '      " Fix B (user 18/07/2026): resolve COLLECTIVE ORDER. AUFNR dari MSEG 101 bisa'.
  PERFORM A USING '      " order referensi (mis. A29000002540) yang TIDAK punya komponen 261 sama sekali;'.
  PERFORM A USING '      " order asli dicari via AFPO-MILL_OC_AUFNR_U. Tanpa ini tracing MATI di hop'.
  PERFORM A USING '      " pertama sehingga MIC level Base Film (mis. PALZTH00) selalu kosong.'.
  PERFORM A USING '      CLEAR LV_COMBINE.'.
  PERFORM A USING '      SELECT SINGLE AUFNR INTO LV_COMBINE'.
  PERFORM A USING '        FROM AFPO'.
  PERFORM A USING '        WHERE MILL_OC_AUFNR_U = P_AUFNR.'.
  PERFORM A USING '      IF SY-SUBRC = 0 AND LV_COMBINE IS NOT INITIAL.'.
  PERFORM A USING '        P_AUFNR = LV_COMBINE.'.
  PERFORM A USING '      ENDIF.'.
    N2 = N2 + 1.
    CLEAR F_ORD.
    CONTINUE.
  ENDIF.

  IF F_CMP = 'X' AND L = '    WHERE AUFNR = P_AUFNR AND BWART IN (''261'', ''262'') AND CHARG <> ''''.'.
    PERFORM A USING '    WHERE AUFNR = P_AUFNR AND BWART IN (''261'', ''262'', ''901'', ''902'') AND CHARG <> ''''.'.
    N5 = N5 + 1.
    CONTINUE.
  ENDIF.

  IF F_CMP = 'X' AND L = '    DELETE LT_MSEG WHERE SMBLN IS NOT INITIAL OR BWART = ''262''.'.
    PERFORM A USING '    DELETE LT_MSEG WHERE SMBLN IS NOT INITIAL OR BWART = ''262'' OR BWART = ''902''.'.
    N6 = N6 + 1.
  PERFORM A USING ''.
  PERFORM A USING '    " Fix BKTXT (user 18/07/2026): buang komponen yang BUKAN milik transaksi/roll yang'.
  PERFORM A USING '    " sama dengan dokumen 101-nya. Satu order bisa punya banyak roll, dan BKTXT adalah'.
  PERFORM A USING '    " satu-satunya pembeda. Kalau BKTXT 101 kosong (data lama), filter dilewati.'.
  PERFORM A USING '    IF GV_TRACE_BKTXT IS NOT INITIAL AND LT_MSEG[] IS NOT INITIAL.'.
  PERFORM A USING '      CLEAR LT_MKPF. REFRESH LT_MKPF.'.
  PERFORM A USING '      SELECT MBLNR MJAHR BKTXT INTO TABLE LT_MKPF'.
  PERFORM A USING '        FROM MKPF'.
  PERFORM A USING '        FOR ALL ENTRIES IN LT_MSEG'.
  PERFORM A USING '        WHERE MBLNR = LT_MSEG-MBLNR'.
  PERFORM A USING '          AND MJAHR = LT_MSEG-MJAHR.'.
  PERFORM A USING '      SORT LT_MKPF BY MBLNR MJAHR.'.
  PERFORM A USING '      LOOP AT LT_MSEG.'.
  PERFORM A USING '        CLEAR LT_MKPF.'.
  PERFORM A USING '        READ TABLE LT_MKPF WITH KEY MBLNR = LT_MSEG-MBLNR'.
  PERFORM A USING '                                    MJAHR = LT_MSEG-MJAHR BINARY SEARCH.'.
  PERFORM A USING '        IF SY-SUBRC <> 0 OR LT_MKPF-BKTXT <> GV_TRACE_BKTXT.'.
  PERFORM A USING '          DELETE LT_MSEG.'.
  PERFORM A USING '        ENDIF.'.
  PERFORM A USING '      ENDLOOP.'.
  PERFORM A USING '    ENDIF.'.
    N7 = N7 + 1.
    CLEAR F_CMP.
    CONTINUE.
  ENDIF.

  PERFORM A USING L.
ENDLOOP.

IF N1 <> 1 OR N2 <> 1 OR N3 <> 1 OR N4 <> 1
   OR N5 <> 1 OR N6 <> 1 OR N7 <> 1.
  WRITE: / 'ABORT - ANCHOR MISMATCH'.
  WRITE: / N1, N2, N3, N4, N5, N6, N7.
  RETURN.
ENDIF.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMI_COA_F01'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.

WRITE: / 'SUCCESS=', LV_OK.
WRITE: / 'MESSAGE=', LV_MSG.
DESCRIBE TABLE LT_OUT LINES N1.
WRITE: / 'LINES OUT=', N1.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.