*&---------------------------------------------------------------------*
*& Report  ZQMR_COA
*&---------------------------------------------------------------------*
REPORT ZQMR_COA.

* Cache format MIC dari master QPMK: decimal places (STELLEN) per MIC + plant.
* Dibaca sekali per kombinasi lalu dilayani dari memori. Dinamis penuh -
* MIC baru otomatis ikut tanpa perlu ubah kode. (Fix user 18/07/2026)
TYPES: BEGIN OF TY_MICFMT,
         MKMNR   TYPE QPMK-MKMNR,
         WERKS   TYPE QPMK-WERKS,
         STELLEN TYPE QPMK-STELLEN,
         UOM     TYPE QPMK-MASSEINHSW,
       END OF TY_MICFMT.
DATA: GT_MICFMT TYPE TABLE OF TY_MICFMT,
      GS_MICFMT TYPE TY_MICFMT.
DATA: GV_DEC TYPE I,
      GV_UOM TYPE QPMK-MASSEINHSW.

* Cache hasil rata-rata JR per mother roll (enhancement 18/07/2026).
TYPES: BEGIN OF TY_JRAVG,
         INSLOT TYPE QALS-PRUEFLOS,
         MIC    TYPE QAMV-VERWMERKM,
         ISJR   TYPE C,
         VAL    TYPE QAMR-MITTELWERT,
         CNT    TYPE I,
       END OF TY_JRAVG.
DATA: GT_JRAVG TYPE TABLE OF TY_JRAVG,
      GS_JRAVG TYPE TY_JRAVG.
TYPES: BEGIN OF TY_BARAVG,
         VBELN TYPE LIPS-VBELN,
         MIC   TYPE QAMV-VERWMERKM,
         VAL   TYPE QAMR-MITTELWERT,
         CNT   TYPE I,
       END OF TY_BARAVG.
DATA: GT_BARAVG TYPE TABLE OF TY_BARAVG,
      GS_BARAVG TYPE TY_BARAVG.

TABLES: LIPS, LIKP, QALS, QAMR, QPMK, ZMAP_COA, AUSP, INOB, QASE, ZBATCHISTORY, ZLOG_COA.

*----------------------------------------------------------------------*
* ALV and Data Structures
*----------------------------------------------------------------------*
TYPE-POOLS: SLIS.

TYPES: BEGIN OF TY_ALV,
         VBELN TYPE LIPS-VBELN,
         POSNR TYPE LIPS-POSNR,
         CHARG TYPE LIPS-CHARG,
         NOMSR TYPE C LENGTH 30,
         NOMJR TYPE C LENGTH 30,
         MATNR TYPE LIPS-MATNR,
         ZZTYPE TYPE C LENGTH 30,
         MIC TYPE QAMV-VERWMERKM,
         MICDES TYPE QPMT-KURZTEXT,
         UOM TYPE C LENGTH 30,
         METHOD TYPE C LENGTH 43,
         MICMIN TYPE P DECIMALS 2,
         MICMAX TYPE P DECIMALS 2,
         INS TYPE QALS-PRUEFLOS,
         CMICMIT TYPE C LENGTH 20,
         MICMIT TYPE QAMR-MITTELWERT,
         WERKS TYPE LIPS-WERKS,
       END OF TY_ALV.

DATA: IT_ALV TYPE STANDARD TABLE OF TY_ALV WITH HEADER LINE.

DATA: BEGIN OF IT_DATA OCCURS 0,
        VBELN LIKE LIPS-VBELN,
        POSNR LIKE LIPS-POSNR,
        CHARG LIKE LIPS-CHARG,
        MATNR LIKE LIPS-MATNR,
        WERKS LIKE LIPS-WERKS,
        UECHA LIKE LIPS-UECHA,
        NOMSR TYPE C LENGTH 30,
        NOMJR TYPE C LENGTH 30,
        ZZTYPE TYPE C LENGTH 30,
        KUNAG LIKE LIKP-KUNAG,
      END OF IT_DATA.

DATA: BEGIN OF IT_ZMAP OCCURS 0,
        MATNR LIKE ZMAP_COA-MATNR,
        MIC LIKE ZMAP_COA-MIC,
        KUNNR LIKE ZMAP_COA-KUNNR,
        METHOD LIKE ZMAP_COA-METHOD,
        MAPPING LIKE ZMAP_COA-MAPPING,
        NUM(5) ,
      END OF IT_ZMAP.

DATA: BEGIN OF IT_ZMAP_ALL OCCURS 0,
        MATNR LIKE ZMAP_COA-MATNR,
        MIC LIKE ZMAP_COA-MIC,
        KUNNR LIKE ZMAP_COA-KUNNR,
        METHOD LIKE ZMAP_COA-METHOD,
        MAPPING LIKE ZMAP_COA-MAPPING,
      END OF IT_ZMAP_ALL.

DATA: BEGIN OF IT_ZMAP_REQ OCCURS 0,
        MATNR LIKE ZMAP_COA-MATNR,
        KUNNR LIKE ZMAP_COA-KUNNR,
      END OF IT_ZMAP_REQ.

DATA: BEGIN OF IT_MIC OCCURS 0,
        MIC LIKE QPMK-MKMNR,
        MICDES LIKE QPMT-KURZTEXT,
        UOM LIKE QPMK-STEUERKZ,
        METHOD(40),
        MICMIN LIKE QPMK-TOLERANZUN,
        MICMAX LIKE QPMK-TOLERANZOB,
        CMICMIT(20),
        MICMIT LIKE QAMR-MITTELWERT,
        MERKNR LIKE QAMV-MERKNR,
        INS LIKE QALS-PRUEFLOS,
      END OF IT_MIC.

DATA: BEGIN OF L_S_OBJEK,
        OBJEK LIKE AUSP-OBJEK,
        IOBJEK LIKE INOB-OBJEK,
        OBJ(25),
        CHARG LIKE LIPS-CHARG,
      END OF L_S_OBJEK.

DATA: IT_OBJEK LIKE STANDARD TABLE OF L_S_OBJEK WITH HEADER LINE.
DATA: WA_OBJEK LIKE L_S_OBJEK.
DATA: TBATCH LIKE TABLE OF CLBATCH WITH HEADER LINE.
DATA: TBATCH_JR LIKE TABLE OF CLBATCH WITH HEADER LINE.

DATA: LOT_SR_CONV LIKE QALS-PRUEFLOS,
      LOT_JR_CONV LIKE QALS-PRUEFLOS,
      LOT_SR_BASE LIKE QALS-PRUEFLOS,
      LOT_JR_BASE LIKE QALS-PRUEFLOS.

DATA: L_JR_CONV_BATCH LIKE MCH1-CHARG,
      L_SR_BASE_BATCH LIKE MCH1-CHARG,
      L_JR_BASE_BATCH LIKE MCH1-CHARG.

DATA: LT_SR TYPE TABLE OF ZQM_GET_BATCH_SR WITH HEADER LINE.
DATA: T_SR TYPE TABLE OF ZQM_GET_BATCH_SR WITH HEADER LINE.

DATA: WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
      IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT   TYPE SLIS_LAYOUT_ALV.

DATA: ATINN_ROLL TYPE AUSP-ATINN,
      ATINN_CODE TYPE AUSP-ATINN.

*----------------------------------------------------------------------*
* Selection Screen
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
SELECT-OPTIONS: S_ERDAT FOR LIKP-ERDAT.
PARAMETERS: P_WERKS TYPE LIPS-WERKS MATCHCODE OBJECT H_T001W.
SELECT-OPTIONS: S_VBELN FOR LIPS-VBELN.
SELECT-OPTIONS: S_ROLL FOR AUSP-ATWRT.
SELECT-OPTIONS: S_TYPE FOR AUSP-ATWRT.
SELECT-OPTIONS: S_CHARG FOR LIPS-CHARG.
SELECTION-SCREEN END OF BLOCK B1.

AT SELECTION-SCREEN.
  IF S_VBELN[] IS INITIAL AND S_ERDAT[] IS INITIAL.
    MESSAGE 'Untuk menjaga performa, harap isi Nomor ODO (VBELN) ATAU Tanggal (ERDAT)!' TYPE 'E'.
  ENDIF.

  IF S_VBELN[] IS INITIAL AND S_ERDAT[] IS NOT INITIAL.
    DATA: LV_DAYS TYPE I.
    IF S_ERDAT-HIGH IS NOT INITIAL.
      LV_DAYS = S_ERDAT-HIGH - S_ERDAT-LOW.
      IF LV_DAYS > 31.
        MESSAGE 'Rentang tanggal maksimal 1 bulan jika Nomor ODO dikosongkan!' TYPE 'E'.
      ENDIF.
    ENDIF.
  ENDIF.

*----------------------------------------------------------------------*
* Start of Selection
*----------------------------------------------------------------------*

INITIALIZATION.
  CALL FUNCTION 'CONVERSION_EXIT_ATINN_INPUT' EXPORTING INPUT = 'ZZNOMORROLL' IMPORTING OUTPUT = ATINN_ROLL.
  CALL FUNCTION 'CONVERSION_EXIT_ATINN_INPUT' EXPORTING INPUT = 'ZZCODE' IMPORTING OUTPUT = ATINN_CODE.

START-OF-SELECTION.
  PERFORM GET_DATA.
  IF IT_ALV[] IS INITIAL.
    MESSAGE 'Data tidak ditemukan untuk kriteria seleksi ini.' TYPE 'S' DISPLAY LIKE 'E'.
  ELSE.
    PERFORM DISPLAY_ALV.
  ENDIF.

FORM GET_DATA.
  DATA: TEXT1 TYPE C LENGTH 25,
        TEXT2 TYPE C LENGTH 30,
        LV_KUNNR LIKE ZMAP_COA-KUNNR.

  DATA: R_PSTYV TYPE RANGE OF LIPS-PSTYV,
        WA_PSTYV LIKE LINE OF R_PSTYV,
        IT_ZMAP_DELIV TYPE STANDARD TABLE OF ZMAP_TYPE WITH HEADER LINE.

  DATA: L_PREV_VBELN LIKE LIPS-VBELN,
        L_PREV_MATNR LIKE LIPS-MATNR,
        L_TARGET_JR LIKE MCH1-CHARG,
        L_MATNR_JR LIKE MCH1-MATNR,
        L_SAVED_NOMJR TYPE C LENGTH 30.
  DATA: LT_SAVED_MIC LIKE TABLE OF IT_MIC WITH HEADER LINE.


  DATA: BEGIN OF IT_BATCH_COLLECT OCCURS 0,
          MATNR LIKE MCH1-MATNR,
          CHARG LIKE MCH1-CHARG,
        END OF IT_BATCH_COLLECT.

  DATA: BEGIN OF IT_TEMP_OBJEK OCCURS 0,
          OBJEK LIKE INOB-OBJEK,
        END OF IT_TEMP_OBJEK.

  DATA: BEGIN OF IT_INOB_RAW OCCURS 0,
          CUOBJ LIKE INOB-CUOBJ,
          OBJEK LIKE INOB-OBJEK,
        END OF IT_INOB_RAW.

  DATA: BEGIN OF IT_INOB OCCURS 0,
          CUOBJ LIKE INOB-CUOBJ,
          OBJEK LIKE AUSP-OBJEK,
          MATNR LIKE MCH1-MATNR,
          CHARG LIKE MCH1-CHARG,
        END OF IT_INOB.

  DATA: BEGIN OF IT_AUSP OCCURS 0,
          OBJEK LIKE AUSP-OBJEK,
          ATINN LIKE AUSP-ATINN,
          ATWRT LIKE AUSP-ATWRT,
        END OF IT_AUSP.

  DATA: LV_OBJEK LIKE INOB-OBJEK.

  CLEAR: R_PSTYV, IT_ZMAP_DELIV.
  REFRESH: R_PSTYV, IT_ZMAP_DELIV.

  SELECT * INTO TABLE IT_ZMAP_DELIV FROM ZMAP_TYPE
    WHERE PROG = SY-CPROG AND TYPE = 'ITEM CATEGORY'.
  LOOP AT IT_ZMAP_DELIV.
    WA_PSTYV-SIGN = 'I'.
    WA_PSTYV-OPTION = 'EQ'.
    WA_PSTYV-LOW = IT_ZMAP_DELIV-VALUE.
    APPEND WA_PSTYV TO R_PSTYV.
  ENDLOOP.
  IF R_PSTYV[] IS INITIAL.
    WA_PSTYV-SIGN = 'I'. WA_PSTYV-OPTION = 'EQ'. WA_PSTYV-LOW = 'ZB'. APPEND WA_PSTYV TO R_PSTYV.
  ENDIF.

  IF S_ROLL[] IS NOT INITIAL.
    SELECT OBJEK INTO WA_OBJEK-OBJEK
      FROM AUSP
      WHERE AUSP~ATINN = ATINN_ROLL
      AND AUSP~ATWRT IN S_ROLL.
      APPEND WA_OBJEK TO IT_OBJEK.
    ENDSELECT.

    IF IT_OBJEK[] IS NOT INITIAL.
      LOOP AT IT_OBJEK INTO WA_OBJEK.
        SELECT SINGLE INOB~OBJEK INTO WA_OBJEK-IOBJEK
        FROM INOB WHERE CUOBJ = WA_OBJEK-OBJEK.
        SPLIT WA_OBJEK-IOBJEK AT SPACE INTO TEXT1 TEXT2.
        CONDENSE: TEXT1, TEXT2.
        WA_OBJEK-OBJ = TEXT1.
        WA_OBJEK-CHARG = TEXT2.
        MODIFY IT_OBJEK FROM WA_OBJEK.
      ENDLOOP.

        SORT IT_OBJEK BY CHARG.
        DELETE ADJACENT DUPLICATES FROM IT_OBJEK COMPARING CHARG.
      SELECT A~VBELN A~POSNR A~CHARG A~MATNR A~WERKS A~UECHA B~KUNAG
        INTO CORRESPONDING FIELDS OF TABLE IT_DATA
        FROM LIPS AS A
        INNER JOIN LIKP AS B ON A~VBELN = B~VBELN
        FOR ALL ENTRIES IN IT_OBJEK
        WHERE A~VBELN IN S_VBELN
          AND A~CHARG = IT_OBJEK-CHARG
          AND A~PSTYV IN R_PSTYV
          AND B~ERDAT IN S_ERDAT.
    ENDIF.
  ELSE.
    SELECT A~VBELN A~POSNR A~CHARG A~MATNR A~WERKS A~UECHA B~KUNAG
      INTO CORRESPONDING FIELDS OF TABLE IT_DATA
      FROM LIPS AS A
      INNER JOIN LIKP AS B ON A~VBELN = B~VBELN
      WHERE A~VBELN IN S_VBELN
        AND A~CHARG IN S_CHARG
        AND A~PSTYV IN R_PSTYV
        AND B~ERDAT IN S_ERDAT.
  ENDIF.

  IF P_WERKS IS NOT INITIAL.
    DELETE IT_DATA WHERE WERKS NE P_WERKS.
  ENDIF.

  DELETE IT_DATA WHERE CHARG IS INITIAL.
  SORT IT_DATA BY VBELN MATNR CHARG.
  DELETE ADJACENT DUPLICATES FROM IT_DATA COMPARING VBELN MATNR CHARG.

  " ----------------------------------------------------------------------
  " PHASE 1: COLLECT BATCHES AND TRACE JUMBO ROLLS
  " ----------------------------------------------------------------------
  CLEAR IT_BATCH_COLLECT. REFRESH IT_BATCH_COLLECT.



  " Fix (permintaan user 17/07/2026): dulu trace jumbo roll hanya sekali per VBELN+MATNR
  " (batch pertama sebagai sampel, hasil di-inherit ke semua baris lain). Sekarang trace
  " SETIAP batch (bukan hanya batch pertama per grup) supaya tiap DO item bisa dapat lot
  " sendiri-sendiri - dibutuhkan supaya averaging MIC per-DO (lihat AGGREGATE_MIC_VALUES)
  " menghitung nilai dari batch yang benar-benar berbeda, bukan mewarisi 1 sampel saja.
  LOOP AT IT_DATA.
    IT_BATCH_COLLECT-MATNR = IT_DATA-MATNR.
    IT_BATCH_COLLECT-CHARG = IT_DATA-CHARG.
    APPEND IT_BATCH_COLLECT.

    PERFORM GET_TRACED_LOTS.

    L_TARGET_JR = L_JR_BASE_BATCH.
    IF L_TARGET_JR IS INITIAL.
      L_TARGET_JR = L_JR_CONV_BATCH.
    ENDIF.

    IF L_TARGET_JR IS NOT INITIAL.
      SELECT SINGLE MATNR INTO L_MATNR_JR FROM MCH1 WHERE CHARG = L_TARGET_JR.
      IF SY-SUBRC EQ 0.
        IT_BATCH_COLLECT-MATNR = L_MATNR_JR.
        IT_BATCH_COLLECT-CHARG = L_TARGET_JR.
        APPEND IT_BATCH_COLLECT.
      ENDIF.
    ENDIF.
  ENDLOOP.

  " ----------------------------------------------------------------------
  " PHASE 2: BULK DB READ (NO SELECT IN LOOP)
  " ----------------------------------------------------------------------
  SORT IT_BATCH_COLLECT BY MATNR CHARG.
  DELETE ADJACENT DUPLICATES FROM IT_BATCH_COLLECT COMPARING MATNR CHARG.

  CLEAR IT_INOB. REFRESH IT_INOB.
  CLEAR IT_AUSP. REFRESH IT_AUSP.
  CLEAR IT_TEMP_OBJEK. REFRESH IT_TEMP_OBJEK.

  IF IT_BATCH_COLLECT[] IS NOT INITIAL.
    LOOP AT IT_BATCH_COLLECT.
      IT_TEMP_OBJEK-OBJEK = IT_BATCH_COLLECT-MATNR.
      IT_TEMP_OBJEK-OBJEK+18(10) = IT_BATCH_COLLECT-CHARG.
      APPEND IT_TEMP_OBJEK.
    ENDLOOP.

      SORT IT_TEMP_OBJEK BY OBJEK.
      DELETE ADJACENT DUPLICATES FROM IT_TEMP_OBJEK COMPARING OBJEK.
    SELECT CUOBJ OBJEK INTO TABLE IT_INOB_RAW
      FROM INOB
      FOR ALL ENTRIES IN IT_TEMP_OBJEK
      WHERE OBJEK = IT_TEMP_OBJEK-OBJEK
        AND OBTAB = 'MCH1'.

    LOOP AT IT_INOB_RAW.
      IT_INOB-CUOBJ = IT_INOB_RAW-CUOBJ.
      IT_INOB-OBJEK = IT_INOB_RAW-CUOBJ.
      IT_INOB-MATNR = IT_INOB_RAW-OBJEK(18).
      IT_INOB-CHARG = IT_INOB_RAW-OBJEK+18(10).
      APPEND IT_INOB.
    ENDLOOP.
    SORT IT_INOB BY MATNR CHARG.
  ENDIF.

  IF IT_INOB[] IS NOT INITIAL.
      SORT IT_INOB BY OBJEK.
      DELETE ADJACENT DUPLICATES FROM IT_INOB COMPARING OBJEK.
    SELECT OBJEK ATINN ATWRT INTO TABLE IT_AUSP
      FROM AUSP
      FOR ALL ENTRIES IN IT_INOB
      WHERE OBJEK = IT_INOB-OBJEK
        AND ( ATINN = ATINN_ROLL OR ATINN = ATINN_CODE )
        AND KLART = '023'.
    SORT IT_AUSP BY OBJEK ATINN.
  ENDIF.

  " ----------------------------------------------------------------------
  " PHASE 2.5: PRE-FETCH ZMAP_COA (REDUCE SELECT IN LOOP)
  " ----------------------------------------------------------------------
  CLEAR IT_ZMAP_REQ. REFRESH IT_ZMAP_REQ.
  LOOP AT IT_DATA.
    IT_ZMAP_REQ-MATNR = IT_DATA-MATNR.
    IT_ZMAP_REQ-KUNNR = IT_DATA-KUNAG.
    APPEND IT_ZMAP_REQ.

    IT_ZMAP_REQ-MATNR = IT_DATA-MATNR.
    IT_ZMAP_REQ-KUNNR = ' '.
    APPEND IT_ZMAP_REQ.
  ENDLOOP.
  SORT IT_ZMAP_REQ BY MATNR KUNNR.
  DELETE ADJACENT DUPLICATES FROM IT_ZMAP_REQ COMPARING MATNR KUNNR.

  CLEAR IT_ZMAP_ALL. REFRESH IT_ZMAP_ALL.
  IF IT_ZMAP_REQ[] IS NOT INITIAL.
      SORT IT_ZMAP_REQ BY MATNR KUNNR.
      DELETE ADJACENT DUPLICATES FROM IT_ZMAP_REQ COMPARING MATNR KUNNR.
    SELECT MATNR MIC KUNNR METHOD MAPPING
      INTO CORRESPONDING FIELDS OF TABLE IT_ZMAP_ALL
      FROM ZMAP_COA
      FOR ALL ENTRIES IN IT_ZMAP_REQ
      WHERE MATNR = IT_ZMAP_REQ-MATNR
        AND KUNNR = IT_ZMAP_REQ-KUNNR
        AND DELETION NE 'X'.
    SORT IT_ZMAP_ALL BY MATNR KUNNR MIC.
  ENDIF.

  " ----------------------------------------------------------------------
  " PHASE 3: ALV POPULATION (ONLY READ TABLE)
  SORT IT_INOB BY MATNR CHARG.
  SORT IT_AUSP BY OBJEK ATINN.
  " ----------------------------------------------------------------------
  CLEAR: L_PREV_VBELN, L_PREV_MATNR, L_SAVED_NOMJR, LT_SAVED_MIC.
  REFRESH LT_SAVED_MIC.

  LOOP AT IT_DATA.
    CLEAR: IT_DATA-NOMSR, IT_DATA-ZZTYPE.

    CLEAR IT_INOB.
    READ TABLE IT_INOB WITH KEY MATNR = IT_DATA-MATNR CHARG = IT_DATA-CHARG BINARY SEARCH.
    IF SY-SUBRC EQ 0.
      CLEAR IT_AUSP.
      READ TABLE IT_AUSP WITH KEY OBJEK = IT_INOB-OBJEK ATINN = ATINN_ROLL BINARY SEARCH.
      IF SY-SUBRC EQ 0.
        IT_DATA-NOMSR = IT_AUSP-ATWRT.
      ENDIF.
      CLEAR IT_AUSP.
      READ TABLE IT_AUSP WITH KEY OBJEK = IT_INOB-OBJEK ATINN = ATINN_CODE BINARY SEARCH.
      IF SY-SUBRC EQ 0.
        IT_DATA-ZZTYPE = IT_AUSP-ATWRT.
      ENDIF.
    ENDIF.

    IF S_TYPE[] IS NOT INITIAL.
      IF IT_DATA-ZZTYPE NOT IN S_TYPE.
        CONTINUE.
      ENDIF.
    ENDIF.

    " Fix (permintaan user 17/07/2026): dulu logic ini "Batch Pertama sebagai Sampel" -
    " hanya batch PERTAMA dalam 1 VBELN+MATNR yang di-trace (GET_TRACED_LOTS+GET_MIC),
    " hasilnya di-copy/inherit ke SEMUA batch lain dalam grup yang sama (L_SAVED_NOMJR/
    " LT_SAVED_MIC). Sekarang trace & GET_MIC dijalankan PER BATCH (mirip ZQMI_COA_F01),
    " supaya tiap DO item punya hasil MIC sendiri sebagai dasar averaging yang benar
    " (lihat FORM AGGREGATE_MIC_VALUES). Baris tampil tetap PER DO ITEM (tidak di-collapse) -
    " yang berubah hanya value CMICMIT-nya, ditimpa dengan hasil rata-rata di tahap akhir.
    CLEAR IT_DATA-NOMJR.

    DATA: IT_ZMAP_GEN LIKE TABLE OF IT_ZMAP WITH HEADER LINE,
          IT_ZMAP_CUS LIKE TABLE OF IT_ZMAP WITH HEADER LINE.
    CLEAR: IT_ZMAP, LV_KUNNR, IT_ZMAP_GEN, IT_ZMAP_CUS.
    REFRESH: IT_ZMAP, IT_ZMAP_GEN, IT_ZMAP_CUS.

    LV_KUNNR = IT_DATA-KUNAG.

    LOOP AT IT_ZMAP_ALL INTO IT_ZMAP_GEN WHERE MATNR = IT_DATA-MATNR AND KUNNR = ' '.
      APPEND IT_ZMAP_GEN.
    ENDLOOP.

    IF LV_KUNNR IS NOT INITIAL.
      LOOP AT IT_ZMAP_ALL INTO IT_ZMAP_CUS WHERE MATNR = IT_DATA-MATNR AND KUNNR = LV_KUNNR.
        APPEND IT_ZMAP_CUS.
      ENDLOOP.
    ENDIF.

    IT_ZMAP[] = IT_ZMAP_GEN[].
    SORT IT_ZMAP BY MIC.
    LOOP AT IT_ZMAP_CUS.
      CLEAR IT_ZMAP.
      READ TABLE IT_ZMAP WITH KEY MIC = IT_ZMAP_CUS-MIC BINARY SEARCH.
      IF SY-SUBRC = 0.
        IT_ZMAP-METHOD = IT_ZMAP_CUS-METHOD.
        IT_ZMAP-KUNNR  = IT_ZMAP_CUS-KUNNR.
        IT_ZMAP-MAPPING = IT_ZMAP_CUS-MAPPING.
        MODIFY IT_ZMAP INDEX SY-TABIX.
      ELSE.
        APPEND IT_ZMAP_CUS TO IT_ZMAP.
      ENDIF.
    ENDLOOP.

    SORT IT_ZMAP BY MIC ASCENDING.
    DELETE ADJACENT DUPLICATES FROM IT_ZMAP COMPARING MIC.

    IF IT_ZMAP[] IS NOT INITIAL.
      PERFORM GET_TRACED_LOTS.

      " Get JR Roll Number (From Bulk AUSP)
      L_TARGET_JR = L_JR_BASE_BATCH.
      IF L_TARGET_JR IS INITIAL.
        L_TARGET_JR = L_JR_CONV_BATCH.
      ENDIF.

      IF L_TARGET_JR IS NOT INITIAL.
        SELECT SINGLE MATNR INTO L_MATNR_JR FROM MCH1 WHERE CHARG = L_TARGET_JR.
        IF SY-SUBRC EQ 0.
          CLEAR IT_INOB.
          READ TABLE IT_INOB WITH KEY MATNR = L_MATNR_JR CHARG = L_TARGET_JR BINARY SEARCH.
          IF SY-SUBRC EQ 0.
            CLEAR IT_AUSP.
            READ TABLE IT_AUSP WITH KEY OBJEK = IT_INOB-OBJEK ATINN = ATINN_ROLL BINARY SEARCH.
            IF SY-SUBRC EQ 0.
              IT_DATA-NOMJR = IT_AUSP-ATWRT.
            ENDIF.
          ENDIF.
        ENDIF.
      ENDIF.

      PERFORM GET_MIC.
    ENDIF.

    IF IT_DATA-UECHA IS INITIAL.
      IT_DATA-UECHA = IT_DATA-POSNR.
    ENDIF.
    MODIFY IT_DATA.

    " Append to ALV table
    LOOP AT IT_MIC.
      CLEAR IT_ALV.
      IT_ALV-VBELN = IT_DATA-VBELN.
      IT_ALV-POSNR = IT_DATA-POSNR.
      IT_ALV-CHARG = IT_DATA-CHARG.
      IT_ALV-NOMSR = IT_DATA-NOMSR.
      IT_ALV-NOMJR = IT_DATA-NOMJR.
      IT_ALV-MATNR = IT_DATA-MATNR.
      IT_ALV-WERKS = IT_DATA-WERKS.
      IT_ALV-ZZTYPE = IT_DATA-ZZTYPE.
      IT_ALV-MIC = IT_MIC-MIC.
      IT_ALV-MICDES = IT_MIC-MICDES.
      IT_ALV-UOM = IT_MIC-UOM.
      IT_ALV-METHOD = IT_MIC-METHOD.
      IT_ALV-MICMIN = IT_MIC-MICMIN.
      IT_ALV-MICMAX = IT_MIC-MICMAX.

      " Fix (permintaan user 17/07/2026): tambahan capture IT_MIC-MICMIT (nilai numerik)
      " di SEMUA jalur sukses, bukan cuma jalur fallback MITTELWERT - dibutuhkan sebagai
      " input SUM untuk averaging (FORM AGGREGATE_MIC_VALUES). Juga tambahkan validasi
      " ANZWERTG > 0 di fallback terakhir (konsisten dengan ZQMI_COA_F01) supaya kalau
      " memang tidak ada data sama sekali, CMICMIT jatuh ke '-' - bukan salah tampil "0.000".
      CLEAR IT_MIC-MICMIT.
      " Enhancement (user 18/07/2026): untuk MIC mapping JR (Conv/Base),
      " nilai = rata-rata sibling roll 1 mother roll (lihat GET_JR_AVG).
      DATA: LV_ISJR TYPE C, LV_JRVAL TYPE QAMR-MITTELWERT.
      DATA: LV_JRCNT TYPE I.
      CLEAR: LV_ISJR, LV_JRVAL, LV_JRCNT.
      PERFORM GET_JR_AVG USING IT_DATA-VBELN
              IT_MIC-INS IT_MIC-MIC
                      CHANGING LV_ISJR LV_JRVAL LV_JRCNT.
      IF LV_ISJR = 'X'.
        CLEAR: IT_ALV-CMICMIT, IT_MIC-MICMIT.
        IF LV_JRCNT > 0.
          PERFORM MICFMT USING IT_MIC-MIC IT_DATA-WERKS
                  CHANGING GV_DEC GV_UOM.
          WRITE LV_JRVAL TO IT_ALV-CMICMIT
                EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
          IT_MIC-MICMIT = LV_JRVAL.
        ELSE.
          IT_ALV-CMICMIT = '-'.
          CLEAR IT_MIC-MICMIT.
        ENDIF.
      ELSE.
      IF IT_MIC-INS IS NOT INITIAL.
        SELECT SINGLE CODE1 INTO IT_ALV-CMICMIT
          FROM QAMR
          WHERE PRUEFLOS = IT_MIC-INS
            AND MERKNR = IT_MIC-MERKNR.

        IF IT_ALV-CMICMIT IS INITIAL.
          " Ambil nilai single result (cycle) terakhir dari QASE untuk MVTR/OTR
          IF IT_MIC-MIC CS 'MVTR' OR IT_MIC-MIC CS 'OTR'.
            " Enhancement (Baginda, 22/07/2026): rata-rata
            " last-cycle (DETAILERG) barrier value lintas
            " SEMUA inspection lot SR-Converting di DO ini
            " (per JR batch), bukan 1 lot & 1 cycle acak
            " (bug lama: sort by PROBENR).
            DATA: LV_BARVAL TYPE QAMR-MITTELWERT.
            DATA: LV_BARCNT TYPE I.
            CLEAR: LV_BARVAL, LV_BARCNT.
            PERFORM GET_BAR_AVG USING IT_DATA-VBELN
                    IT_MIC-MIC
                    CHANGING LV_BARVAL LV_BARCNT.
            IF LV_BARCNT > 0.
              PERFORM MICFMT USING IT_MIC-MIC IT_DATA-WERKS
                      CHANGING GV_DEC GV_UOM.
              WRITE LV_BARVAL TO IT_ALV-CMICMIT
                    EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
              IT_MIC-MICMIT = LV_BARVAL.
            ENDIF.
          ENDIF.

          " Fallback ke rata-rata (MITTELWERT), divalidasi via ANZWERTG > 0
          IF IT_ALV-CMICMIT IS INITIAL.
            DATA: LV_ANZWERTG TYPE QAMR-ANZWERTG.
            CLEAR LV_ANZWERTG.
            SELECT SINGLE MITTELWERT ANZWERTG INTO (IT_MIC-MICMIT, LV_ANZWERTG)
              FROM QAMR
              WHERE PRUEFLOS = IT_MIC-INS
                AND MERKNR = IT_MIC-MERKNR.
            IF SY-SUBRC = 0 AND LV_ANZWERTG > 0.
              PERFORM MICFMT USING IT_MIC-MIC IT_DATA-WERKS
                      CHANGING GV_DEC GV_UOM.
              WRITE IT_MIC-MICMIT TO IT_ALV-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
            ELSE.
              IT_ALV-CMICMIT = '-'.
              CLEAR IT_MIC-MICMIT.
            ENDIF.
          ENDIF.
        ENDIF.
      ELSE.
        IT_ALV-CMICMIT = '-'.
      ENDIF.
      ENDIF.
      IT_ALV-MICMIT = IT_MIC-MICMIT.
      IT_ALV-INS = IT_MIC-INS.

      " --- BEGIN ZLOG_COA CHECK ---
      DATA: BEGIN OF LT_ZLOG OCCURS 0,
              SEQ LIKE ZLOG_COA-SEQ,
              VALUE1 LIKE ZLOG_COA-VALUE1,
              VALUE2 LIKE ZLOG_COA-VALUE2,
            END OF LT_ZLOG.
      CLEAR LT_ZLOG. REFRESH LT_ZLOG.
      SELECT SEQ VALUE1 VALUE2 INTO TABLE LT_ZLOG FROM ZLOG_COA
        WHERE PRUEFLOS = IT_MIC-INS
          AND MIC = IT_ALV-MIC
          AND KUNNR = IT_DATA-KUNAG
          AND DELETION <> 'X'.
      IF SY-SUBRC = 0.
        SORT LT_ZLOG BY SEQ DESCENDING.
        CLEAR LT_ZLOG.
        READ TABLE LT_ZLOG INDEX 1.
        IF LT_ZLOG-VALUE2 IS NOT INITIAL.
          IT_ALV-CMICMIT = LT_ZLOG-VALUE2.
        ELSEIF LT_ZLOG-VALUE1 IS NOT INITIAL.
          PERFORM MICFMT USING IT_MIC-MIC IT_DATA-WERKS
                  CHANGING GV_DEC GV_UOM.
          WRITE LT_ZLOG-VALUE1 TO IT_ALV-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
          IT_ALV-MICMIT = LT_ZLOG-VALUE1. " FIX: Update numeric value for aggregation
        ENDIF.
      ENDIF.
      " --- END ZLOG_COA CHECK ---

      APPEND IT_ALV.
    ENDLOOP.

  ENDLOOP.

  " Enhancement (permintaan user 17/07/2026): rata-ratakan CMICMIT untuk MIC yang sama
  " dalam 1 DO (VBELN+MATNR+MIC), logic sama seperti ZQMI_COA_F01 - bedanya di sini baris
  " TETAP tampil per DO item (tidak di-collapse), hanya value-nya yang ditimpa hasil rata-rata.
  PERFORM AGGREGATE_MIC_VALUES.

  SORT IT_ALV BY VBELN POSNR CHARG MIC.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form AGGREGATE_MIC_VALUES
*&---------------------------------------------------------------------*
* Enhancement (permintaan user 17/07/2026): Rata-ratakan CMICMIT untuk MIC yang sama
* dalam 1 DO (key: VBELN+MATNR+MIC), logic SAMA seperti "Enhancement: Aggregate/Average
* MIC results" di ZQMI_COA_F01 (sum per grup, count per grup, kalau ADA SATU SAJA batch
* dengan CMICMIT='-' maka SELURUH grup jadi '-', kalau tidak dirata-rata dan diformat
* 3 desimal HANYA jika jumlah batch > 1 dan SUM <> 0). PERBEDAAN dengan ZQMI_COA_F01:
* baris IT_ALV TIDAK di-collapse jadi 1 baris per MIC - semua baris (per DO item/batch)
* tetap ada, hanya field CMICMIT-nya yang ditimpa dengan hasil rata-rata grupnya.
* Catatan teknis: logic finalize-grup ditulis 2x inline (bukan FORM terpisah) karena
* IT_AVG adalah internal table lokal - FORM lain tidak bisa mereferensikan tipenya
* via LIKE lintas FORM di ABAP 7.31 kalau deklarasinya lokal di FORM ini.
FORM AGGREGATE_MIC_VALUES.
  DATA: BEGIN OF IT_AVG OCCURS 0,
          VBELN   LIKE LIPS-VBELN,
          MATNR   LIKE LIPS-MATNR,
          MIC     TYPE QAMV-VERWMERKM,
          CMICMIT TYPE C LENGTH 20,
        END OF IT_AVG.

  DATA: LV_SUM       TYPE QAMR-MITTELWERT,
        LV_COUNT     TYPE I,
        LV_HAS_EMPTY TYPE C,
        LV_AVG_NUM   TYPE QAMR-MITTELWERT.
  DATA: LS_CUR_VBELN     LIKE LIPS-VBELN,
        LS_CUR_MATNR     LIKE LIPS-MATNR,
        LS_CUR_MIC       TYPE QAMV-VERWMERKM,
        LS_FIRST_CMICMIT TYPE C LENGTH 20.
  DATA: LS_CUR_WERKS LIKE LIPS-WERKS.

  CLEAR: LV_SUM, LV_COUNT, LV_HAS_EMPTY, LS_CUR_VBELN, LS_CUR_MATNR, LS_CUR_MIC, LS_FIRST_CMICMIT.
  REFRESH IT_AVG.

  IF IT_ALV[] IS INITIAL.
    RETURN.
  ENDIF.

  DATA: IT_UNIQUE LIKE STANDARD TABLE OF IT_ALV WITH HEADER LINE.
  IT_UNIQUE[] = IT_ALV[].
  SORT IT_UNIQUE BY VBELN MATNR MIC INS.
  DELETE ADJACENT DUPLICATES FROM IT_UNIQUE COMPARING VBELN MATNR MIC INS.

  SORT IT_UNIQUE BY VBELN MATNR MIC.
  SORT IT_ALV BY VBELN MATNR MIC.

  LOOP AT IT_UNIQUE.
    IF LS_CUR_VBELN NE IT_UNIQUE-VBELN OR LS_CUR_MATNR NE IT_UNIQUE-MATNR OR LS_CUR_MIC NE IT_UNIQUE-MIC.
      IF LV_COUNT > 0.
        CLEAR IT_AVG.
        IT_AVG-VBELN = LS_CUR_VBELN.
        IT_AVG-MATNR = LS_CUR_MATNR.
        IT_AVG-MIC   = LS_CUR_MIC.
        IT_AVG-CMICMIT = LS_FIRST_CMICMIT.
        IF LV_COUNT > 0.
          LV_AVG_NUM = LV_SUM / LV_COUNT.
          IF LV_COUNT > 1 AND LV_SUM <> 0.
            PERFORM MICFMT USING LS_CUR_MIC LS_CUR_WERKS
                    CHANGING GV_DEC GV_UOM.
            WRITE LV_AVG_NUM TO IT_AVG-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
          ENDIF.
        ENDIF.
        APPEND IT_AVG.
      ENDIF.

      LS_CUR_VBELN = IT_UNIQUE-VBELN.
      LS_CUR_MATNR = IT_UNIQUE-MATNR.
      LS_CUR_MIC   = IT_UNIQUE-MIC.
      LS_CUR_WERKS = IT_UNIQUE-WERKS.
      LS_FIRST_CMICMIT = IT_UNIQUE-CMICMIT.
      IF IT_UNIQUE-CMICMIT = '-'.
        LV_SUM = 0.
        LV_COUNT = 0.
      ELSE.
        LV_SUM = IT_UNIQUE-MICMIT.
        LV_COUNT = 1.
      ENDIF.
    ELSE.
      IF IT_UNIQUE-CMICMIT <> '-'.
        LV_SUM = LV_SUM + IT_UNIQUE-MICMIT.
        LV_COUNT = LV_COUNT + 1.
        IF LS_FIRST_CMICMIT = '-'.
          LS_FIRST_CMICMIT = IT_UNIQUE-CMICMIT.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDLOOP.

  IF LV_COUNT > 0.
    CLEAR IT_AVG.
    IT_AVG-VBELN = LS_CUR_VBELN.
    IT_AVG-MATNR = LS_CUR_MATNR.
    IT_AVG-MIC   = LS_CUR_MIC.
    IT_AVG-CMICMIT = LS_FIRST_CMICMIT.
    IF LV_HAS_EMPTY = 'X'.
      IT_AVG-CMICMIT = '-'.
    ELSE.
      LV_AVG_NUM = LV_SUM / LV_COUNT.
      IF LV_COUNT > 1 AND LV_SUM <> 0.
        PERFORM MICFMT USING LS_CUR_MIC LS_CUR_WERKS
                CHANGING GV_DEC GV_UOM.
        WRITE LV_AVG_NUM TO IT_AVG-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.
      ENDIF.
    ENDIF.
    APPEND IT_AVG.
  ENDIF.

  SORT IT_AVG BY VBELN MATNR MIC.

  " Timpakan value hasil rata-rata ke SEMUA baris grupnya - baris tetap per DO item
  LOOP AT IT_ALV.
    READ TABLE IT_AVG WITH KEY VBELN = IT_ALV-VBELN MATNR = IT_ALV-MATNR MIC = IT_ALV-MIC BINARY SEARCH.
    IF SY-SUBRC = 0.
      IT_ALV-CMICMIT = IT_AVG-CMICMIT.
      MODIFY IT_ALV.
    ENDIF.
  ENDLOOP.
ENDFORM.


*&---------------------------------------------------------------------*
*& Form GET_TRACED_LOTS
*&---------------------------------------------------------------------*
TYPES: BEGIN OF TY_TRACE_DATA,
         CHARG               TYPE LIPS-CHARG,
         LOT_JR_CONV         TYPE QALS-PRUEFLOS,
         LOT_SR_BASE         TYPE QALS-PRUEFLOS,
         LOT_JR_BASE         TYPE QALS-PRUEFLOS,
         L_JR_CONV_BATCH     TYPE MCH1-CHARG,
         L_SR_BASE_BATCH     TYPE MCH1-CHARG,
         L_JR_BASE_BATCH     TYPE MCH1-CHARG,
         LOT_SR_CONV_SIBLING TYPE QALS-PRUEFLOS,
       END OF TY_TRACE_DATA.
DATA: GT_TRACE_DATA TYPE TABLE OF TY_TRACE_DATA,
      GS_TRACE_DATA TYPE TY_TRACE_DATA.

FORM GET_TRACED_LOTS.
  DATA: L_AUFNR LIKE AFPO-AUFNR,
        L_MBLNR LIKE MSEG-MBLNR,
        L_MATNR LIKE MSEG-MATNR,
        L_CHARG LIKE MSEG-CHARG,
        L_LICHA LIKE MCH1-LICHA,
        L_LEN TYPE I,
        L_TEMP TYPE I.

  DATA: LV_SEARCH_SR TYPE CHARG_D,
        LV_LATEST_SR TYPE CHARG_D.

  DATA: LV_FALLBACK_AUFNR_1 LIKE MSEG-AUFNR,
        LV_FALLBACK_PARENT_1 LIKE MSEG-CHARG,
        LV_FALLBACK_AUFNR_2 LIKE MSEG-AUFNR,
        LV_FALLBACK_PARENT_2 LIKE MSEG-CHARG.

  CLEAR: LOT_SR_CONV, LOT_JR_CONV, LOT_SR_BASE, LOT_JR_BASE,
         L_JR_CONV_BATCH, L_SR_BASE_BATCH, L_JR_BASE_BATCH,
         GS_TRACE_DATA.

  SORT GT_TRACE_DATA BY CHARG.
  READ TABLE GT_TRACE_DATA INTO GS_TRACE_DATA WITH KEY CHARG = IT_DATA-CHARG BINARY SEARCH.
  IF SY-SUBRC = 0.
    L_JR_CONV_BATCH = GS_TRACE_DATA-L_JR_CONV_BATCH.
    LOT_JR_CONV     = GS_TRACE_DATA-LOT_JR_CONV.
    L_SR_BASE_BATCH = GS_TRACE_DATA-L_SR_BASE_BATCH.
    LOT_SR_BASE     = GS_TRACE_DATA-LOT_SR_BASE.
    L_JR_BASE_BATCH = GS_TRACE_DATA-L_JR_BASE_BATCH.
    LOT_JR_BASE     = GS_TRACE_DATA-LOT_JR_BASE.
    IF LOT_SR_CONV IS INITIAL.
      LOT_SR_CONV = GS_TRACE_DATA-LOT_SR_CONV_SIBLING.
    ENDIF.
    RETURN.
  ENDIF.

  " 1. SR Converting Lot
  SELECT SINGLE PRUEFLOS INTO LOT_SR_CONV FROM QALS WHERE CHARG = IT_DATA-CHARG AND ART = 'Z04'.

  " Fallback 1: Jika DO item adalah SR yang terkena ZQM0016
  IF LOT_SR_CONV IS INITIAL.
    PERFORM GET_ORIGINAL_BATCH USING IT_DATA-CHARG CHANGING LV_SEARCH_SR.
    IF LV_SEARCH_SR NE IT_DATA-CHARG.
      SELECT SINGLE PRUEFLOS INTO LOT_SR_CONV FROM QALS WHERE CHARG = LV_SEARCH_SR AND ART = 'Z04'.
    ENDIF.
  ENDIF.

  " Fallback 2: Jika DO item adalah Carton (Tidak punya Lot Z04)
  " Kita ekstrak batch SR-nya dari string Mother Roll Carton (IT_DATA-NOMSR)
  IF LOT_SR_CONV IS INITIAL AND IT_DATA-NOMSR IS NOT INITIAL.
    DATA: V_LINE_L  TYPE C LENGTH 20,
          V_CODE_L  TYPE C LENGTH 20,
          V_MOYE_L  TYPE C LENGTH 20,
          V_SEQ_L   TYPE C LENGTH 20,
          V_DUMMY_L TYPE C LENGTH 50,
          L_MROLL_L TYPE C LENGTH 50,
          LV_SR_OBJEK TYPE AUSP-OBJEK,
          LV_SR_BATCH TYPE MCH1-CHARG.

    SPLIT IT_DATA-NOMSR AT SPACE INTO V_LINE_L V_CODE_L V_MOYE_L V_SEQ_L V_DUMMY_L.
    CONCATENATE V_LINE_L V_CODE_L V_MOYE_L V_SEQ_L INTO L_MROLL_L SEPARATED BY SPACE.

    IF L_MROLL_L IS NOT INITIAL.
      SELECT SINGLE OBJEK INTO LV_SR_OBJEK FROM AUSP
        WHERE ATINN = ATINN_ROLL
          AND ATWRT = L_MROLL_L
          AND KLART = '023'.
      IF SY-SUBRC = 0.
        SELECT SINGLE CHARG INTO LV_SR_BATCH FROM INOB WHERE CUOBJ = LV_SR_OBJEK.
        IF SY-SUBRC = 0.
          SELECT SINGLE PRUEFLOS INTO LOT_SR_CONV FROM QALS WHERE CHARG = LV_SR_BATCH AND ART = 'Z04'.
          IF LOT_SR_CONV IS INITIAL.
            " Jika SR anak dari Carton ini terkena ZQM0016
            PERFORM GET_ORIGINAL_BATCH USING LV_SR_BATCH CHANGING LV_SEARCH_SR.
            IF LV_SEARCH_SR NE LV_SR_BATCH.
              SELECT SINGLE PRUEFLOS INTO LOT_SR_CONV FROM QALS WHERE CHARG = LV_SEARCH_SR AND ART = 'Z04'.
            ENDIF.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDIF.


  IF LOT_SR_CONV IS INITIAL.
    PERFORM GET_ORIGINAL_BATCH USING IT_DATA-CHARG CHANGING LV_SEARCH_SR.
    CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
      EXPORTING
        CHARG_S = LV_SEARCH_SR
      IMPORTING
        CHARG_J = L_JR_CONV_BATCH.
    " --- BEGIN FALLBACK WRAPPER ---
    " Jika JR gagal ditemukan, mungkin terputus oleh Change Grade (309) di tengah hierarki
    IF L_JR_CONV_BATCH IS INITIAL.
      PERFORM GET_VALID_ORDER_FROM_MSEG USING LV_SEARCH_SR CHANGING LV_FALLBACK_AUFNR_1.
      IF LV_FALLBACK_AUFNR_1 IS NOT INITIAL.
        PERFORM GET_VALID_COMPONENT_FROM_MSEG USING LV_FALLBACK_AUFNR_1 CHANGING LV_FALLBACK_PARENT_1.
        IF LV_FALLBACK_PARENT_1 IS NOT INITIAL.
          " Bypass change grade parent
          PERFORM GET_ORIGINAL_BATCH USING LV_FALLBACK_PARENT_1 CHANGING LV_SEARCH_SR.
          " Coba panggil lagi
          CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
            EXPORTING
              CHARG_S = LV_SEARCH_SR
            IMPORTING
              CHARG_J = L_JR_CONV_BATCH.
        ENDIF.
      ENDIF.
    ENDIF.
    " --- END FALLBACK WRAPPER ---

    IF L_JR_CONV_BATCH IS NOT INITIAL.
      REFRESH T_SR.
      CALL FUNCTION 'ZQM_GET_BATCH_SR_BY_JR'
        EXPORTING
          CHARGJR = L_JR_CONV_BATCH
        TABLES
          T_SR    = T_SR.

      LOOP AT T_SR.
        PERFORM GET_NEWEST_BATCH USING T_SR-CHARG CHANGING LV_LATEST_SR.
        SELECT SINGLE PRUEFLOS INTO LOT_SR_CONV FROM QALS WHERE CHARG = LV_LATEST_SR AND ART = 'Z04'.
        IF LOT_SR_CONV IS NOT INITIAL.
          EXIT.
        ENDIF.
      ENDLOOP.
    ENDIF.
  ELSE.
    PERFORM GET_ORIGINAL_BATCH USING IT_DATA-CHARG CHANGING LV_SEARCH_SR.
    CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
      EXPORTING
        CHARG_S = LV_SEARCH_SR
      IMPORTING
        CHARG_J = L_JR_CONV_BATCH.
    " --- BEGIN FALLBACK WRAPPER ---
    " Jika JR gagal ditemukan, mungkin terputus oleh Change Grade (309) di tengah hierarki
    IF L_JR_CONV_BATCH IS INITIAL.
      PERFORM GET_VALID_ORDER_FROM_MSEG USING LV_SEARCH_SR CHANGING LV_FALLBACK_AUFNR_1.
      IF LV_FALLBACK_AUFNR_1 IS NOT INITIAL.
        PERFORM GET_VALID_COMPONENT_FROM_MSEG USING LV_FALLBACK_AUFNR_1 CHANGING LV_FALLBACK_PARENT_1.
        IF LV_FALLBACK_PARENT_1 IS NOT INITIAL.
          " Bypass change grade parent
          PERFORM GET_ORIGINAL_BATCH USING LV_FALLBACK_PARENT_1 CHANGING LV_SEARCH_SR.
          " Coba panggil lagi
          CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
            EXPORTING
              CHARG_S = LV_SEARCH_SR
            IMPORTING
              CHARG_J = L_JR_CONV_BATCH.
        ENDIF.
      ENDIF.
    ENDIF.
    " --- END FALLBACK WRAPPER ---
  ENDIF.

  " 2. JR Converting Lot
  IF L_JR_CONV_BATCH IS NOT INITIAL.
    SELECT SINGLE PRUEFLOS INTO LOT_JR_CONV FROM QALS WHERE CHARG = L_JR_CONV_BATCH AND ( ART = 'Z02' OR ART = 'Z03' ).
    IF LOT_JR_CONV IS INITIAL.
      PERFORM GET_JR_SIBLING_LOT USING L_JR_CONV_BATCH CHANGING LOT_JR_CONV.
    ENDIF.
  ENDIF.

  " 3. Cari SR Base Film Batch
  IF L_JR_CONV_BATCH IS NOT INITIAL.
    PERFORM GET_VALID_ORDER_FROM_MSEG USING L_JR_CONV_BATCH CHANGING L_AUFNR.

    IF L_AUFNR IS NOT INITIAL.
      PERFORM GET_VALID_COMPONENT_FROM_MSEG USING L_AUFNR CHANGING L_CHARG.
      IF L_CHARG IS NOT INITIAL.
        SELECT SINGLE MATNR INTO L_MATNR FROM MCH1 WHERE CHARG = L_CHARG.
      ENDIF.

      IF L_CHARG IS NOT INITIAL.
        L_LEN = STRLEN( L_MATNR ).
        L_TEMP = L_LEN - 1.
        IF L_MATNR(2) = 'SR' AND ( L_MATNR+L_TEMP(1) = 'A' OR L_MATNR+L_TEMP(1) = 'O' ).
          SELECT SINGLE LICHA INTO L_LICHA FROM MCH1 WHERE MATNR = L_MATNR AND CHARG = L_CHARG.
          IF L_LICHA IS NOT INITIAL.
            L_SR_BASE_BATCH = L_LICHA.
          ELSE.
            L_SR_BASE_BATCH = L_CHARG.
          ENDIF.
        ELSE.
          L_SR_BASE_BATCH = L_CHARG.
        ENDIF.
      ENDIF.
    ENDIF.
  ELSE.
    " Jika tidak ada JR Conv, mungkin inputnya langsung SR Base?
    L_SR_BASE_BATCH = IT_DATA-CHARG.
  ENDIF.

  " Fix dinamis: JR yang ditemukan di atas (L_JR_CONV_BATCH) ternyata tidak punya turunan
  " SR Base Film. Artinya JR tsb sebenarnya JR Base Film (terminal), dan batch DO ini
  " sendiri sudah SR Base Film - bukan SR Converting.
  " Lakukan relabeling batch & lot supaya tracing lanjut dengan benar ke JR Base Film.
  IF L_JR_CONV_BATCH IS NOT INITIAL AND L_SR_BASE_BATCH IS INITIAL.
    L_JR_BASE_BATCH = L_JR_CONV_BATCH.
    LOT_JR_BASE     = LOT_JR_CONV.
    L_SR_BASE_BATCH = IT_DATA-CHARG.
    LOT_SR_BASE     = LOT_SR_CONV.
    CLEAR: L_JR_CONV_BATCH, LOT_JR_CONV, LOT_SR_CONV.
  ENDIF.

  " 3. SR Base Film Lot
  IF L_SR_BASE_BATCH IS NOT INITIAL AND LOT_SR_BASE IS INITIAL.
    SELECT SINGLE PRUEFLOS INTO LOT_SR_BASE FROM QALS WHERE CHARG = L_SR_BASE_BATCH AND ART = 'Z04'.

    IF L_JR_BASE_BATCH IS INITIAL. " Skip re-search kalau JR Base sudah ketemu dari re-labeling di atas
    IF LOT_SR_BASE IS INITIAL.
      PERFORM GET_ORIGINAL_BATCH USING L_SR_BASE_BATCH CHANGING LV_SEARCH_SR.
      CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
        EXPORTING
          CHARG_S = LV_SEARCH_SR
        IMPORTING
          CHARG_J = L_JR_BASE_BATCH.
    " --- BEGIN FALLBACK WRAPPER ---
    " Jika JR gagal ditemukan, mungkin terputus oleh Change Grade (309) di tengah hierarki
    IF L_JR_BASE_BATCH IS INITIAL.
      PERFORM GET_VALID_ORDER_FROM_MSEG USING LV_SEARCH_SR CHANGING LV_FALLBACK_AUFNR_2.
      IF LV_FALLBACK_AUFNR_2 IS NOT INITIAL.
        PERFORM GET_VALID_COMPONENT_FROM_MSEG USING LV_FALLBACK_AUFNR_2 CHANGING LV_FALLBACK_PARENT_2.
        IF LV_FALLBACK_PARENT_2 IS NOT INITIAL.
          " Bypass change grade parent
          PERFORM GET_ORIGINAL_BATCH USING LV_FALLBACK_PARENT_2 CHANGING LV_SEARCH_SR.
          " Coba panggil lagi
          CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
            EXPORTING
              CHARG_S = LV_SEARCH_SR
            IMPORTING
              CHARG_J = L_JR_BASE_BATCH.
        ENDIF.
      ENDIF.
    ENDIF.
    " --- END FALLBACK WRAPPER ---

      IF L_JR_BASE_BATCH IS NOT INITIAL.
        REFRESH T_SR.
        CALL FUNCTION 'ZQM_GET_BATCH_SR_BY_JR'
          EXPORTING
            CHARGJR = L_JR_BASE_BATCH
          TABLES
            T_SR    = T_SR.

        LOOP AT T_SR.
          PERFORM GET_NEWEST_BATCH USING T_SR-CHARG CHANGING LV_LATEST_SR.
          SELECT SINGLE PRUEFLOS INTO LOT_SR_BASE FROM QALS WHERE CHARG = LV_LATEST_SR AND ART = 'Z04'.
          IF LOT_SR_BASE IS NOT INITIAL.
            EXIT.
          ENDIF.
        ENDLOOP.
      ENDIF.
    ELSE.
      PERFORM GET_ORIGINAL_BATCH USING L_SR_BASE_BATCH CHANGING LV_SEARCH_SR.
      CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
        EXPORTING
          CHARG_S = LV_SEARCH_SR
        IMPORTING
          CHARG_J = L_JR_BASE_BATCH.
    " --- BEGIN FALLBACK WRAPPER ---
    " Jika JR gagal ditemukan, mungkin terputus oleh Change Grade (309) di tengah hierarki
    IF L_JR_BASE_BATCH IS INITIAL.
      PERFORM GET_VALID_ORDER_FROM_MSEG USING LV_SEARCH_SR CHANGING LV_FALLBACK_AUFNR_2.
      IF LV_FALLBACK_AUFNR_2 IS NOT INITIAL.
        PERFORM GET_VALID_COMPONENT_FROM_MSEG USING LV_FALLBACK_AUFNR_2 CHANGING LV_FALLBACK_PARENT_2.
        IF LV_FALLBACK_PARENT_2 IS NOT INITIAL.
          " Bypass change grade parent
          PERFORM GET_ORIGINAL_BATCH USING LV_FALLBACK_PARENT_2 CHANGING LV_SEARCH_SR.
          " Coba panggil lagi
          CALL FUNCTION 'ZQM_GET_BATCH_JR_BY_SR'
            EXPORTING
              CHARG_S = LV_SEARCH_SR
            IMPORTING
              CHARG_J = L_JR_BASE_BATCH.
        ENDIF.
      ENDIF.
    ENDIF.
    " --- END FALLBACK WRAPPER ---
    ENDIF.
    ENDIF. " penutup guard L_JR_BASE_BATCH IS INITIAL
  ENDIF.

  " 4. JR Base Film Lot
  IF L_JR_BASE_BATCH IS NOT INITIAL AND LOT_JR_BASE IS INITIAL.
    SELECT SINGLE PRUEFLOS INTO LOT_JR_BASE FROM QALS WHERE CHARG = L_JR_BASE_BATCH AND ( ART = 'Z02' OR ART = 'Z03' ).
    IF LOT_JR_BASE IS INITIAL.
      PERFORM GET_JR_SIBLING_LOT USING L_JR_BASE_BATCH CHANGING LOT_JR_BASE.
    ENDIF.
  ENDIF.

  GS_TRACE_DATA-CHARG = IT_DATA-CHARG.
  GS_TRACE_DATA-L_JR_CONV_BATCH = L_JR_CONV_BATCH.
  GS_TRACE_DATA-LOT_JR_CONV = LOT_JR_CONV.
  GS_TRACE_DATA-L_SR_BASE_BATCH = L_SR_BASE_BATCH.
  GS_TRACE_DATA-LOT_SR_BASE = LOT_SR_BASE.
  GS_TRACE_DATA-L_JR_BASE_BATCH = L_JR_BASE_BATCH.
  GS_TRACE_DATA-LOT_JR_BASE = LOT_JR_BASE.
  IF GS_TRACE_DATA-LOT_SR_CONV_SIBLING IS INITIAL AND LOT_SR_CONV IS NOT INITIAL.
    GS_TRACE_DATA-LOT_SR_CONV_SIBLING = LOT_SR_CONV.
  ENDIF.
  APPEND GS_TRACE_DATA TO GT_TRACE_DATA.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  GET_ORIGINAL_BATCH
*&---------------------------------------------------------------------*
FORM GET_ORIGINAL_BATCH USING P_BATCH CHANGING P_ORIGINAL_BATCH.
  DATA: LV_OLD_BATCH TYPE CHARG_D.
  P_ORIGINAL_BATCH = P_BATCH.
  DO.
    CLEAR LV_OLD_BATCH.
    SELECT CHARG INTO LV_OLD_BATCH FROM ZBATCHISTORY
      UP TO 1 ROWS
      WHERE NCHARG = P_ORIGINAL_BATCH
      ORDER BY BUDAT DESCENDING UZEIT DESCENDING.
    ENDSELECT.
    IF SY-SUBRC = 0 AND LV_OLD_BATCH IS NOT INITIAL.
      P_ORIGINAL_BATCH = LV_OLD_BATCH.
    ELSE.
      EXIT.
    ENDIF.
  ENDDO.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  GET_NEWEST_BATCH
*&---------------------------------------------------------------------*
FORM GET_NEWEST_BATCH USING P_BATCH CHANGING P_NEWEST_BATCH.
  DATA: LV_NEW_BATCH TYPE CHARG_D.
  P_NEWEST_BATCH = P_BATCH.
  DO.
    CLEAR LV_NEW_BATCH.
    SELECT NCHARG INTO LV_NEW_BATCH FROM ZBATCHISTORY
      UP TO 1 ROWS
      WHERE CHARG = P_NEWEST_BATCH
      ORDER BY BUDAT DESCENDING UZEIT DESCENDING.
    ENDSELECT.
    IF SY-SUBRC = 0 AND LV_NEW_BATCH IS NOT INITIAL.
      P_NEWEST_BATCH = LV_NEW_BATCH.
    ELSE.
      EXIT.
    ENDIF.
  ENDDO.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form GET_MIC
*&---------------------------------------------------------------------*
FORM GET_MIC.
  DATA: INS LIKE QALS-PRUEFLOS.

  CLEAR IT_MIC. REFRESH IT_MIC.

  LOOP AT IT_ZMAP.
    CLEAR INS.
    " Fix (permintaan user 15/07/2026): CLEAR IT_MIC penuh (bukan cuma INS) di awal tiap iterasi.
    " Tanpa ini, kalau SELECT SINGLE MIC saat ini gagal ketemu di QAMV, field MERKNR/MICMIN/
    " MICMAX bisa membawa nilai basi dari MIC sebelumnya yang berhasil - lalu ikut kepakai
    " saat lookup CMICMIT (QAMR) di GET_DATA, menghasilkan value MIC yang salah/tertukar.
    CLEAR IT_MIC.
    IF IT_ZMAP-MAPPING CS 'SR Base Film'.
      INS = LOT_SR_BASE.
    ELSEIF IT_ZMAP-MAPPING CS 'JR Base Film'.
      INS = LOT_JR_BASE.
    ELSEIF IT_ZMAP-MAPPING CS 'SR Converting'.
      INS = LOT_SR_CONV.
    ELSEIF IT_ZMAP-MAPPING CS 'JR Converting'.
      INS = LOT_JR_CONV.
    ELSE.
      INS = LOT_SR_CONV.
    ENDIF.

    IF INS IS NOT INITIAL.
      SELECT SINGLE VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC, IT_MIC-MICDES, IT_MIC-MICMIN, IT_MIC-MICMAX, IT_MIC-MERKNR)
        FROM QAMV
        WHERE PRUEFLOS = INS
          AND VERWMERKM = IT_ZMAP-MIC.
    ELSE.
      SY-SUBRC = 4. " Force fallback if INS is empty
    ENDIF.

    IF SY-SUBRC EQ 0.
      IT_MIC-INS = INS.
      IT_MIC-METHOD = IT_ZMAP-METHOD.
      SELECT SINGLE MASSEINHSW INTO IT_MIC-UOM
        FROM QPMK
        WHERE MKMNR = IT_MIC-MIC.
      APPEND IT_MIC.
    ELSE.
      " Fallback: MIC ada di ZMAP_COA tapi tidak ada di lot / tidak ada lot sama sekali
      IT_MIC-MIC = IT_ZMAP-MIC.
      IT_MIC-INS = INS.
      IT_MIC-METHOD = IT_ZMAP-METHOD.
      SELECT SINGLE KURZTEXT INTO IT_MIC-MICDES FROM QPMT WHERE MKMNR = IT_ZMAP-MIC AND SPRACHE = SY-LANGU.
      SELECT SINGLE MASSEINHSW INTO IT_MIC-UOM FROM QPMK WHERE MKMNR = IT_ZMAP-MIC.
      APPEND IT_MIC.
    ENDIF.
  ENDLOOP.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form DISPLAY_ALV
*&---------------------------------------------------------------------*
FORM DISPLAY_ALV.
  CLEAR: IT_FIELDCAT. REFRESH: IT_FIELDCAT.

  PERFORM ADD_FIELDCAT USING:
    'VBELN'   'Nomor ODO',
    'POSNR'   'Item',
    'CHARG'   'Batch',
    'NOMSR'   'No. Roll SR',
    'NOMJR'   'No. Roll JR',
    'MATNR'   'Material',
    'ZZTYPE'  'Film Type',
    'MIC'     'MIC',
    'MICDES'  'MIC Description',
    'UOM'     'Unit of Measure',
    'METHOD'  'Testing Method',
    'MICMIN'  'Lower Limit',
    'MICMAX'  'Upper Limit',
    'INS'     'Insp. Lot',
    'CMICMIT' 'Value'.

  WA_LAYOUT-ZEBRA = 'X'.
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IS_LAYOUT   = WA_LAYOUT
      IT_FIELDCAT = IT_FIELDCAT
    TABLES
      T_OUTTAB    = IT_ALV
    EXCEPTIONS
      PROGRAM_ERROR = 1
      OTHERS        = 2.
ENDFORM.

*&---------------------------------------------------------------------*
*& Form ADD_FIELDCAT
*&---------------------------------------------------------------------*
FORM ADD_FIELDCAT USING P_FIELDNAME P_SELTEXT.
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-FIELDNAME = P_FIELDNAME.
  WA_FIELDCAT-SELTEXT_M = P_SELTEXT.
  WA_FIELDCAT-SELTEXT_L = P_SELTEXT.
  WA_FIELDCAT-SELTEXT_S = P_SELTEXT.
   APPEND WA_FIELDCAT TO IT_FIELDCAT.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  GET_JR_SIBLING_LOT
*&---------------------------------------------------------------------*
FORM GET_JR_SIBLING_LOT USING P_BATCH TYPE CHARG_D
                        CHANGING P_LOT TYPE QALS-PRUEFLOS.
  DATA: LV_CUOBJ_BM TYPE MCH1-CUOBJ_BM,
        LV_OBJEK TYPE AUSP-OBJEK,
        LV_ROLL_STR TYPE AUSP-ATWRT.

  DATA: BEGIN OF LT_PARTS OCCURS 0,
          PART(50) TYPE C,
        END OF LT_PARTS.
  DATA: LV_PART(50) TYPE C,
        LV_PREFIX(50) TYPE C,
        LV_SEQ_STR(10) TYPE C,
        LV_SEQ_NUM TYPE I,
        LV_LINES TYPE I.

  DATA: LV_IDX TYPE I,
        LV_START TYPE I,
        LV_END TYPE I,
        LV_SEQ_NEW_STR TYPE C LENGTH 3,
        LV_BATCH_NEW TYPE CHARG_D,
        LV_ROLL_NEW TYPE AUSP-ATWRT.

  DATA: BEGIN OF LT_SIBLING_ROLLS OCCURS 0,
          ATWRT TYPE AUSP-ATWRT,
        END OF LT_SIBLING_ROLLS.

  DATA: BEGIN OF LT_CUOBJ OCCURS 0,
          OBJEK TYPE AUSP-OBJEK,
        END OF LT_CUOBJ.

  DATA: BEGIN OF LT_CUOBJ_BM OCCURS 0,
          CUOBJ_BM TYPE MCH1-CUOBJ_BM,
        END OF LT_CUOBJ_BM.

  DATA: BEGIN OF LT_BATCHES OCCURS 0,
          CHARG TYPE MCH1-CHARG,
        END OF LT_BATCHES.

  DATA: BEGIN OF LT_LOTS OCCURS 0,
          PRUEFLOS TYPE QALS-PRUEFLOS,
          CHARG TYPE QALS-CHARG,
        END OF LT_LOTS.

  CLEAR P_LOT.
  IF P_BATCH IS INITIAL.
    RETURN.
  ENDIF.



  " 2. Dapatkan CUOBJ_BM (Internal Object Number) dari tabel MCH1 untuk P_BATCH
  SELECT SINGLE CUOBJ_BM INTO LV_CUOBJ_BM
    FROM MCH1
    WHERE CHARG = P_BATCH.

  IF SY-SUBRC <> 0 OR LV_CUOBJ_BM IS INITIAL.
    RETURN.
  ENDIF.

  LV_OBJEK = LV_CUOBJ_BM.

  " 3. Dapatkan teks Nomor Roll dari AUSP
  SELECT SINGLE ATWRT INTO LV_ROLL_STR
    FROM AUSP
    WHERE OBJEK = LV_OBJEK
      AND ATINN = ATINN_ROLL
      AND KLART = '023'
      AND MAFID = 'O'.

  IF SY-SUBRC <> 0 OR LV_ROLL_STR IS INITIAL.
    RETURN.
  ENDIF.

  " 4. Ekstrak prefix dan sequence dari Nomor Roll (misal: "W CGA 108 001")
  SPLIT LV_ROLL_STR AT SPACE INTO TABLE LT_PARTS.
  DESCRIBE TABLE LT_PARTS LINES LV_LINES.

  IF LV_LINES >= 2.
    CLEAR LT_PARTS.
    READ TABLE LT_PARTS INDEX LV_LINES.
    LV_SEQ_STR = LT_PARTS-PART.

    " Reconstruct prefix
    DATA: LV_IDX_PREFIX TYPE I.
    LV_IDX_PREFIX = 1.
    CLEAR LV_PREFIX.
    WHILE LV_IDX_PREFIX < LV_LINES.
      CLEAR LT_PARTS.
      READ TABLE LT_PARTS INDEX LV_IDX_PREFIX.
      LV_PART = LT_PARTS-PART.
      IF LV_PREFIX IS INITIAL.
        LV_PREFIX = LV_PART.
      ELSE.
        CONCATENATE LV_PREFIX LV_PART INTO LV_PREFIX SEPARATED BY SPACE.
      ENDIF.
      LV_IDX_PREFIX = LV_IDX_PREFIX + 1.
    ENDWHILE.

    " Pastikan karakter terakhir (sequence) adalah angka
    IF LV_SEQ_STR CO '0123456789 '.
      LV_SEQ_NUM = LV_SEQ_STR.

      LV_START = LV_SEQ_NUM - 10.
      LV_END = LV_SEQ_NUM + 10.
      IF LV_START < 1.
        LV_START = 1.
      ENDIF.

      " Generate Sibling Rolls
      LV_IDX = LV_START.
      WHILE LV_IDX <= LV_END.
        IF LV_IDX <> LV_SEQ_NUM.
          UNPACK LV_IDX TO LV_SEQ_NEW_STR. " Akan menghasilkan padding '001' dst
          CONCATENATE LV_PREFIX LV_SEQ_NEW_STR INTO LV_ROLL_NEW SEPARATED BY SPACE.
          LT_SIBLING_ROLLS-ATWRT = LV_ROLL_NEW.
          APPEND LT_SIBLING_ROLLS.
        ENDIF.
        LV_IDX = LV_IDX + 1.
      ENDWHILE.

      IF LT_SIBLING_ROLLS[] IS NOT INITIAL.
        " 5. Konversi balik Nomor Roll Sibling ke Batch Sibling (CUOBJ)
          SORT LT_SIBLING_ROLLS BY ATWRT.
          DELETE ADJACENT DUPLICATES FROM LT_SIBLING_ROLLS COMPARING ATWRT.
        SELECT OBJEK INTO TABLE LT_CUOBJ
          FROM AUSP
          FOR ALL ENTRIES IN LT_SIBLING_ROLLS
          WHERE ATINN = ATINN_ROLL
            AND ATWRT = LT_SIBLING_ROLLS-ATWRT
            AND KLART = '023'
            AND MAFID = 'O'.

        IF LT_CUOBJ[] IS NOT INITIAL.
          " Pindahkan OBJEK (CHAR 50) ke CUOBJ_BM (NUMC 18) agar kompatibel dengan FOR ALL ENTRIES
          LOOP AT LT_CUOBJ.
            LT_CUOBJ_BM-CUOBJ_BM = LT_CUOBJ-OBJEK.
            APPEND LT_CUOBJ_BM.
          ENDLOOP.

          " 6. Dapatkan CHARG dari MCH1
          IF LT_CUOBJ_BM[] IS NOT INITIAL.
              SORT LT_CUOBJ_BM BY CUOBJ_BM.
              DELETE ADJACENT DUPLICATES FROM LT_CUOBJ_BM COMPARING CUOBJ_BM.
            SELECT CHARG INTO TABLE LT_BATCHES
              FROM MCH1
              FOR ALL ENTRIES IN LT_CUOBJ_BM
              WHERE CUOBJ_BM = LT_CUOBJ_BM-CUOBJ_BM.
          ENDIF.

          IF LT_BATCHES[] IS NOT INITIAL.
            " 7. Cari Lot Inspeksi (QALS)
              SORT LT_BATCHES BY CHARG.
              DELETE ADJACENT DUPLICATES FROM LT_BATCHES COMPARING CHARG.
            SELECT PRUEFLOS CHARG INTO TABLE LT_LOTS
              FROM QALS
              FOR ALL ENTRIES IN LT_BATCHES
              WHERE CHARG = LT_BATCHES-CHARG
                AND ( ART = 'Z02' OR ART = 'Z03' ).

            IF SY-SUBRC = 0.
              SORT LT_LOTS BY PRUEFLOS DESCENDING.
              CLEAR LT_LOTS.
              READ TABLE LT_LOTS INDEX 1.
              IF SY-SUBRC = 0.
                P_LOT = LT_LOTS-PRUEFLOS.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  GET_VALID_ORDER_FROM_MSEG
*&---------------------------------------------------------------------*
* BKTXT dokumen GR (101) yang sedang di-trace. Di-set oleh GET_VALID_ORDER_FROM_MSEG,
* dibaca GET_VALID_COMPONENT_FROM_MSEG. BKTXT = identitas transaksi / nomor roll, dan
* merupakan penghubung yang benar antara posting 101 dan 261 dalam SATU production order.
DATA: GV_TRACE_BKTXT TYPE MKPF-BKTXT.

FORM GET_VALID_ORDER_FROM_MSEG USING P_CHARG CHANGING P_AUFNR.
  DATA: LT_MSEG TYPE TABLE OF MSEG WITH HEADER LINE,
        LT_CANC TYPE TABLE OF MSEG WITH HEADER LINE.
  DATA: LV_COMBINE LIKE AFPO-AUFNR.
  CLEAR P_AUFNR.
  SELECT AUFNR MBLNR MJAHR ZEILE SMBLN SJAHR SMBLP BWART CHARG
    INTO CORRESPONDING FIELDS OF TABLE LT_MSEG
    FROM MSEG
    WHERE CHARG = P_CHARG AND BWART IN ('101', '102')
    %_HINTS ORACLE 'INDEX("MSEG" "MSEG~Z07")'.

  IF SY-SUBRC = 0.
    LT_CANC[] = LT_MSEG[].
    DELETE LT_CANC WHERE SMBLN IS INITIAL.
    LOOP AT LT_CANC.
      DELETE LT_MSEG WHERE MBLNR = LT_CANC-SMBLN AND MJAHR = LT_CANC-SJAHR AND ZEILE = LT_CANC-SMBLP.
    ENDLOOP.
    DELETE LT_MSEG WHERE SMBLN IS NOT INITIAL OR BWART = '102'.

    SORT LT_MSEG BY MBLNR DESCENDING ZEILE DESCENDING.
    READ TABLE LT_MSEG INDEX 1.
    IF SY-SUBRC = 0.
      P_AUFNR = LT_MSEG-AUFNR.

      " Fix A (user 18/07/2026): ambil BKTXT dokumen GR (101) ini, dipakai
      " GET_VALID_COMPONENT_FROM_MSEG untuk memilih komponen 261 pasangan roll ini.
      " Bukti: order 100000072887 punya 8 posting 261 / 4 batch berbeda, dibedakan
      " HANYA oleh BKTXT. Logic lama ambil MBLNR terbesar - salah roll tanpa gejala.
      SELECT SINGLE BKTXT INTO GV_TRACE_BKTXT
        FROM MKPF
        WHERE MBLNR = LT_MSEG-MBLNR
          AND MJAHR = LT_MSEG-MJAHR.

      " Fix B (user 18/07/2026): resolve COLLECTIVE ORDER. AUFNR dari MSEG 101 bisa
      " order referensi (mis. A29000002540) yang TIDAK punya komponen 261 sama sekali;
      " order asli dicari via AFPO-MILL_OC_AUFNR_U. Tanpa ini tracing MATI di hop
      " pertama sehingga MIC level Base Film (mis. PALZTH00) selalu kosong.
      CLEAR LV_COMBINE.
      SELECT SINGLE AUFNR INTO LV_COMBINE
        FROM AFPO
        WHERE MILL_OC_AUFNR_U = P_AUFNR.
      IF SY-SUBRC = 0 AND LV_COMBINE IS NOT INITIAL.
        P_AUFNR = LV_COMBINE.
      ENDIF.
    ENDIF.
  ENDIF.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  GET_VALID_COMPONENT_FROM_MSEG
*&---------------------------------------------------------------------*
FORM GET_VALID_COMPONENT_FROM_MSEG USING P_AUFNR CHANGING P_CHARG.
  DATA: BEGIN OF LT_MKPF OCCURS 0,
          MBLNR LIKE MKPF-MBLNR,
          MJAHR LIKE MKPF-MJAHR,
          BKTXT LIKE MKPF-BKTXT,
        END OF LT_MKPF.
  DATA: LT_MSEG TYPE TABLE OF MSEG WITH HEADER LINE,
        LT_CANC TYPE TABLE OF MSEG WITH HEADER LINE.
  CLEAR P_CHARG.
  SELECT AUFNR MBLNR MJAHR ZEILE SMBLN SJAHR SMBLP BWART CHARG MATNR
    INTO CORRESPONDING FIELDS OF TABLE LT_MSEG
    FROM MSEG
    WHERE AUFNR = P_AUFNR AND BWART IN ('261', '262', '901', '902') AND CHARG <> ''.

  IF SY-SUBRC = 0.
    LT_CANC[] = LT_MSEG[].
    DELETE LT_CANC WHERE SMBLN IS INITIAL.
    LOOP AT LT_CANC.
      DELETE LT_MSEG WHERE MBLNR = LT_CANC-SMBLN AND MJAHR = LT_CANC-SJAHR AND ZEILE = LT_CANC-SMBLP.
    ENDLOOP.
    DELETE LT_MSEG WHERE SMBLN IS NOT INITIAL OR BWART = '262' OR BWART = '902'.

    " Fix BKTXT (user 18/07/2026): buang komponen yang BUKAN milik transaksi/roll yang
    " sama dengan dokumen 101-nya. Satu order bisa punya banyak roll, dan BKTXT adalah
    " satu-satunya pembeda. Kalau BKTXT 101 kosong (data lama), filter dilewati.
    IF GV_TRACE_BKTXT IS NOT INITIAL AND LT_MSEG[] IS NOT INITIAL.
      CLEAR LT_MKPF. REFRESH LT_MKPF.
      SELECT MBLNR MJAHR BKTXT INTO TABLE LT_MKPF
        FROM MKPF
        FOR ALL ENTRIES IN LT_MSEG
        WHERE MBLNR = LT_MSEG-MBLNR
          AND MJAHR = LT_MSEG-MJAHR.
      SORT LT_MKPF BY MBLNR MJAHR.
      LOOP AT LT_MSEG.
        CLEAR LT_MKPF.
        READ TABLE LT_MKPF WITH KEY MBLNR = LT_MSEG-MBLNR
                                    MJAHR = LT_MSEG-MJAHR BINARY SEARCH.
        IF SY-SUBRC <> 0 OR LT_MKPF-BKTXT <> GV_TRACE_BKTXT.
          DELETE LT_MSEG.
        ENDIF.
      ENDLOOP.
    ENDIF.

    SORT LT_MSEG BY MBLNR DESCENDING ZEILE DESCENDING.
    LOOP AT LT_MSEG.
      " Pastikan yang diambil adalah material Base Film (SR/JR), bukan komponen pelengkap
      IF LT_MSEG-MATNR(2) = 'SR' OR LT_MSEG-MATNR(2) = 'JR'.
        P_CHARG = LT_MSEG-CHARG.
        EXIT.
      ENDIF.
    ENDLOOP.
  ENDIF.
ENDFORM.

*&--------------------------------------------------------------------*
*&      Form  MICFMT
*&--------------------------------------------------------------------*
* Fix (user 18/07/2026): sebelumnya WRITE meng-hardcode DECIMALS 3,
* value tidak mengikuti master MIC (mis. SEWESTMZ STELLEN=0 seharusnya
* tampil 55 bukan 54.842). Ambil STELLEN dari QPMK per MIC + plant,
* di-cache di GT_MICFMT. Kalau plant kosong / tidak ketemu -> pakai
* baris manapun (STELLEN sama antar plant).
*&--------------------------------------------------------------------*
*&      Form  GET_JR_AVG
*&--------------------------------------------------------------------*
* Enhancement (user 18/07/2026): untuk MIC ber-mapping JR (Converting /
* Base Film), nilai = RATA-RATA across semua sibling roll JR dalam 1
* mother roll (mis. E EWE 076 001..004), bukan hanya 1 roll yang di-slit
* ke SR-nya. Sebab QC merekam inspeksi JR sekali per order/jumbo di satu
* roll perwakilan; roll lain lot-nya kosong. Hanya lot dengan ANZWERTG>0
* yang ikut rata-rata (skip kosong). P_ISJR='X' bila INSLOT adalah lot JR
* (QALS ART Z02/Z03); bila bukan, caller pakai logika lama (SR tak berubah).
FORM GET_JR_AVG USING P_VBELN P_INSLOT P_MIC
         CHANGING P_ISJR
                  P_VAL TYPE QAMR-MITTELWERT
                  P_CNT TYPE I.
  DATA: L_ART TYPE QALS-ART.
  DATA: L_ICHARG TYPE QALS-CHARG.
  DATA: L_AUFNR TYPE MSEG-AUFNR.
  DATA: L_MK TYPE QAMV-MERKNR.
  DATA: L_MW TYPE QAMR-MITTELWERT, L_AZ TYPE QAMR-ANZWERTG.
  DATA: L_SUM TYPE QAMR-MITTELWERT.
  DATA: BEGIN OF LT_BCH OCCURS 0,
          CHARG TYPE MSEG-CHARG,
        END OF LT_BCH.
  DATA: BEGIN OF LT_JLOT OCCURS 0,
          LOT TYPE QALS-PRUEFLOS,
        END OF LT_JLOT.

  CLEAR: P_ISJR, P_VAL, P_CNT, L_SUM.
  SORT GT_JRAVG BY INSLOT MIC.
  READ TABLE GT_JRAVG INTO GS_JRAVG
       WITH KEY INSLOT = P_INSLOT MIC = P_MIC BINARY SEARCH.
  IF SY-SUBRC = 0.
    P_ISJR = GS_JRAVG-ISJR.
    P_VAL = GS_JRAVG-VAL.
    P_CNT = GS_JRAVG-CNT.
    RETURN.
  ENDIF.

  IF P_INSLOT IS NOT INITIAL.
    CLEAR: L_ART, L_ICHARG.
    SELECT SINGLE ART CHARG INTO (L_ART, L_ICHARG) FROM QALS
      WHERE PRUEFLOS = P_INSLOT.
    IF SY-SUBRC = 0 AND ( L_ART = 'Z02' OR L_ART = 'Z03' ).
      P_ISJR = 'X'.

      " 1) Langsung: nilai lot INSLOT sendiri (yg sudah
      "    ditentukan report per mapping base/converting).
      CLEAR L_MK.
      SELECT SINGLE MERKNR INTO L_MK FROM QAMV
        WHERE PRUEFLOS = P_INSLOT AND VERWMERKM = P_MIC.
      IF L_MK IS NOT INITIAL.
        CLEAR: L_MW, L_AZ.
        SELECT SINGLE MITTELWERT ANZWERTG
          INTO (L_MW, L_AZ) FROM QAMR
          WHERE PRUEFLOS = P_INSLOT AND MERKNR = L_MK.
        IF L_AZ > 0.
          P_VAL = L_MW.
          P_CNT = 1.
        ENDIF.
      ENDIF.

      " 2) Fallback: INSLOT kosong (inspeksi JR direkam di
      "    roll representatif lain dlm 1 production order
      "    yg sama). Rata2 lot JR non-empty se-order.
      IF P_CNT = 0 AND L_ICHARG IS NOT INITIAL.
        CLEAR L_AUFNR.
        SELECT SINGLE AUFNR INTO L_AUFNR FROM MSEG
          WHERE CHARG = L_ICHARG AND BWART = '101'.
        IF L_AUFNR IS NOT INITIAL.
          REFRESH LT_BCH.
          SELECT CHARG INTO TABLE LT_BCH FROM MSEG
            WHERE AUFNR = L_AUFNR AND BWART = '101'.
          SORT LT_BCH BY CHARG.
          DELETE ADJACENT DUPLICATES FROM LT_BCH.
          REFRESH LT_JLOT.
          LOOP AT LT_BCH.
            SELECT PRUEFLOS APPENDING TABLE LT_JLOT
              FROM QALS
              WHERE CHARG = LT_BCH-CHARG
                AND ( ART = 'Z02' OR ART = 'Z03' ).
          ENDLOOP.
          SORT LT_JLOT BY LOT.
          DELETE ADJACENT DUPLICATES FROM LT_JLOT.
          LOOP AT LT_JLOT.
            CLEAR L_MK.
            SELECT SINGLE MERKNR INTO L_MK FROM QAMV
              WHERE PRUEFLOS = LT_JLOT-LOT
                AND VERWMERKM = P_MIC.
            IF L_MK IS NOT INITIAL.
              CLEAR: L_MW, L_AZ.
              SELECT SINGLE MITTELWERT ANZWERTG
                INTO (L_MW, L_AZ) FROM QAMR
                WHERE PRUEFLOS = LT_JLOT-LOT
                  AND MERKNR = L_MK.
              IF L_AZ > 0.
                L_SUM = L_SUM + L_MW.
                P_CNT = P_CNT + 1.
              ENDIF.
            ENDIF.
          ENDLOOP.
          IF P_CNT > 0.
            P_VAL = L_SUM / P_CNT.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDIF.

  CLEAR GS_JRAVG.
  GS_JRAVG-INSLOT = P_INSLOT.
  GS_JRAVG-MIC = P_MIC.
  GS_JRAVG-ISJR = P_ISJR.
  GS_JRAVG-VAL = P_VAL.
  GS_JRAVG-CNT = P_CNT.
  APPEND GS_JRAVG TO GT_JRAVG.
ENDFORM.
FORM GET_BAR_AVG USING P_VBELN P_MIC
         CHANGING P_VAL TYPE QAMR-MITTELWERT
                  P_CNT TYPE I.
  DATA: L_NEWEST TYPE CHARG_D, L_LOT TYPE QALS-PRUEFLOS.
  DATA: L_MK TYPE QAMV-MERKNR, L_ALT TYPE QAMV-VERWMERKM.
  DATA: L_MW TYPE QASE-MESSWERT, L_SUM TYPE QAMR-MITTELWERT.
  DATA: BEGIN OF LT_CH OCCURS 0,
          CHARG TYPE LIPS-CHARG,
        END OF LT_CH.
  DATA: BEGIN OF LT_LOT OCCURS 0,
          LOT TYPE QALS-PRUEFLOS,
        END OF LT_LOT.

  CLEAR: P_VAL, P_CNT, L_SUM.
  SORT GT_BARAVG BY VBELN MIC.
  READ TABLE GT_BARAVG INTO GS_BARAVG
       WITH KEY VBELN = P_VBELN MIC = P_MIC BINARY SEARCH.
  IF SY-SUBRC = 0.
    P_VAL = GS_BARAVG-VAL.
    P_CNT = GS_BARAVG-CNT.
    RETURN.
  ENDIF.

  REFRESH LT_CH.
  LOOP AT IT_DATA WHERE VBELN = P_VBELN.
    IF IT_DATA-CHARG IS NOT INITIAL.
      LT_CH-CHARG = IT_DATA-CHARG.
      COLLECT LT_CH.
    ENDIF.
  ENDLOOP.

  REFRESH LT_LOT.
  LOOP AT LT_CH.
    CLEAR L_NEWEST.
    PERFORM GET_NEWEST_BATCH USING LT_CH-CHARG
                             CHANGING L_NEWEST.
    IF L_NEWEST IS INITIAL.
      L_NEWEST = LT_CH-CHARG.
    ENDIF.
    CLEAR L_LOT.
    SELECT SINGLE PRUEFLOS INTO L_LOT FROM QALS
      WHERE CHARG = L_NEWEST AND ART = 'Z04'.
    IF SY-SUBRC = 0 AND L_LOT IS NOT INITIAL.
      LT_LOT-LOT = L_LOT.
      COLLECT LT_LOT.
    ENDIF.
  ENDLOOP.

  LOOP AT LT_LOT.
    CLEAR L_MK.
    SELECT SINGLE MERKNR INTO L_MK FROM QAMV
      WHERE PRUEFLOS = LT_LOT-LOT AND VERWMERKM = P_MIC.
    IF SY-SUBRC <> 0 OR L_MK IS INITIAL.
      L_ALT = P_MIC.
      IF P_MIC CS 'MVTR'.
        REPLACE FIRST OCCURRENCE OF 'MVTR' IN L_ALT
                WITH 'WVTR'.
      ELSEIF P_MIC CS 'WVTR'.
        REPLACE FIRST OCCURRENCE OF 'WVTR' IN L_ALT
                WITH 'MVTR'.
      ELSEIF P_MIC CS 'O2TR'.
        REPLACE FIRST OCCURRENCE OF 'O2TR' IN L_ALT
                WITH 'OTR'.
      ELSEIF P_MIC CS 'OTR'.
        REPLACE FIRST OCCURRENCE OF 'OTR' IN L_ALT
                WITH 'O2TR'.
      ENDIF.
      IF L_ALT <> P_MIC.
        SELECT SINGLE MERKNR INTO L_MK FROM QAMV
          WHERE PRUEFLOS = LT_LOT-LOT AND VERWMERKM = L_ALT.
      ENDIF.
    ENDIF.
    IF L_MK IS NOT INITIAL.
      CLEAR L_MW.
      SELECT MESSWERT INTO L_MW FROM QASE
        UP TO 1 ROWS
        WHERE PRUEFLOS = LT_LOT-LOT AND MERKNR = L_MK
          AND ATTRIBUT = ''
        ORDER BY DETAILERG DESCENDING.
      ENDSELECT.
      IF SY-SUBRC = 0.
        L_SUM = L_SUM + L_MW.
        P_CNT = P_CNT + 1.
      ENDIF.
    ENDIF.
  ENDLOOP.

  IF P_CNT > 0.
    P_VAL = L_SUM / P_CNT.
  ENDIF.

  CLEAR GS_BARAVG.
  GS_BARAVG-VBELN = P_VBELN.
  GS_BARAVG-MIC = P_MIC.
  GS_BARAVG-VAL = P_VAL.
  GS_BARAVG-CNT = P_CNT.
  APPEND GS_BARAVG TO GT_BARAVG.
ENDFORM.

FORM MICFMT USING P_MIC P_WRK
         CHANGING P_DEC TYPE I
                  P_UOM.
  CLEAR: P_DEC, P_UOM.
  IF P_MIC IS INITIAL.
    RETURN.
  ENDIF.
  READ TABLE GT_MICFMT INTO GS_MICFMT
    WITH KEY MKMNR = P_MIC WERKS = P_WRK.
  IF SY-SUBRC <> 0.
    CLEAR GS_MICFMT.
    GS_MICFMT-MKMNR = P_MIC.
    GS_MICFMT-WERKS = P_WRK.
    IF P_WRK IS NOT INITIAL.
      SELECT SINGLE STELLEN MASSEINHSW
        INTO (GS_MICFMT-STELLEN, GS_MICFMT-UOM)
        FROM QPMK
        WHERE MKMNR = P_MIC
          AND WERKS = P_WRK.
    ELSE.
      SY-SUBRC = 4.
    ENDIF.
    IF SY-SUBRC <> 0.
      SELECT SINGLE STELLEN MASSEINHSW
        INTO (GS_MICFMT-STELLEN, GS_MICFMT-UOM)
        FROM QPMK
        WHERE MKMNR = P_MIC.
    ENDIF.
    APPEND GS_MICFMT TO GT_MICFMT.
  ENDIF.
  P_DEC = GS_MICFMT-STELLEN.
  P_UOM = GS_MICFMT-UOM.
ENDFORM.