FUNCTION ZQM_GET_BATCH_SR_BY_JR.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(CHARGJR) TYPE  CHARG_D
*"     VALUE(DERIVATIVE) TYPE  CHAR2 OPTIONAL
*"     VALUE(POSITION) TYPE  CHAR2 OPTIONAL
*"     REFERENCE(SCRAP) TYPE  BOOLEAN OPTIONAL
*"  TABLES
*"      T_SR STRUCTURE  ZQM_GET_BATCH_SR
*"      T_CABN STRUCTURE  CABN OPTIONAL
*"----------------------------------------------------------------------


  DATA: BEGIN OF IT_BATCH OCCURS 0,
            MBLNR LIKE AUFM-MBLNR,
            MJAHR LIKE AUFM-MJAHR,
            MATNR LIKE AUFM-MATNR,
            WERKS LIKE AUFM-WERKS,
            CHARG LIKE AUFM-CHARG,
            BWART LIKE AUFM-BWART,
            AUFNR LIKE AUFM-AUFNR,
            MENGE LIKE AUFM-MENGE,
            MEINS LIKE AUFM-MEINS,
            SMBLN LIKE MSEG-SMBLN,
            SJAHR LIKE MSEG-SJAHR,
            SMBLP LIKE MSEG-SMBLP,
            BUDAT_MKPF LIKE MSEG-BUDAT_MKPF,
        END OF IT_BATCH.

  DATA: IT_BATCH_JR LIKE IT_BATCH OCCURS 0 WITH HEADER LINE.
  DATA: IT_BATCH_JC LIKE IT_BATCH OCCURS 0 WITH HEADER LINE.
  DATA: IT_BATCH_SR LIKE IT_BATCH OCCURS 0 WITH HEADER LINE.
  DATA: IT_BATCH_SC LIKE IT_BATCH OCCURS 0 WITH HEADER LINE.
  DATA: IT_BATCH_CG LIKE ZBATCHISTORY OCCURS 0 WITH HEADER LINE.
  DATA: WA_BATCH    LIKE IT_BATCH.
  DATA: IT_AFPO LIKE AFPO OCCURS 0 WITH HEADER LINE.
  DATA: T_SR_SS LIKE T_SR OCCURS 0 WITH HEADER LINE.

  DATA: BEGIN OF IT_CHAR OCCURS 0,
            CHARG          TYPE CHARG_D,
            ATINN          TYPE ATINN,
            ATWRT          TYPE ATWRT,
            ATFLV          TYPE ATFLV,
            ATWTB          TYPE ATWTB,
        END OF IT_CHAR.

  DATA: ZZDERIVATIVEMS     TYPE ATINN,
        ZZPOSITIONMS       TYPE ATINN,
        ZZDERIVATIVESS     TYPE ATINN,
        ZZPOSITIONSS       TYPE ATINN,
        ZZCRITERIA         TYPE ATINN,
        ZZWIDTH            TYPE ATINN.

  REFRESH: IT_BATCH_JR, IT_BATCH_JC, IT_BATCH_SR, IT_BATCH_SC, IT_AFPO, T_SR_SS, IT_CHAR.
  CLEAR: IT_BATCH_JR, IT_BATCH_JC, IT_BATCH_SR, IT_BATCH_SC, IT_AFPO, T_SR_SS, IT_CHAR.

  IF T_CABN[] IS INITIAL.
    SELECT SINGLE ATINN INTO ZZDERIVATIVEMS         FROM CABN WHERE ATNAM = 'ZZDERIVATIVEMS'.
    SELECT SINGLE ATINN INTO ZZPOSITIONMS           FROM CABN WHERE ATNAM = 'ZZPOSITIONMS'.
    SELECT SINGLE ATINN INTO ZZDERIVATIVESS         FROM CABN WHERE ATNAM = 'ZZDERIVATIVESS'.
    SELECT SINGLE ATINN INTO ZZPOSITIONSS           FROM CABN WHERE ATNAM = 'ZZPOSITIONSS'.
    SELECT SINGLE ATINN INTO ZZCRITERIA             FROM CABN WHERE ATNAM = 'ZZCRITERIA'.
    SELECT SINGLE ATINN INTO ZZWIDTH                FROM CABN WHERE ATNAM = 'ZZWIDTH'.
  ELSE.
    READ TABLE T_CABN WITH KEY ATNAM = 'ZZDERIVATIVEMS'.
    IF SY-SUBRC EQ 0.
      ZZDERIVATIVEMS = T_CABN-ATINN.
    ENDIF.

    READ TABLE T_CABN WITH KEY ATNAM = 'ZZPOSITIONMS'.
    IF SY-SUBRC EQ 0.
      ZZPOSITIONMS = T_CABN-ATINN.
    ENDIF.

    READ TABLE T_CABN WITH KEY ATNAM = 'ZZDERIVATIVESS'.
    IF SY-SUBRC EQ 0.
      ZZDERIVATIVESS = T_CABN-ATINN.
    ENDIF.

    READ TABLE T_CABN WITH KEY ATNAM = 'ZZPOSITIONSS'.
    IF SY-SUBRC EQ 0.
      ZZPOSITIONSS = T_CABN-ATINN.
    ENDIF.

    READ TABLE T_CABN WITH KEY ATNAM = 'ZZCRITERIA'.
    IF SY-SUBRC EQ 0.
      ZZCRITERIA = T_CABN-ATINN.
    ENDIF.

    READ TABLE T_CABN WITH KEY ATNAM = 'ZZWIDTH'.
    IF SY-SUBRC EQ 0.
      ZZWIDTH = T_CABN-ATINN.
    ENDIF.
  ENDIF.

  SELECT
    AUFM~MBLNR
    AUFM~MJAHR
    AUFM~MATNR
    AUFM~WERKS
    AUFM~CHARG
    AUFM~BWART
    AUFM~AUFNR
    AUFM~MENGE
    AUFM~MEINS
    MSEG~SMBLN
    MSEG~SJAHR
    MSEG~SMBLP
    MSEG~BUDAT_MKPF
  APPENDING CORRESPONDING FIELDS OF TABLE IT_BATCH_JR
  FROM AUFM
  JOIN MSEG ON AUFM~MANDT  =  MSEG~MANDT  AND
               AUFM~MBLNR  =  MSEG~MBLNR  AND
               AUFM~MJAHR  =  MSEG~MJAHR  AND
               AUFM~ZEILE  =  MSEG~ZEILE
  WHERE AUFM~CHARG = CHARGJR
    AND AUFM~BWART IN ('261') %_HINTS ORACLE 'INDEX("MESG" "MSEG~Z07")'.

  SORT IT_BATCH_JR BY MBLNR MJAHR.
  DELETE ADJACENT DUPLICATES FROM IT_BATCH_JR COMPARING MBLNR MJAHR.

  IF IT_BATCH_JR[] IS INITIAL.
    EXIT.
  ENDIF.

  " Get data batch cancelation
  SELECT
    AUFM~MBLNR
    AUFM~MJAHR
    AUFM~MATNR
    AUFM~WERKS
    AUFM~CHARG
    AUFM~BWART
    AUFM~AUFNR
    AUFM~MENGE
    AUFM~MEINS
    MSEG~SMBLN
    MSEG~SJAHR
    MSEG~SMBLP
    MSEG~BUDAT_MKPF
  APPENDING CORRESPONDING FIELDS OF TABLE IT_BATCH_JC
  FROM AUFM
  JOIN MSEG ON AUFM~MANDT  =  MSEG~MANDT  AND
               AUFM~MBLNR  =  MSEG~MBLNR  AND
               AUFM~MJAHR  =  MSEG~MJAHR  AND
               AUFM~ZEILE  =  MSEG~ZEILE
  FOR ALL ENTRIES IN IT_BATCH_JR
  WHERE MSEG~SMBLN = IT_BATCH_JR-MBLNR
    AND MSEG~SJAHR = IT_BATCH_JR-MJAHR %_HINTS ORACLE 'INDEX("MESG" "MSEG~Z10")'.

  SORT IT_BATCH_JC BY SMBLN SJAHR.
  DELETE ADJACENT DUPLICATES FROM IT_BATCH_JC COMPARING SMBLN SJAHR.

  " Eliminate batch cancelation
  LOOP AT IT_BATCH_JC.
    LOOP AT IT_BATCH_JR WHERE MBLNR = IT_BATCH_JC-SMBLN AND MJAHR = IT_BATCH_JC-SJAHR.
      DELETE IT_BATCH_JR.
    ENDLOOP.
  ENDLOOP.

  IF IT_BATCH_JR[] IS INITIAL.
    EXIT.
  ENDIF.

  SELECT *
   INTO CORRESPONDING FIELDS OF TABLE IT_AFPO
   FROM AFPO
   FOR ALL ENTRIES IN IT_BATCH_JR
   WHERE AUFNR = IT_BATCH_JR-AUFNR.

  IF IT_AFPO[] IS INITIAL.
    EXIT.
  ENDIF.

  DELETE IT_AFPO WHERE MILL_OC_AUFNR_U IS INITIAL.

  LOOP AT IT_AFPO.
    CLEAR: IT_BATCH_SR, IT_BATCH_SC, IT_CHAR, WA_BATCH.
    REFRESH: IT_BATCH_SR, IT_BATCH_SC, IT_CHAR.

    SELECT
      AUFM~MBLNR
      AUFM~MJAHR
      AUFM~MATNR
      AUFM~WERKS
      AUFM~CHARG
      AUFM~BWART
      AUFM~AUFNR
      AUFM~MENGE
      AUFM~MEINS
      MSEG~SMBLN
      MSEG~SJAHR
      MSEG~SMBLP
      MSEG~BUDAT_MKPF
      APPENDING CORRESPONDING FIELDS OF TABLE IT_BATCH_SR
      FROM AUFM
      JOIN MSEG ON AUFM~MANDT  =  MSEG~MANDT  AND
                   AUFM~MBLNR  =  MSEG~MBLNR  AND
                   AUFM~MJAHR  =  MSEG~MJAHR  AND
                   AUFM~ZEILE  =  MSEG~ZEILE
      WHERE AUFM~AUFNR = IT_AFPO-MILL_OC_AUFNR_U
        AND AUFM~BWART IN ('101') %_HINTS ORACLE 'INDEX("MESG" "MSEG~Z08")'.

     IF IT_BATCH_SR[] IS INITIAL.
      "Batch Scrap
      IF SCRAP EQ 'X'.
        SELECT MATNR CHARG ERSDA INTO (IT_BATCH_SR-MATNR, IT_BATCH_SR-CHARG, IT_BATCH_SR-BUDAT_MKPF) FROM MCH1 WHERE LICHA EQ IT_AFPO-MILL_OC_AUFNR_U.
          IF SY-SUBRC EQ 0.
            PERFORM GET_DETAIL_CHARACTERISTIC USING IT_BATCH_SR-MATNR IT_BATCH_SR-CHARG ZZCRITERIA CHANGING T_SR-GRADE.
            IF T_SR-GRADE EQ 'S'.
              SELECT SINGLE WERKS INTO IT_BATCH_SR-WERKS FROM MCHA WHERE MATNR EQ IT_BATCH_SR-MATNR AND CHARG EQ IT_BATCH_SR-CHARG.

              APPEND IT_BATCH_SR.
              CLEAR IT_BATCH_SR.
            ENDIF.
          ENDIF.
        ENDSELECT.
      ELSE.
        CONTINUE.
      ENDIF.
    ELSE.
      " Get data batch cancelation
      SELECT
        AUFM~MBLNR
        AUFM~MJAHR
        AUFM~MATNR
        AUFM~WERKS
        AUFM~CHARG
        AUFM~BWART
        AUFM~AUFNR
        AUFM~MENGE
        AUFM~MEINS
        MSEG~SMBLN
        MSEG~SJAHR
        MSEG~SMBLP
        APPENDING CORRESPONDING FIELDS OF TABLE IT_BATCH_SC
        FROM AUFM
        JOIN MSEG ON AUFM~MANDT  =  MSEG~MANDT  AND
                     AUFM~MBLNR  =  MSEG~MBLNR  AND
                     AUFM~MJAHR  =  MSEG~MJAHR  AND
                     AUFM~ZEILE  =  MSEG~ZEILE
        FOR ALL ENTRIES IN IT_BATCH_SR
        WHERE MSEG~SMBLN = IT_BATCH_SR-MBLNR
          AND MSEG~SJAHR = IT_BATCH_SR-MJAHR %_HINTS ORACLE 'INDEX("MESG" "MSEG~Z10")'.

       IF SCRAP EQ 'X'. "Check Scrap
          SELECT MATNR CHARG ERSDA INTO (WA_BATCH-MATNR, WA_BATCH-CHARG, WA_BATCH-BUDAT_MKPF) FROM MCH1 WHERE LICHA EQ IT_AFPO-MILL_OC_AUFNR_U.
            IF SY-SUBRC EQ 0.
              PERFORM GET_DETAIL_CHARACTERISTIC USING WA_BATCH-MATNR WA_BATCH-CHARG ZZCRITERIA CHANGING T_SR-GRADE.
              IF T_SR-GRADE EQ 'S'.
                SELECT SINGLE WERKS INTO WA_BATCH-WERKS FROM MCHA WHERE MATNR EQ WA_BATCH-MATNR AND CHARG EQ WA_BATCH-CHARG.

                APPEND WA_BATCH TO IT_BATCH_SR.
                CLEAR : WA_BATCH,IT_BATCH_SR.
              ENDIF.
            ENDIF.
          ENDSELECT.
        ENDIF.


      " Eliminate batch cancelation
      LOOP AT IT_BATCH_SC.
        LOOP AT IT_BATCH_SR WHERE MBLNR = IT_BATCH_SC-SMBLN AND MJAHR = IT_BATCH_SC-SJAHR.
          DELETE IT_BATCH_SR.
        ENDLOOP.
      ENDLOOP.
    ENDIF.


    IF IT_BATCH_SR[] IS INITIAL.
      CONTINUE.
    ENDIF.

    SELECT CHARG AUSP~ATINN AUSP~ATWRT AUSP~ATFLV
      INTO CORRESPONDING FIELDS OF TABLE IT_CHAR
      FROM MCH1
      JOIN AUSP  ON AUSP~OBJEK EQ MCH1~CUOBJ_BM
       FOR ALL ENTRIES IN IT_BATCH_SR
     WHERE MATNR EQ IT_BATCH_SR-MATNR
       AND CHARG EQ IT_BATCH_SR-CHARG
       AND KLART EQ '023'
       AND AUSP~ATINN IN (ZZDERIVATIVEMS, ZZPOSITIONMS, ZZDERIVATIVESS, ZZPOSITIONSS, ZZCRITERIA, ZZWIDTH).

    LOOP AT IT_BATCH_SR.
      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZDERIVATIVESS.
      IF SY-SUBRC EQ 0.
        T_SR-DERIVATIVE_SS = IT_CHAR-ATWRT.
      ENDIF.

      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZDERIVATIVEMS.
      IF SY-SUBRC EQ 0.
        T_SR-DERIVATIVE = IT_CHAR-ATWRT.
      ENDIF.

      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZPOSITIONSS.
      IF SY-SUBRC EQ 0.
        T_SR-POSITION_SS = IT_CHAR-ATWRT.
      ENDIF.

      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZPOSITIONMS.
      IF SY-SUBRC EQ 0.
        T_SR-POSITION = IT_CHAR-ATWRT.
      ENDIF.

      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZCRITERIA.
      IF SY-SUBRC EQ 0.
        T_SR-GRADE = IT_CHAR-ATWRT.
      ENDIF.

      READ TABLE IT_CHAR WITH KEY CHARG = IT_BATCH_SR-CHARG ATINN = ZZWIDTH.
      IF SY-SUBRC EQ 0.
        T_SR-WIDTH = IT_CHAR-ATFLV.
      ENDIF.

      T_SR-CHARGJR  = CHARGJR.
      T_SR-CHARG    = IT_BATCH_SR-CHARG.
      T_SR-MATNR    = IT_BATCH_SR-MATNR.
      T_SR-WERKS    = IT_BATCH_SR-WERKS.
      T_SR-BUDAT    = IT_BATCH_SR-BUDAT_MKPF.

      SELECT SINGLE ABLAD INTO T_SR-ABLAD FROM AFPO WHERE AUFNR EQ IT_AFPO-AUFNR.

      APPEND T_SR.
    ENDLOOP.
  ENDLOOP.

  DELETE ADJACENT DUPLICATES FROM T_SR.
  IF DERIVATIVE IS NOT INITIAL.
    DELETE T_SR WHERE DERIVATIVE <> DERIVATIVE.
  ENDIF.
  IF POSITION IS NOT INITIAL.
    DELETE T_SR WHERE POSITION <> POSITION.
  ENDIF.

  REFRESH: T_SR_SS, IT_BATCH_CG.
  CLEAR: T_SR_SS, IT_BATCH_CG.

  IF T_SR[] IS NOT INITIAL.
    SELECT MATNR CHARG WERKS NCHARG NOROLL2 GRADE2 DCRITB NWEIGHT
        INTO CORRESPONDING FIELDS OF TABLE IT_BATCH_CG
        FROM ZBATCHISTORY
         FOR ALL ENTRIES IN T_SR
       WHERE CHARG = T_SR-CHARG.

    DELETE IT_BATCH_CG WHERE NCHARG IS INITIAL.
    SORT IT_BATCH_CG BY BUDAT DESCENDING UZEIT DESCENDING.
  ENDIF.

 LOOP AT T_SR.
    READ TABLE IT_BATCH_CG WITH KEY CHARG = T_SR-CHARG.
    IF SY-SUBRC EQ 0.
      CALL FUNCTION 'ZQM_GET_BATCH_SR_BY_JR'
        EXPORTING
          CHARGJR = IT_BATCH_CG-NCHARG
        TABLES
          T_SR    = T_SR_SS
          T_CABN  = T_CABN.
    ELSE.
      CALL FUNCTION 'ZQM_GET_BATCH_SR_BY_JR'
        EXPORTING
          CHARGJR = T_SR-CHARG
        TABLES
          T_SR    = T_SR_SS
          T_CABN  = T_CABN.
    ENDIF.
  ENDLOOP.

  APPEND LINES OF T_SR_SS TO T_SR.

  READ TABLE T_SR WITH KEY ABLAD = 'SS'.
  IF SY-SUBRC EQ 0.
    READ TABLE T_SR WITH KEY ABLAD = 'MS'.
    IF SY-SUBRC EQ 0.
      MODIFY T_SR TRANSPORTING CHARGJR WHERE ABLAD EQ 'SS'.
    ENDIF.
  ENDIF.
ENDFUNCTION.

*&---------------------------------------------------------------------*
*&      Form  GET_DETAIL_CHARACTERISTIC
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->MATNR      text
*      -->CHARG      text
*      -->ATNAM      text
*      -->VALUE      text
*----------------------------------------------------------------------*
FORM GET_DETAIL_CHARACTERISTIC USING MATNR CHARG ATINN CHANGING VALUE.
  DATA: V_ATWRT TYPE ATWRT,
        V_ATFLV TYPE ATFLV.

  SELECT SINGLE ATWRT ATFLV INTO (V_ATWRT, V_ATFLV)
    FROM MCH1
    JOIN AUSP ON AUSP~OBJEK EQ MCH1~CUOBJ_BM
   WHERE MATNR EQ MATNR
     AND CHARG EQ CHARG
     AND ATINN EQ ATINN.

  IF V_ATFLV IS NOT INITIAL.
    VALUE = V_ATFLV.
  ELSE.
    VALUE = V_ATWRT.
  ENDIF.
ENDFORM.                    "GET_DETAIL_CHARACTERISTIC