*&---------------------------------------------------------------------*
*& Report  ZPPR_PLANNING_SLITROLL
*&---------------------------------------------------------------------*
*& Hasil planning Slit Roll: batch -> original order -> combine order
*&---------------------------------------------------------------------*
REPORT ZPPR_PLANNING_SLITROLL.

TYPE-POOLS: SLIS.

TABLES: AUFK, AFPO, MCH1.

TYPES: BEGIN OF TY_MAP,
         AUART TYPE AUART,
         GRUP  TYPE C LENGTH 15,
       END OF TY_MAP.

TYPES: BEGIN OF TY_CABN,
         ATNAM TYPE CABN-ATNAM,
         ATINN TYPE CABN-ATINN,
         ANZDZ TYPE CABN-ANZDZ,
       END OF TY_CABN.

TYPES: BEGIN OF TY_CHAR,
         OBJEK TYPE AUSP-OBJEK,
         ATINN TYPE AUSP-ATINN,
         ATWRT TYPE AUSP-ATWRT,
         ATFLV TYPE AUSP-ATFLV,
       END OF TY_CHAR.

TYPES: BEGIN OF TY_OBJECT,
         OBJEK TYPE AUSP-OBJEK,
       END OF TY_OBJECT.

TYPES: BEGIN OF TY_DATA,
         ERDAT_ORI  TYPE AUFK-ERDAT,
         AUFNR_ORI  TYPE AUFK-AUFNR,
         AUART_ORI  TYPE AUFK-AUART,
         MATNR_ORI  TYPE AFPO-MATNR,
         WERKS      TYPE AUFK-WERKS,
         CHARG      TYPE MCH1-CHARG,
         LICHA      TYPE MCH1-LICHA,
         OBJEK      TYPE AUSP-OBJEK,
         AUFNR_COMB TYPE AUFK-AUFNR,
         AUART_COMB TYPE AUFK-AUART,
         ERDAT_COMB TYPE AUFK-ERDAT,
         MATNR_COMB TYPE AFPO-MATNR,
         PLNUM      TYPE AFPO-PLNUM,
         POSNR      TYPE AFPO-POSNR,
         PSMNG      TYPE AFPO-PSMNG,
         WEMNG      TYPE AFPO-WEMNG,
         MEINS      TYPE AFPO-MEINS,
         GSTRP      TYPE AFKO-GSTRP,
         GLTRP      TYPE AFKO-GLTRP,
         GLUZP      TYPE AFKO-GLUZP,
         VERID      TYPE AFPO-VERID,
         LGORT      TYPE AFPO-LGORT,
         ABLAD      TYPE AFPO-ABLAD,
         KDAUF      TYPE AUFK-KDAUF,
         KDPOS      TYPE AUFK-KDPOS,
         MILL_SORT  TYPE AFPO-MILL_OC_SORT,
         ZZCODE     TYPE C LENGTH 40,
         ZZTREAT    TYPE C LENGTH 40,
         ZZCORE     TYPE C LENGTH 40,
         ZZWIDTH    TYPE C LENGTH 40,
         ZZLENGTH   TYPE C LENGTH 40,
         ZZGRADE    TYPE C LENGTH 40,
         ZZDER_MS   TYPE C LENGTH 40,
         ZZDER_SS   TYPE C LENGTH 40,
         ZZPOS_MS   TYPE C LENGTH 40,
         ZZPOS_SS   TYPE C LENGTH 40,
         ZZPACKING  TYPE C LENGTH 40,
         ZZLABEL    TYPE C LENGTH 40,
         ZZPACKCODE TYPE C LENGTH 40,
         ZZEXLENGTH TYPE C LENGTH 40,
         ZZPRODLINE TYPE C LENGTH 40,
         ZZNOLOT    TYPE C LENGTH 40,
         ZZNOROLL   TYPE C LENGTH 40,
         ZZALIAS    TYPE C LENGTH 40,
         ZZCOMBNO   TYPE C LENGTH 40,
       END OF TY_DATA.

DATA: GT_DATA     TYPE STANDARD TABLE OF TY_DATA,
      GS_DATA     TYPE TY_DATA,
      GT_MAP      TYPE STANDARD TABLE OF TY_MAP,
      GS_MAP      TYPE TY_MAP,
      GT_CABN     TYPE STANDARD TABLE OF TY_CABN,
      GS_CABN     TYPE TY_CABN,
      GT_CHAR     TYPE STANDARD TABLE OF TY_CHAR,
      GS_CHAR     TYPE TY_CHAR,
      GT_OBJECT   TYPE STANDARD TABLE OF TY_OBJECT,
      GS_OBJECT   TYPE TY_OBJECT,
      GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
      GS_LAYOUT   TYPE SLIS_LAYOUT_ALV,
      GS_VARIANT  TYPE DISVARIANT,
      GV_REPID    TYPE SY-REPID.

DATA: GV_ZZCODE     TYPE ATINN,
      GV_ZZTREAT    TYPE ATINN,
      GV_ZZCORE     TYPE ATINN,
      GV_ZZWIDTH    TYPE ATINN,
      GV_ZZLENGTH   TYPE ATINN,
      GV_ZZLENGTHSH TYPE ATINN,
      GV_ZZGRADE    TYPE ATINN,
      GV_ZZDER_MS   TYPE ATINN,
      GV_ZZDER_SS   TYPE ATINN,
      GV_ZZPOS_MS   TYPE ATINN,
      GV_ZZPOS_SS   TYPE ATINN,
      GV_ZZPACKING  TYPE ATINN,
      GV_ZZLABEL    TYPE ATINN,
      GV_ZZPACKCODE TYPE ATINN,
      GV_ZZEXLENGTH TYPE ATINN,
      GV_ZZPRODLINE TYPE ATINN,
      GV_ZZNOLOT    TYPE ATINN,
      GV_ZZNOROLL   TYPE ATINN,
      GV_ZZALIAS    TYPE ATINN,
      GV_ZZCOMBNO   TYPE ATINN.

RANGES: GR_AUART_ORI  FOR AUFK-AUART,
        GR_AUART_COMB FOR AUFK-AUART,
        GR_ATINN      FOR CABN-ATINN.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_ERDAT FOR AUFK-ERDAT,
                S_COMB  FOR AUFK-AUFNR,
                S_ORI   FOR AUFK-AUFNR,
                S_WERKS FOR AUFK-WERKS,
                S_MATNR FOR AFPO-MATNR,
                S_CHARG FOR MCH1-CHARG.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-005.
PARAMETERS: P_VARI TYPE DISVARIANT-VARIANT.
SELECTION-SCREEN END OF BLOCK B2.

INITIALIZATION.
  GV_REPID = SY-REPID.
  GS_VARIANT-REPORT = SY-REPID.
  PERFORM INIT_LAYOUT.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_VARI.
  PERFORM F4_VARIANT.

AT SELECTION-SCREEN ON P_VARI.
  PERFORM VALIDATE_LAYOUT.

START-OF-SELECTION.
  PERFORM LOAD_ORDER_TYPE_MAP.
  PERFORM LOAD_CHARACTERISTIC_MAP.
  PERFORM GET_DATA.
  PERFORM LOAD_CHARACTERISTICS.

  IF GT_DATA[] IS INITIAL.
    MESSAGE TEXT-002 TYPE 'S' DISPLAY LIKE 'E'.
    RETURN.
  ENDIF.

  PERFORM DISPLAY_ALV.

*&---------------------------------------------------------------------*
*&      Form  LOAD_ORDER_TYPE_MAP
*&---------------------------------------------------------------------*
FORM LOAD_ORDER_TYPE_MAP.
  REFRESH: GT_MAP, GR_AUART_ORI, GR_AUART_COMB.

  SELECT VALUE OPT
    INTO (GS_MAP-AUART, GS_MAP-GRUP)
    FROM ZMAP_TYPE
    WHERE TCODE    = SPACE
      AND PROG     = 'ZPPR_PLANNING_SLITROLL'
      AND TYPE     = 'ORDER TYPE'
      AND DELETION = SPACE.
    APPEND GS_MAP TO GT_MAP.

    IF GS_MAP-GRUP = 'SR ORIGINAL'.
      GR_AUART_ORI-SIGN = 'I'.
      GR_AUART_ORI-OPTION = 'EQ'.
      GR_AUART_ORI-LOW = GS_MAP-AUART.
      APPEND GR_AUART_ORI.
    ELSEIF GS_MAP-GRUP = 'SR COMBINE'.
      GR_AUART_COMB-SIGN = 'I'.
      GR_AUART_COMB-OPTION = 'EQ'.
      GR_AUART_COMB-LOW = GS_MAP-AUART.
      APPEND GR_AUART_COMB.
    ENDIF.
    CLEAR GS_MAP.
  ENDSELECT.

  IF GR_AUART_ORI[] IS INITIAL OR GR_AUART_COMB[] IS INITIAL.
    MESSAGE TEXT-003 TYPE 'S' DISPLAY LIKE 'E'.
    LEAVE LIST-PROCESSING.
  ENDIF.

  SORT GR_AUART_ORI BY LOW.
  DELETE ADJACENT DUPLICATES FROM GR_AUART_ORI COMPARING LOW.
  SORT GR_AUART_COMB BY LOW.
  DELETE ADJACENT DUPLICATES FROM GR_AUART_COMB COMPARING LOW.
ENDFORM.                    " LOAD_ORDER_TYPE_MAP

*&---------------------------------------------------------------------*
*&      Form  GET_DATA
*&---------------------------------------------------------------------*
FORM GET_DATA.
  REFRESH GT_DATA.

  SELECT O~ERDAT
         O~AUFNR
         O~AUART
         OI~MATNR
         O~WERKS
         B~CHARG
         B~LICHA
         B~CUOBJ_BM
         C~AUFNR
         C~AUART
         C~ERDAT
         CI~MATNR
         CI~PLNUM
         CI~POSNR
         CI~PSMNG
         CI~WEMNG
         CI~MEINS
         CK~GSTRP
         CK~GLTRP
         CK~GLUZP
         CI~VERID
         OI~LGORT
         CI~ABLAD
         C~KDAUF
         C~KDPOS
         CI~MILL_OC_SORT
    INTO TABLE GT_DATA
    FROM AUFK AS O
    INNER JOIN AFPO AS OI
      ON OI~AUFNR = O~AUFNR
    INNER JOIN MCH1 AS B
      ON B~MATNR = OI~MATNR
     AND B~LICHA = O~AUFNR
    INNER JOIN AFPO AS CI
      ON CI~MILL_OC_AUFNR_U = O~AUFNR
    INNER JOIN AUFK AS C
      ON C~AUFNR = CI~AUFNR
    INNER JOIN AFKO AS CK
      ON CK~AUFNR = C~AUFNR
    WHERE O~ERDAT IN S_ERDAT
      AND O~AUFNR IN S_ORI
      AND O~AUART IN GR_AUART_ORI
      AND O~WERKS IN S_WERKS
      AND OI~MATNR IN S_MATNR
      AND B~CHARG IN S_CHARG
      AND C~AUFNR IN S_COMB
      AND C~AUART IN GR_AUART_COMB.

  SORT GT_DATA BY ERDAT_ORI AUFNR_ORI AUFNR_COMB CHARG.
  DELETE ADJACENT DUPLICATES FROM GT_DATA
    COMPARING AUFNR_ORI AUFNR_COMB CHARG POSNR.
ENDFORM.                    " GET_DATA

*&---------------------------------------------------------------------*
*&      Form  LOAD_CHARACTERISTIC_MAP
*&---------------------------------------------------------------------*
FORM LOAD_CHARACTERISTIC_MAP.
  REFRESH: GT_CABN, GR_ATINN.

  SELECT ATNAM ATINN ANZDZ INTO TABLE GT_CABN
    FROM CABN
    WHERE ATNAM LIKE 'ZZ%'.

  SORT GT_CABN BY ATNAM.

  PERFORM SET_ATINN USING 'ZZCODE' CHANGING GV_ZZCODE.
  PERFORM SET_ATINN USING 'ZZTREATMENT' CHANGING GV_ZZTREAT.
  PERFORM SET_ATINN USING 'ZZCORE' CHANGING GV_ZZCORE.
  PERFORM SET_ATINN USING 'ZZWIDTH' CHANGING GV_ZZWIDTH.
  PERFORM SET_ATINN USING 'ZZLENGTH' CHANGING GV_ZZLENGTH.
  PERFORM SET_ATINN USING 'ZZLENGTHSHT' CHANGING GV_ZZLENGTHSH.
  PERFORM SET_ATINN USING 'ZZGRADE' CHANGING GV_ZZGRADE.
  PERFORM SET_ATINN USING 'ZZDERIVATIVEMS' CHANGING GV_ZZDER_MS.
  PERFORM SET_ATINN USING 'ZZDERIVATIVESS' CHANGING GV_ZZDER_SS.
  PERFORM SET_ATINN USING 'ZZPOSITIONMS' CHANGING GV_ZZPOS_MS.
  PERFORM SET_ATINN USING 'ZZPOSITIONSS' CHANGING GV_ZZPOS_SS.
  PERFORM SET_ATINN USING 'ZZPACKING' CHANGING GV_ZZPACKING.
  PERFORM SET_ATINN USING 'ZZLABEL' CHANGING GV_ZZLABEL.
  PERFORM SET_ATINN USING 'ZZPACKINGCODE' CHANGING GV_ZZPACKCODE.
  PERFORM SET_ATINN USING 'ZZEXLENGTH' CHANGING GV_ZZEXLENGTH.
  PERFORM SET_ATINN USING 'ZZPRODLINE' CHANGING GV_ZZPRODLINE.
  PERFORM SET_ATINN USING 'ZZNOLOTTOYOBO' CHANGING GV_ZZNOLOT.
  PERFORM SET_ATINN USING 'ZZNOROLLTOYOBO' CHANGING GV_ZZNOROLL.
  PERFORM SET_ATINN USING 'ZZALIAS' CHANGING GV_ZZALIAS.
  PERFORM SET_ATINN USING 'ZZTYBCOMBINATIONNO'
                    CHANGING GV_ZZCOMBNO.

  SORT GR_ATINN BY LOW.
  DELETE ADJACENT DUPLICATES FROM GR_ATINN COMPARING LOW.
ENDFORM.                    " LOAD_CHARACTERISTIC_MAP

*&---------------------------------------------------------------------*
*&      Form  SET_ATINN
*&---------------------------------------------------------------------*
FORM SET_ATINN USING P_ATNAM CHANGING P_ATINN.
  CLEAR P_ATINN.
  READ TABLE GT_CABN INTO GS_CABN
    WITH KEY ATNAM = P_ATNAM BINARY SEARCH.
  IF SY-SUBRC = 0.
    P_ATINN = GS_CABN-ATINN.
    GR_ATINN-SIGN = 'I'.
    GR_ATINN-OPTION = 'EQ'.
    GR_ATINN-LOW = GS_CABN-ATINN.
    APPEND GR_ATINN.
  ENDIF.
ENDFORM.                    " SET_ATINN

*&---------------------------------------------------------------------*
*&      Form  LOAD_CHARACTERISTICS
*&---------------------------------------------------------------------*
FORM LOAD_CHARACTERISTICS.
  REFRESH: GT_OBJECT, GT_CHAR.

  LOOP AT GT_DATA INTO GS_DATA.
    CLEAR GS_OBJECT.
    GS_OBJECT-OBJEK = GS_DATA-OBJEK.
    APPEND GS_OBJECT TO GT_OBJECT.
  ENDLOOP.

  SORT GT_OBJECT BY OBJEK.
  DELETE ADJACENT DUPLICATES FROM GT_OBJECT COMPARING OBJEK.

  IF GT_OBJECT[] IS NOT INITIAL AND GR_ATINN[] IS NOT INITIAL.
    SELECT OBJEK ATINN ATWRT ATFLV
      INTO TABLE GT_CHAR
      FROM AUSP
      FOR ALL ENTRIES IN GT_OBJECT
      WHERE OBJEK = GT_OBJECT-OBJEK
        AND KLART = '023'
        AND ATINN IN GR_ATINN.
  ENDIF.

  SORT GT_CHAR BY OBJEK ATINN.

  LOOP AT GT_DATA INTO GS_DATA.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZCODE
                           CHANGING GS_DATA-ZZCODE.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZTREAT
                           CHANGING GS_DATA-ZZTREAT.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZCORE
                           CHANGING GS_DATA-ZZCORE.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZWIDTH
                           CHANGING GS_DATA-ZZWIDTH.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZLENGTH
                           CHANGING GS_DATA-ZZLENGTH.
    IF GS_DATA-ZZLENGTH IS INITIAL.
      PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZLENGTHSH
                             CHANGING GS_DATA-ZZLENGTH.
    ENDIF.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZGRADE
                           CHANGING GS_DATA-ZZGRADE.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZDER_MS
                           CHANGING GS_DATA-ZZDER_MS.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZDER_SS
                           CHANGING GS_DATA-ZZDER_SS.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZPOS_MS
                           CHANGING GS_DATA-ZZPOS_MS.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZPOS_SS
                           CHANGING GS_DATA-ZZPOS_SS.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZPACKING
                           CHANGING GS_DATA-ZZPACKING.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZLABEL
                           CHANGING GS_DATA-ZZLABEL.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZPACKCODE
                           CHANGING GS_DATA-ZZPACKCODE.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZEXLENGTH
                           CHANGING GS_DATA-ZZEXLENGTH.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZPRODLINE
                           CHANGING GS_DATA-ZZPRODLINE.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZNOLOT
                           CHANGING GS_DATA-ZZNOLOT.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZNOROLL
                           CHANGING GS_DATA-ZZNOROLL.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZALIAS
                           CHANGING GS_DATA-ZZALIAS.
    PERFORM GET_CHAR_VALUE USING GS_DATA-OBJEK GV_ZZCOMBNO
                           CHANGING GS_DATA-ZZCOMBNO.
    MODIFY GT_DATA FROM GS_DATA.
  ENDLOOP.
ENDFORM.                    " LOAD_CHARACTERISTICS

*&---------------------------------------------------------------------*
*&      Form  GET_CHAR_VALUE
*&---------------------------------------------------------------------*
FORM GET_CHAR_VALUE USING P_OBJEK P_ATINN CHANGING P_VALUE.
  DATA: LV_ATFLV TYPE P LENGTH 16 DECIMALS 7.

  CLEAR P_VALUE.
  IF P_ATINN IS INITIAL.
    RETURN.
  ENDIF.

  READ TABLE GT_CHAR INTO GS_CHAR
    WITH KEY OBJEK = P_OBJEK ATINN = P_ATINN BINARY SEARCH.
  IF SY-SUBRC = 0.
    IF GS_CHAR-ATWRT IS NOT INITIAL.
      P_VALUE = GS_CHAR-ATWRT.
    ELSEIF GS_CHAR-ATFLV IS NOT INITIAL.
      LV_ATFLV = GS_CHAR-ATFLV.
      READ TABLE GT_CABN INTO GS_CABN
        WITH KEY ATINN = P_ATINN.
      WRITE LV_ATFLV TO P_VALUE
        DECIMALS GS_CABN-ANZDZ NO-GROUPING.
      CONDENSE P_VALUE.
    ENDIF.
  ENDIF.
ENDFORM.                    " GET_CHAR_VALUE

*&---------------------------------------------------------------------*
*&      Form  ADD_FIELDCAT
*&---------------------------------------------------------------------*
FORM ADD_FIELDCAT USING P_FIELD P_TEXT P_LEN P_KEY P_QFIELD.
  CLEAR GS_FIELDCAT.
  GS_FIELDCAT-FIELDNAME = P_FIELD.
  GS_FIELDCAT-SELTEXT_L = P_TEXT.
  GS_FIELDCAT-SELTEXT_M = P_TEXT.
  GS_FIELDCAT-SELTEXT_S = P_TEXT.
  GS_FIELDCAT-OUTPUTLEN = P_LEN.
  GS_FIELDCAT-KEY = P_KEY.
  GS_FIELDCAT-QFIELDNAME = P_QFIELD.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.
ENDFORM.                    " ADD_FIELDCAT

*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCAT
*&---------------------------------------------------------------------*
FORM BUILD_FIELDCAT.
  REFRESH GT_FIELDCAT.

  PERFORM ADD_FIELDCAT USING:
    'ERDAT_ORI'  'Order Created On' 10 'X' '',
    'AUFNR_ORI'  'Original Order'   12 'X' '',
    'AUART_ORI'  'Original Type'     8 ''  '',
    'MATNR_ORI'  'Original Material' 18 '' '',
    'WERKS'      'Plant'             6 ''  '',
    'CHARG'      'Batch'            10 ''  '',
    'LICHA'      'Vendor Batch'     15 ''  '',
    'AUFNR_COMB' 'Combine Order'    12 'X' '',
    'AUART_COMB' 'Combine Type'      8 ''  '',
    'ERDAT_COMB' 'Combine Created'  10 ''  '',
    'MATNR_COMB' 'Combine Material' 18 ''  '',
    'PLNUM'      'Planned Order'    10 ''  '',
    'POSNR'      'Item'              6 ''  '',
    'PSMNG'      'Planned Qty'      15 ''  'MEINS',
    'WEMNG'      'GR Qty'           15 ''  'MEINS',
    'MEINS'      'UoM'               5 ''  '',
    'GSTRP'      'Basic Start'      10 ''  '',
    'GLTRP'      'Basic Finish'     10 ''  '',
    'GLUZP'      'Finish Time'       8 ''  '',
    'VERID'      'Prod. Version'     8 ''  '',
    'LGORT'      'Storage Loc.'      8 ''  '',
    'ABLAD'      'Unloading Point'  20 ''  '',
    'KDAUF'      'Sales Order'      12 ''  '',
    'KDPOS'      'SO Item'           6 ''  '',
    'MILL_SORT'  'Sequence'          8 ''  '',
    'ZZCODE'     'Film Code'        12 ''  '',
    'ZZTREAT'    'Treatment'        12 ''  '',
    'ZZCORE'     'Core'             10 ''  '',
    'ZZWIDTH'    'Width'            12 ''  '',
    'ZZLENGTH'   'Length'           12 ''  '',
    'ZZGRADE'    'Grade'            10 ''  '',
    'ZZDER_MS'   'Main Derivative'  15 ''  '',
    'ZZDER_SS'   'Sub Derivative'   15 ''  '',
    'ZZPOS_MS'   'Main Position'    15 ''  '',
    'ZZPOS_SS'   'Sub Position'     15 ''  '',
    'ZZPACKING'  'Packing'          12 ''  '',
    'ZZLABEL'    'Label Type'       12 ''  '',
    'ZZPACKCODE' 'Packing Code'     20 ''  '',
    'ZZEXLENGTH' 'Extra Length'     12 ''  '',
    'ZZPRODLINE' 'Production Line'  15 ''  '',
    'ZZNOLOT'    'Toyobo Lot No.'   18 ''  '',
    'ZZNOROLL'   'Toyobo Roll No.'  18 ''  '',
    'ZZALIAS'    'Alias'            20 ''  '',
    'ZZCOMBNO'   'Combination No.'  20 ''  ''.
ENDFORM.                    " BUILD_FIELDCAT

*&---------------------------------------------------------------------*
*&      Form  DISPLAY_ALV
*&---------------------------------------------------------------------*
FORM DISPLAY_ALV.
  PERFORM BUILD_FIELDCAT.

  CLEAR GS_LAYOUT.
  GS_LAYOUT-ZEBRA = 'X'.
  GS_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  GS_VARIANT-REPORT = SY-REPID.
  GS_VARIANT-VARIANT = P_VARI.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM = GV_REPID
      IS_LAYOUT          = GS_LAYOUT
      IT_FIELDCAT        = GT_FIELDCAT
      I_DEFAULT          = 'X'
      I_SAVE             = 'A'
      IS_VARIANT         = GS_VARIANT
    TABLES
      T_OUTTAB           = GT_DATA
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.

  IF SY-SUBRC <> 0.
    MESSAGE TEXT-004 TYPE 'S' DISPLAY LIKE 'E'.
  ENDIF.
ENDFORM.                    " DISPLAY_ALV

*&---------------------------------------------------------------------*
*&      Form  F4_VARIANT
*&---------------------------------------------------------------------*
FORM F4_VARIANT.
  DATA: LS_VARIANT TYPE DISVARIANT,
        LV_EXIT    TYPE CHAR1.

  LS_VARIANT-REPORT = SY-REPID.
  CALL FUNCTION 'REUSE_ALV_VARIANT_F4'
    EXPORTING
      IS_VARIANT = LS_VARIANT
      I_SAVE     = 'A'
    IMPORTING
      E_EXIT     = LV_EXIT
      ES_VARIANT = LS_VARIANT
    EXCEPTIONS
      NOT_FOUND  = 1
      OTHERS     = 2.

  IF SY-SUBRC = 0 AND LV_EXIT IS INITIAL.
    P_VARI = LS_VARIANT-VARIANT.
  ENDIF.
ENDFORM.                    " F4_VARIANT

*&---------------------------------------------------------------------*
*&      Form  INIT_LAYOUT
*&---------------------------------------------------------------------*
FORM INIT_LAYOUT.
  DATA: LS_VARIANT TYPE DISVARIANT.

  CLEAR LS_VARIANT.
  LS_VARIANT-REPORT = SY-REPID.

  CALL FUNCTION 'REUSE_ALV_VARIANT_DEFAULT_GET'
    EXPORTING
      I_SAVE     = 'A'
    CHANGING
      CS_VARIANT = LS_VARIANT
    EXCEPTIONS
      OTHERS     = 1.

  IF SY-SUBRC = 0 AND LS_VARIANT-VARIANT IS NOT INITIAL.
    P_VARI = LS_VARIANT-VARIANT.
  ELSE.
    CLEAR P_VARI.
    SELECT VARIANT FROM LTDX INTO P_VARI UP TO 1 ROWS
      WHERE REPORT = SY-REPID
        AND ( USERNAME = SY-UNAME OR USERNAME = SPACE )
      ORDER BY USERNAME DESCENDING VARIANT ASCENDING.
    ENDSELECT.
  ENDIF.
ENDFORM.                    " INIT_LAYOUT

*&---------------------------------------------------------------------*
*&      Form  VALIDATE_LAYOUT
*&---------------------------------------------------------------------*
FORM VALIDATE_LAYOUT.
  DATA: LS_VARIANT TYPE DISVARIANT.

  IF P_VARI IS NOT INITIAL.
    CLEAR LS_VARIANT.
    LS_VARIANT-REPORT = SY-REPID.
    LS_VARIANT-VARIANT = P_VARI.

    CALL FUNCTION 'REUSE_ALV_VARIANT_EXISTENCE'
      EXPORTING
        I_SAVE     = 'A'
      CHANGING
        CS_VARIANT = LS_VARIANT
      EXCEPTIONS
        OTHERS     = 1.

    IF SY-SUBRC <> 0.
      MESSAGE E000(0K) WITH 'Layout not found'.
    ENDIF.
  ENDIF.
ENDFORM.                    " VALIDATE_LAYOUT
