FUNCTION ZPP_MD_DL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(MODE) TYPE  CHAR10
*"     VALUE(MAT_GROUP) TYPE  CHAR120 OPTIONAL
*"  TABLES
*"      MAST STRUCTURE  MAST
*"      STKO STRUCTURE  STKO
*"      STPO STRUCTURE  STPO
*"      STAS STRUCTURE  STAS
*"  EXCEPTIONS
*"      MODE_IS_NOT_AVAILABLE
*"      PAR_MAT_GROUP_IS_NULL
*"      DATA_NOT_FOUND
*"----------------------------------------------------------------------

  DATA: V1(10).
  RANGES: P_MATKL FOR MARA-MATKL.

  IF MAT_GROUP IS NOT INITIAL.
    CLEAR V1.
    P_MATKL-SIGN = 'I'.
    P_MATKL-OPTION = 'EQ'.
    WHILE MAT_GROUP NE ''.
      SPLIT MAT_GROUP AT ',' INTO V1 MAT_GROUP.
      P_MATKL-LOW = V1.
      APPEND P_MATKL.
    ENDWHILE.
    DELETE P_MATKL WHERE LOW = ''.
  ENDIF.

  CASE MODE.
    WHEN 'MAST'.
      DATA: I_MAST LIKE MAST OCCURS 0.
      PERFORM GET_MAST USING P_MATKL[] CHANGING I_MAST.
      MAST[] = I_MAST[].
      CLEAR: I_MAST[].
      REFRESH: I_MAST[].

    WHEN 'STKO'.
      DATA: I_STKO LIKE STKO OCCURS 0.
      PERFORM GET_STKO_ONLY USING P_MATKL[] CHANGING I_STKO.
      STKO[] = I_STKO[].
      CLEAR: I_STKO[].
      REFRESH: I_STKO[].

    WHEN 'STPO'.
      DATA: I_STPO LIKE STPO OCCURS 0.
      PERFORM GET_STPO_ONLY USING P_MATKL[] CHANGING I_STPO.
      STPO[] = I_STPO[].
      CLEAR: I_STPO[].
      REFRESH: I_STPO[].

    WHEN 'STAS'.
      DATA: I_STAS LIKE STAS OCCURS 0.
      PERFORM GET_STAS_ONLY USING P_MATKL[] CHANGING I_STAS.
      STAS[] = I_STAS[].
      CLEAR: I_STAS[].
      REFRESH: I_STAS[].

    WHEN 'ALL'.
      DATA: I_MAST_ALL LIKE MAST OCCURS 0,
            I_STKO_ALL LIKE STKO OCCURS 0,
            I_STPO_ALL LIKE STPO OCCURS 0,
            I_STAS_ALL LIKE STAS OCCURS 0.
      PERFORM GET_ALL_BOM USING P_MATKL[]
                          CHANGING I_MAST_ALL I_STKO_ALL I_STPO_ALL I_STAS_ALL.
      MAST[] = I_MAST_ALL[].
      STKO[] = I_STKO_ALL[].
      STPO[] = I_STPO_ALL[].
      STAS[] = I_STAS_ALL[].
      CLEAR: I_MAST_ALL[], I_STKO_ALL[], I_STPO_ALL[], I_STAS_ALL[].
      REFRESH: I_MAST_ALL[], I_STKO_ALL[], I_STPO_ALL[], I_STAS_ALL[].

    WHEN OTHERS.
      MESSAGE 'Mode Is Not Available' TYPE 'S' RAISING MODE_IS_NOT_AVAILABLE.
  ENDCASE.

ENDFUNCTION.

*======================================================================*
* SUBROUTINE DEFINITIONS (FORM)
*======================================================================*

DATA: T_MAST LIKE STANDARD TABLE OF MAST,
      T_STKO LIKE STANDARD TABLE OF STKO,
      T_STPO LIKE STANDARD TABLE OF STPO,
      T_STAS LIKE STANDARD TABLE OF STAS.

*----------------------------------------------------------------------*
* FORM: GET_MAST (Mode MAST)
*----------------------------------------------------------------------*
FORM GET_MAST USING VALUE(P_MATKL) TYPE STANDARD TABLE
              CHANGING W_MAST LIKE T_MAST.

  DATA: IT_MAST LIKE MAST OCCURS 0 WITH HEADER LINE,
        BEGIN OF IT_MATNR OCCURS 0,
          MATNR TYPE MARA-MATNR,
        END OF IT_MATNR.

  IF P_MATKL[] IS NOT INITIAL.
    SELECT MATNR FROM MARA INTO TABLE IT_MATNR WHERE MATKL IN P_MATKL.
    IF IT_MATNR[] IS NOT INITIAL.
      SELECT * FROM MAST INTO TABLE IT_MAST
        FOR ALL ENTRIES IN IT_MATNR
        WHERE MATNR = IT_MATNR-MATNR.
    ENDIF.
  ELSE.
    SELECT * FROM MAST INTO TABLE IT_MAST.
  ENDIF.

  IF IT_MAST[] IS NOT INITIAL.
    IT_MAST-ANDAT = '19000101'.
    IT_MAST-AEDAT = '19000101'.
    MODIFY IT_MAST TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_MAST TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    W_MAST[] = IT_MAST[].
    CLEAR: IT_MAST[].
    REFRESH: IT_MAST[].
  ELSE.
    MESSAGE 'Data Not Found' TYPE 'S' RAISING DATA_NOT_FOUND.
  ENDIF.

ENDFORM.

*----------------------------------------------------------------------*
* FORM: GET_STKO_ONLY (Mode STKO)
*----------------------------------------------------------------------*
FORM GET_STKO_ONLY USING VALUE(P_MATKL) TYPE STANDARD TABLE
                   CHANGING W_STKO LIKE T_STKO.

  DATA: IT_STKO LIKE STKO OCCURS 0 WITH HEADER LINE,
        IT_MAST_TEMP LIKE MAST OCCURS 0 WITH HEADER LINE,
        BEGIN OF IT_MATNR OCCURS 0,
          MATNR TYPE MARA-MATNR,
        END OF IT_MATNR.

  IF P_MATKL[] IS NOT INITIAL.
    SELECT MATNR FROM MARA INTO TABLE IT_MATNR WHERE MATKL IN P_MATKL.
    IF IT_MATNR[] IS NOT INITIAL.
      SELECT MANDT MATNR WERKS STLAN STLNR STLAL
        FROM MAST INTO CORRESPONDING FIELDS OF TABLE IT_MAST_TEMP
        FOR ALL ENTRIES IN IT_MATNR
        WHERE MATNR = IT_MATNR-MATNR.

      IF IT_MAST_TEMP[] IS NOT INITIAL.
        SELECT * FROM STKO INTO TABLE IT_STKO
          FOR ALL ENTRIES IN IT_MAST_TEMP
          WHERE STLNR = IT_MAST_TEMP-STLNR.
      ENDIF.
    ENDIF.
  ELSE.
    SELECT * FROM STKO INTO TABLE IT_STKO.
  ENDIF.

  IF IT_STKO[] IS NOT INITIAL.
    IT_STKO-DATUV = '19000101'.
    IT_STKO-ANDAT = '19000101'.
    IT_STKO-AEDAT = '19000101'.
    IT_STKO-DVDAT = '19000101'.
    MODIFY IT_STKO TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STKO TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STKO TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STKO TRANSPORTING DVDAT WHERE DVDAT = 00000000.
    W_STKO[] = IT_STKO[].
    CLEAR: IT_STKO[].
    REFRESH: IT_STKO[].
  ELSE.
    MESSAGE 'Data Not Found' TYPE 'S' RAISING DATA_NOT_FOUND.
  ENDIF.

ENDFORM.

*----------------------------------------------------------------------*
* FORM: GET_STPO_ONLY (Mode STPO)
*----------------------------------------------------------------------*
FORM GET_STPO_ONLY USING VALUE(P_MATKL) TYPE STANDARD TABLE
                   CHANGING W_STPO LIKE T_STPO.

  DATA: IT_STPO LIKE STPO OCCURS 0 WITH HEADER LINE,
        IT_MAST_TEMP LIKE MAST OCCURS 0 WITH HEADER LINE,
        BEGIN OF IT_MATNR OCCURS 0,
          MATNR TYPE MARA-MATNR,
        END OF IT_MATNR.

  IF P_MATKL[] IS NOT INITIAL.
    SELECT MATNR FROM MARA INTO TABLE IT_MATNR WHERE MATKL IN P_MATKL.
    IF IT_MATNR[] IS NOT INITIAL.
      SELECT MANDT MATNR WERKS STLAN STLNR STLAL
        FROM MAST INTO CORRESPONDING FIELDS OF TABLE IT_MAST_TEMP
        FOR ALL ENTRIES IN IT_MATNR
        WHERE MATNR = IT_MATNR-MATNR.

      IF IT_MAST_TEMP[] IS NOT INITIAL.
        SELECT * FROM STPO INTO TABLE IT_STPO
          FOR ALL ENTRIES IN IT_MAST_TEMP
          WHERE STLNR = IT_MAST_TEMP-STLNR.
      ENDIF.
    ENDIF.
  ELSE.
    SELECT * FROM STPO INTO TABLE IT_STPO.
  ENDIF.

  IF IT_STPO[] IS NOT INITIAL.
    IT_STPO-DATUV = '19000101'.
    IT_STPO-ANDAT = '19000101'.
    IT_STPO-AEDAT = '19000101'.
    IT_STPO-DVDAT = '19000101'.
    MODIFY IT_STPO TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STPO TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STPO TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STPO TRANSPORTING DVDAT WHERE DVDAT = 00000000.
    W_STPO[] = IT_STPO[].
    CLEAR: IT_STPO[].
    REFRESH: IT_STPO[].
  ELSE.
    MESSAGE 'Data Not Found' TYPE 'S' RAISING DATA_NOT_FOUND.
  ENDIF.

ENDFORM.

*----------------------------------------------------------------------*
* FORM: GET_STAS_ONLY (Mode STAS)
*----------------------------------------------------------------------*
FORM GET_STAS_ONLY USING VALUE(P_MATKL) TYPE STANDARD TABLE
                   CHANGING W_STAS LIKE T_STAS.

  DATA: IT_STAS LIKE STAS OCCURS 0 WITH HEADER LINE,
        IT_MAST_TEMP LIKE MAST OCCURS 0 WITH HEADER LINE,
        BEGIN OF IT_MATNR OCCURS 0,
          MATNR TYPE MARA-MATNR,
        END OF IT_MATNR.

  IF P_MATKL[] IS NOT INITIAL.
    SELECT MATNR FROM MARA INTO TABLE IT_MATNR WHERE MATKL IN P_MATKL.
    IF IT_MATNR[] IS NOT INITIAL.
      SELECT MANDT MATNR WERKS STLAN STLNR STLAL
        FROM MAST INTO CORRESPONDING FIELDS OF TABLE IT_MAST_TEMP
        FOR ALL ENTRIES IN IT_MATNR
        WHERE MATNR = IT_MATNR-MATNR.

      IF IT_MAST_TEMP[] IS NOT INITIAL.
        SELECT * FROM STAS INTO TABLE IT_STAS
          FOR ALL ENTRIES IN IT_MAST_TEMP
          WHERE STLNR = IT_MAST_TEMP-STLNR.
      ENDIF.
    ENDIF.
  ELSE.
    SELECT * FROM STAS INTO TABLE IT_STAS.
  ENDIF.

  IF IT_STAS[] IS NOT INITIAL.
    IT_STAS-DATUV = '19000101'.
    IT_STAS-ANDAT = '19000101'.
    IT_STAS-AEDAT = '19000101'.
    IT_STAS-DVDAT = '19000101'.
    MODIFY IT_STAS TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STAS TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STAS TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STAS TRANSPORTING DVDAT WHERE DVDAT = 00000000.
    W_STAS[] = IT_STAS[].
    CLEAR: IT_STAS[].
    REFRESH: IT_STAS[].
  ELSE.
    MESSAGE 'Data Not Found' TYPE 'S' RAISING DATA_NOT_FOUND.
  ENDIF.

ENDFORM.

*----------------------------------------------------------------------*
* FORM: GET_ALL_BOM (Mode ALL)
*----------------------------------------------------------------------*
FORM GET_ALL_BOM USING VALUE(P_MATKL) TYPE STANDARD TABLE
                 CHANGING W_MAST LIKE T_MAST
                          W_STKO LIKE T_STKO
                          W_STPO LIKE T_STPO
                          W_STAS LIKE T_STAS.

  DATA: IT_MAST LIKE MAST OCCURS 0 WITH HEADER LINE,
        IT_STKO LIKE STKO OCCURS 0 WITH HEADER LINE,
        IT_STPO LIKE STPO OCCURS 0 WITH HEADER LINE,
        IT_STAS LIKE STAS OCCURS 0 WITH HEADER LINE,
        BEGIN OF IT_MATNR OCCURS 0,
          MATNR TYPE MARA-MATNR,
        END OF IT_MATNR.

  IF P_MATKL[] IS NOT INITIAL.
    SELECT MATNR FROM MARA INTO TABLE IT_MATNR WHERE MATKL IN P_MATKL.
    IF IT_MATNR[] IS NOT INITIAL.
      SELECT * FROM MAST INTO TABLE IT_MAST
        FOR ALL ENTRIES IN IT_MATNR
        WHERE MATNR = IT_MATNR-MATNR.

      IF IT_MAST[] IS NOT INITIAL.
        SELECT * FROM STKO INTO TABLE IT_STKO
          FOR ALL ENTRIES IN IT_MAST
          WHERE STLNR = IT_MAST-STLNR.

        IF IT_STKO[] IS NOT INITIAL.
          SELECT * FROM STPO INTO TABLE IT_STPO
            FOR ALL ENTRIES IN IT_STKO
            WHERE STLTY = IT_STKO-STLTY AND
                  STLNR = IT_STKO-STLNR.

          IF IT_STPO[] IS NOT INITIAL.
            SELECT * FROM STAS INTO TABLE IT_STAS
              FOR ALL ENTRIES IN IT_STPO
              WHERE STLTY = IT_STPO-STLTY AND
                    STLNR = IT_STPO-STLNR.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.
  ELSE.
    SELECT * FROM MAST INTO TABLE IT_MAST.
    SELECT * FROM STKO INTO TABLE IT_STKO.
    SELECT * FROM STPO INTO TABLE IT_STPO.
    SELECT * FROM STAS INTO TABLE IT_STAS.
  ENDIF.

  IF IT_MAST[] IS NOT INITIAL OR IT_STKO[] IS NOT INITIAL OR
     IT_STPO[] IS NOT INITIAL OR IT_STAS[] IS NOT INITIAL.

    IT_MAST-ANDAT = '19000101'.
    IT_MAST-AEDAT = '19000101'.
    MODIFY IT_MAST TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_MAST TRANSPORTING AEDAT WHERE AEDAT = 00000000.

    IT_STKO-DATUV = '19000101'.
    IT_STKO-ANDAT = '19000101'.
    IT_STKO-AEDAT = '19000101'.
    IT_STKO-DVDAT = '19000101'.
    MODIFY IT_STKO TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STKO TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STKO TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STKO TRANSPORTING DVDAT WHERE DVDAT = 00000000.

    IT_STPO-DATUV = '19000101'.
    IT_STPO-ANDAT = '19000101'.
    IT_STPO-AEDAT = '19000101'.
    IT_STPO-DVDAT = '19000101'.
    MODIFY IT_STPO TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STPO TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STPO TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STPO TRANSPORTING DVDAT WHERE DVDAT = 00000000.

    IT_STAS-DATUV = '19000101'.
    IT_STAS-ANDAT = '19000101'.
    IT_STAS-AEDAT = '19000101'.
    IT_STAS-DVDAT = '19000101'.
    MODIFY IT_STAS TRANSPORTING DATUV WHERE DATUV = 00000000.
    MODIFY IT_STAS TRANSPORTING ANDAT WHERE ANDAT = 00000000.
    MODIFY IT_STAS TRANSPORTING AEDAT WHERE AEDAT = 00000000.
    MODIFY IT_STAS TRANSPORTING DVDAT WHERE DVDAT = 00000000.

    W_MAST[] = IT_MAST[].
    W_STKO[] = IT_STKO[].
    W_STPO[] = IT_STPO[].
    W_STAS[] = IT_STAS[].

    CLEAR: IT_MAST[], IT_STKO[], IT_STPO[], IT_STAS[].
    REFRESH: IT_MAST[], IT_STKO[], IT_STPO[], IT_STAS[].
  ELSE.
    MESSAGE 'Data Not Found' TYPE 'S' RAISING DATA_NOT_FOUND.
  ENDIF.

ENDFORM.
