*&---------------------------------------------------------------------*
*&  Include           ZPPR_SLITTING_REKAP_DAILY_TOP
*&---------------------------------------------------------------------*

TABLES: MARA, MCHB, MSEG, CAWN, VBPA.

TYPES : BEGIN OF TYPE_CHAR,
          ATWRT LIKE CAWN-ATWRT,
          ATWTB LIKE CAWNT-ATWTB,
        END OF TYPE_CHAR.

TYPES : BEGIN OF TY_MSEG,
          BOX         TYPE CHAR1,
          MBLNR       LIKE MSEG-MBLNR,
          MJAHR       LIKE MSEG-MJAHR,
          ZEILE       LIKE MSEG-ZEILE,
          SMBLN       LIKE MSEG-SMBLN,
          SMBLP       LIKE MSEG-SMBLP,
          BWART       LIKE MSEG-BWART,
          MATNR       LIKE MARA-MATNR,
          CHARG       LIKE MSEG-CHARG,
          WERKS       LIKE MSEG-WERKS,
          LGORT       LIKE MSEG-LGORT,
          MENGE       LIKE MSEG-MENGE,
          MEINS       LIKE MSEG-MEINS,
          COMB        LIKE AFPO-AUFNR,
          AUFNR       LIKE MSEG-AUFNR,
          AUART       LIKE AUFK-AUART,
          VBELN       LIKE MSEG-KDAUF,
          POSNR       LIKE MSEG-KDPOS,
          ABLAD       LIKE MSEG-ABLAD,
          BUDAT       LIKE MSEG-BUDAT_MKPF,
          CPUTM       LIKE MKPF-CPUTM,
          ARBPL       LIKE CRHD-ARBPL,
          ZZCODE      LIKE CAWN-ATWRT,
          NOROLL      LIKE CAWN-ATWRT,
          WIDTH       LIKE CAWN-ATWRT,
          WIDTH2      TYPE P LENGTH 15,
          LENGTH      LIKE CAWN-ATWRT,
          LENGTH2     TYPE  P LENGTH 15,
          GRADE       LIKE CAWN-ATWRT,
          CRIT        LIKE CAWN-ATWRT,
          LINE        LIKE CAWN-ATWRT,
          LINECD      LIKE CAWN-ATWRT,
          TREAT       LIKE CAWN-ATWRT,
          PCKNG       LIKE CAWN-ATWRT,
          ZCONV       TYPE P DECIMALS 2,
          ZEXTRA      TYPE P DECIMALS 2,
          ZALIAS      TYPE CAWN-ATWRT,
          ZDERMS      LIKE CAWN-ATWRT,
          ZPOSMS      LIKE CAWN-ATWRT,
          ZDERSS      LIKE CAWN-ATWRT,
          ZPOSSS      LIKE CAWN-ATWRT,
          ZMSSS       TYPE CHAR2,
          ZZCORETYPE  TYPE CAWN-ATWRT,    " Added by William at 20.06.2025 (Add ZZCORETYPE)
          CUOBJ_BM    TYPE MCH1-CUOBJ_BM,
          V_LASTGRADE LIKE CAWN-ATWRT,
          V_LASTCRIT  LIKE CAWN-ATWRT,
          V_LASTQTY   TYPE P DECIMALS 3,
          SHKZG       LIKE MSEG-SHKZG,
          XAUTO       LIKE MSEG-XAUTO,
          KDAUF       LIKE MSEG-KDAUF,
          KDPOS       LIKE MSEG-KDPOS,
          KDAUF2      LIKE MSEG-MAT_KDAUF,
          KDPOS2      LIKE MSEG-MAT_KDPOS,
          AUART2      LIKE VBAK-AUART,  "Added by Fany 18.01.2025
          KUNNR       LIKE VBAK-KUNNR,
          NAME1       LIKE KNA1-NAME1,
          ZSPEED      TYPE P LENGTH 15,
          ISM01       LIKE AFRU-ISM01,
          ISDD        LIKE AFRU-ISDD,
          ISDZ        LIKE AFRU-ISDZ,
          IEDD        LIKE AFRU-IEDD,
          IEDZ        LIKE AFRU-IEDZ,
          CX          TYPE CHAR1,
        END OF TY_MSEG.

TYPES : BEGIN OF TY_CRIT,
          LINE   LIKE  CAWN-ATWRT,
          ZZCODE LIKE  CAWN-ATWRT,
          GRADE  LIKE  CAWN-ATWRT,
          MENGE  LIKE  MSEG-MENGE,
          MEINS  LIKE  MSEG-MEINS,
        END OF TY_CRIT.

TYPES : BEGIN OF TY_SHIFT,
          LINE   LIKE  CAWN-ATWRT,
          MATNR  TYPE  CHAR10,
          ZZCODE LIKE  CAWN-ATWRT,
          CRIT   LIKE  CAWN-ATWRT,
          GRADE  LIKE  CAWN-ATWRT,
          LENGTH LIKE  CAWN-ATWRT,
          WIDTH  LIKE  CAWN-ATWRT,
          MENG1  LIKE  MSEG-MENGE,
          ROLL1  TYPE  P,
          MENG2  LIKE  MSEG-MENGE,
          ROLL2  TYPE  P,
          MENG3  LIKE  MSEG-MENGE,
          ROLL3  TYPE  P,
          TOTAL  LIKE  MSEG-MENGE,
          TROLL  TYPE  P,
          ARBPL  LIKE  CRHD-ARBPL,
        END OF TY_SHIFT.

TYPES : BEGIN OF TY_SMBLN,
          MBLNR   TYPE MSEG-MBLNR,
          SMBLN   TYPE MSEG-SMBLN,
        END OF TY_SMBLN.

TYPES : BEGIN OF TY_SALE,
          BOX    TYPE  CHAR1,
          VBELN  LIKE  MSEG-KDAUF,
          POSNR  LIKE  MSEG-KDPOS,
          ZZCODE LIKE  CAWN-ATWRT,
          WIDTH  LIKE  AUSP-ATWRT,
          LENGTH LIKE  AUSP-ATWRT,
          TREAT  LIKE  AUSP-ATWRT,
          KWMENG LIKE  VBAP-KWMENG,
          VRKME  LIKE  VBAP-VRKME,
          ZNAME  LIKE  PA0001-ENAME,
          NAME1  LIKE  KNA1-NAME1,
          NAME2  LIKE  KNA1-NAME2,
          ZCONV  LIKE  MSEG-MENGE,
          PCONV  LIKE  AUSP-ATFLV,
          LINE   LIKE  AUSP-ATWRT,
          END OF TY_SALE.

TYPES : BEGIN OF TY_MSKA,
          MATNR  LIKE  MSEG-MATNR,
          CHARG  LIKE  MSEG-CHARG,
          VBELN  LIKE  MSEG-KDAUF,
          POSNR  LIKE  MSEG-KDPOS,
          WERKS  LIKE  MSKA-WERKS,
          LGORT  LIKE  MSKA-LGORT,
          KALAB  LIKE  MSKA-KALAB,
          KASPE  LIKE  MSKA-KASPE,
        END OF TY_MSKA.

DATA : BEGIN OF TY_STOCK,
        MATNR LIKE MSKU-MATNR,
        WERKS LIKE MSKU-WERKS,
        CHARG LIKE MSKU-CHARG,
        LGORT LIKE MSKA-LGORT,
        LABST TYPE P DECIMALS 3,
        INSME TYPE P DECIMALS 3,
        SPEME TYPE P DECIMALS 3,
        EINME TYPE P DECIMALS 3,
      END OF TY_STOCK.


DATA : BEGIN OF IT_AUART OCCURS 0,
        AUFNR LIKE AUFK-AUFNR,
        AUART LIKE AUFK-AUART,
       END OF IT_AUART.

DATA : BEGIN OF IT_MILLOC OCCURS 0,
        AUFNR LIKE AFPO-AUFNR,
        DAUAT LIKE AFPO-DAUAT,
        AUFNR_U LIKE AFPO-MILL_OC_AUFNR_U,
       END OF IT_MILLOC.

DATA : BEGIN OF IT_AFRU OCCURS 0,
        AUFNR LIKE AFRU-AUFNR,
        ARBID LIKE AFRU-ARBID,
        ISM01 LIKE AFRU-ISM01,
        ISDD LIKE AFRU-ISDD,
        ISDZ LIKE AFRU-ISDZ,
        IEDD LIKE AFRU-IEDD,
        IEDZ LIKE AFRU-IEDZ,
        ARBPL LIKE CRHD-ARBPL,
       END OF IT_AFRU.

DATA : BEGIN OF IT_PRODLINE OCCURS 0,
        ATINN LIKE CAWN-ATINN,
        ATWRT LIKE CAWN-ATWRT,
        ATWTB LIKE CAWNT-ATWTB,
       END OF IT_PRODLINE.

DATA : BEGIN OF IT_SLOCCX OCCURS 0,
         AUFNR LIKE AFRU-AUFNR,
         ZCXLGORT LIKE ZTMAP_SLOCRR-ZCXLGORT,
       END OF IT_SLOCCX.

RANGES: V_AUART FOR AUFK-AUART,
        V_AUARTSL FOR AUFK-AUART,
        V_AUARTTR FOR AUFK-AUART.

DATA: V_ATINN LIKE CAWNT-ATINN,
      V_ATZHL LIKE CAWN-ATZHL,
      RIBUAN  TYPE C,
      PULUHAN TYPE C,
      V_AUFPL LIKE AFKO-AUFPL,
      V_ARBID LIKE AFVC-ARBID,
      V_ROLL1 TYPE I,
      V_ROLL2 TYPE I,
      V_ROLL3 TYPE I,
      V_CUSTNAME TYPE KNA1-NAME1.

DATA: V_LINE   TYPE STANDARD TABLE OF TYPE_CHAR WITH HEADER LINE,
      IT_MSEG  TYPE STANDARD TABLE OF TY_MSEG WITH HEADER LINE,
      IT_MSEG_CX  TYPE STANDARD TABLE OF TY_MSEG WITH HEADER LINE,
      IT_SMBLN TYPE STANDARD TABLE OF TY_SMBLN WITH HEADER LINE,
      IT_MSEG2 TYPE STANDARD TABLE OF TY_MSEG,
      IT_MSEG3 TYPE STANDARD TABLE OF TY_MSEG,
      IT_CRIT  TYPE STANDARD TABLE OF TY_CRIT  WITH HEADER LINE,
      IT_SHIFT TYPE STANDARD TABLE OF TY_SHIFT WITH HEADER LINE,
      IT_SALE  TYPE STANDARD TABLE OF TY_SALE  WITH HEADER LINE,
      IT_DATS  TYPE STANDARD TABLE OF TY_MSEG  WITH HEADER LINE,
      IT_DATT  TYPE STANDARD TABLE OF TY_MSEG  WITH HEADER LINE,
      IT_MSKA  TYPE STANDARD TABLE OF TY_MSKA  WITH HEADER LINE,",
      IT_STOCK LIKE TY_STOCK OCCURS 0 WITH HEADER LINE.

DATA: BEGIN OF CHAR_OF_BATCH OCCURS 0,
        ATNAM TYPE ATNAM,
        ATINN TYPE ATINN,
        ATWRT TYPE ATWRT,
        ATWTB TYPE ATWTB,
        ATFLV TYPE ATFLV,
      END OF CHAR_OF_BATCH.

DATA: WA_DATS  TYPE TY_MSEG.

FIELD-SYMBOLS: <FS_MSEG>  LIKE LINE OF IT_MSEG,
               <FS_MSEG_CX>  LIKE LINE OF IT_MSEG,
               <FS_MSEG2> LIKE LINE OF IT_MSEG,
               <FS_MSEG3> LIKE LINE OF IT_MSEG,
               <FS_CRIT>  LIKE LINE OF IT_CRIT,
               <FS_CHAR_OF_BATCH> LIKE LINE OF CHAR_OF_BATCH.

RANGES: R_AUART FOR AUFK-AUART. "Additional Order Type 8 January 2013


RANGES: R_AUFNR FOR AUFK-AUFNR,
        R_AUFNR_MTM FOR AUFK-AUFNR,
        R_DATE FOR MKPF-BUDAT,
        R_MATNO FOR MARA-MATNR,
        R_CHARG FOR MCH1-CHARG,
        R_MILLOC FOR AFPO-MILL_OC_AUFNR_U,
        R_SLOCCX FOR T001L-LGORT.

DATA: IT_CHARG TYPE STANDARD TABLE OF TY_MSEG WITH HEADER LINE.

*****************
* SELECTION AREA
*****************
SELECTION-SCREEN BEGIN OF BLOCK 1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: MATNR  FOR  MARA-MATNR,
                WERKS  FOR  MCHB-WERKS,
                MATKL  FOR  MARA-MATKL.
SELECT-OPTIONS: BUDAT  FOR  MSEG-BUDAT_MKPF OBLIGATORY NO-EXTENSION.
SELECT-OPTIONS: ZLINE  FOR  CAWN-ATWRT NO INTERVALS.
SELECTION-SCREEN END OF BLOCK 1.

SELECTION-SCREEN BEGIN OF BLOCK 2 WITH FRAME TITLE TEXT-002.
PARAMETER: V_RB1 RADIOBUTTON GROUP RB.
PARAMETER: V_RB2 RADIOBUTTON GROUP RB.
SELECTION-SCREEN END OF BLOCK 2.