*&---------------------------------------------------------------------*
*&  Include           ZPPR_SLITTING_REKAP_DAILY_F01
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  GET_ATINN
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM GET_ATINN USING P_INPUT TYPE STRING
            CHANGING V_ATINN.
  CLEAR: V_ATINN.
  CALL FUNCTION 'CONVERSION_EXIT_ATINN_INPUT'
    EXPORTING
      INPUT  = P_INPUT
    IMPORTING
      OUTPUT = V_ATINN.
ENDFORM.                    "GET_ATINN


*&---------------------------------------------------------------------*
*&      Form  F_INITITIALIZATION
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM F_INITITIALIZATION .

  CLEAR V_LINE.
  REFRESH V_LINE.

  PERFORM GET_ATINN USING 'ZZPRODLINE' CHANGING V_ATINN.
  IF V_ATINN NE '0000000000'.
    SELECT CAWN~ATWRT CAWNT~ATWTB
      INTO TABLE V_LINE
      FROM CAWN
     INNER JOIN CAWNT ON CAWNT~ATINN = CAWN~ATINN AND CAWNT~ATZHL = CAWN~ATZHL
     WHERE CAWN~ATINN = V_ATINN.
  ENDIF.

ENDFORM.                    "F_INITITIALIZATION

*&---------------------------------------------------------------------*
*&      Form  F_GET_VALUES_REQUEST
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->FC_ATWRT   text
*----------------------------------------------------------------------*
FORM F_GET_VALUES_REQUEST CHANGING FC_ATWRT.

  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD        = 'ATWRT'
      DYNPPROG        = SY-REPID
      DYNPNR          = SY-DYNNR
      DYNPROFIELD     = 'ATWRT'
      VALUE_ORG       = 'S'
    TABLES
      VALUE_TAB       = V_LINE
    EXCEPTIONS
      PARAMETER_ERROR = 1
      NO_VALUES_FOUND = 2
      OTHERS          = 3.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.                    "f_get_values_request


*&---------------------------------------------------------------------*
*&      Form  DEFINE_AUART
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM DEFINE_AUART.

  CLEAR V_AUART.
  REFRESH V_AUART.

  V_AUART-LOW     =  'ZAD1'.
  APPEND V_AUART.
  V_AUART-LOW     =  'ZAD2'.
  APPEND V_AUART.
  V_AUART-LOW     =  'ZBS1'.
  APPEND V_AUART.
  V_AUART-LOW     =  'ZBS2'.
  APPEND V_AUART.
  V_AUART-LOW     =  'ZRR1'.
  APPEND V_AUART.
  V_AUART-LOW     =  'ZRR2'.
  APPEND V_AUART.

  V_AUART-SIGN    =  'I'.
  V_AUART-OPTION  =  'EQ'.
  MODIFY V_AUART TRANSPORTING SIGN OPTION WHERE SIGN = ''.

  V_AUARTSL-LOW = 'PPA1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'PPA2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'PPT2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'PPZ1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'PPZ2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'TPA1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'TPA2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'TPT2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'TPZ1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'TPZ2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPE2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPL2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPP1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPP2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPR2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPS2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPX2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZTO1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZTO2'.
  APPEND V_AUARTSL.
  " Added by William at 28.07.2022 (OPP7 CPP1)
  V_AUARTSL-LOW = 'CPZ2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'EPZ2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'BPZ1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'BPZ2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'CPP2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'CPE2'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPB1'.
  APPEND V_AUARTSL.
  V_AUARTSL-LOW = 'ZPB2'.
  APPEND V_AUARTSL.
  " End added by William at 28.07.2022 (OPP7 CPP1)

  V_AUARTTR-SIGN = 'I'.
  V_AUARTTR-OPTION = 'EQ'.
  V_AUARTTR-LOW = 'ZPL1'.
  APPEND V_AUARTTR.

  V_AUARTSL-SIGN = 'I'.
  V_AUARTSL-OPTION = 'EQ'.
  MODIFY V_AUARTSL TRANSPORTING SIGN OPTION WHERE SIGN = ''.

  V_AUARTTR-SIGN = 'I'.
  V_AUARTTR-OPTION = 'EQ'.
  V_AUARTTR-LOW = 'ZMM1'.
  APPEND V_AUARTTR.

ENDFORM.                    " define_auart


*&---------------------------------------------------------------------*
*&      Form  GET_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM GET_DATA.

  DATA : BEGIN OF IT_MATNR OCCURS 0,
          MATNR LIKE MARA-MATNR,
         END OF IT_MATNR.
  RANGES :  R_MATNR FOR MARA-MATNR,
            R_BUDAT FOR MKPF-BUDAT,
            R_MBLNR FOR MKPF-MBLNR,
            R_AUFNR_CX FOR AUFK-AUFNR,
            R_COMB FOR AUFK-AUFNR.

  DATA : START_TIME TYPE T,
         FINISH_TIME TYPE T,
         PROC_TIME TYPE I,
         DAY TYPE I,
         START_DATE TYPE D,
         END_DATE TYPE D.


  DATA : V_BUDAT_LOW LIKE P0001-BEGDA,
         V_BUDAT_HIGH LIKE P0001-BEGDA,
         V_AUFNR LIKE AUFK-AUFNR.

  DATA: IT_TMSEG TYPE STANDARD TABLE OF TY_MSEG WITH HEADER LINE.

  CLEAR : IT_MATNR, R_MATNR, IT_MSEG.
  REFRESH : IT_MATNR, R_MATNR, IT_MSEG.
  CLEAR : R_MATNR, R_BUDAT, R_MBLNR, R_AUFNR_MTM, R_SLOCCX.
  REFRESH : R_MATNR, R_BUDAT, R_MBLNR, R_AUFNR_MTM, R_SLOCCX.

  SELECT MATNR
    INTO TABLE IT_MATNR
    FROM MARA
    WHERE MATNR IN MATNR AND
          MATKL IN MATKL AND
          MTART = 'ZFGS'.

  LOOP AT IT_MATNR.
    IF IT_MATNR-MATNR IS NOT INITIAL.
      R_MATNR-SIGN = 'I'.
      R_MATNR-OPTION = 'EQ'.
      R_MATNR-LOW = IT_MATNR-MATNR.
      COLLECT R_MATNR.
      CLEAR R_MATNR.
    ENDIF.
  ENDLOOP.

  IF BUDAT-HIGH IS NOT INITIAL.
    V_BUDAT_LOW = BUDAT-LOW.
    V_BUDAT_HIGH = BUDAT-HIGH.
    CLEAR : R_BUDAT.
    R_BUDAT-SIGN = 'I'.
    R_BUDAT-OPTION = 'EQ'.
    R_BUDAT-LOW = V_BUDAT_LOW.
    COLLECT R_BUDAT.
    CLEAR : R_BUDAT.

    WHILE V_BUDAT_LOW < V_BUDAT_HIGH.
      V_BUDAT_LOW = V_BUDAT_LOW + 1.
      R_BUDAT-SIGN = 'I'.
      R_BUDAT-OPTION = 'EQ'.
      R_BUDAT-LOW = V_BUDAT_LOW.
      COLLECT R_BUDAT.
      CLEAR : R_BUDAT.
    ENDWHILE.
  ELSE.
    R_BUDAT[] = BUDAT[].
  ENDIF.

  SELECT AUFNR AS LOW
     INTO CORRESPONDING FIELDS OF TABLE R_AUFNR_MTM
     FROM AUFK
     WHERE ERDAT IN R_BUDAT AND
           AUFK~AUART IN V_AUARTTR.
  IF SY-SUBRC = 0.
    R_AUFNR_MTM-SIGN = 'I'.
    R_AUFNR_MTM-OPTION = 'EQ'.
    MODIFY R_AUFNR_MTM TRANSPORTING SIGN OPTION WHERE SIGN = ''.
    DELETE R_AUFNR_MTM WHERE LOW = ''.
  ENDIF.

  SELECT DISTINCT ZCXLGORT AS LOW
     INTO CORRESPONDING FIELDS OF TABLE R_SLOCCX
     FROM ZTMAP_SLOCRR.
  IF SY-SUBRC = 0.
    R_SLOCCX-SIGN = 'I'.
    R_SLOCCX-OPTION = 'EQ'.
    MODIFY R_SLOCCX TRANSPORTING SIGN OPTION WHERE SIGN = ''.
    DELETE R_SLOCCX WHERE LOW = ''.
  ENDIF.

  PERFORM GET_ATINN USING 'ZZPRODLINE' CHANGING V_ATINN.
  SELECT CAWN~ATINN CAWN~ATWRT CAWNT~ATWTB
    INTO CORRESPONDING FIELDS OF TABLE IT_PRODLINE
    FROM CAWN
    JOIN CAWNT ON CAWN~ATZHL = CAWNT~ATZHL AND
         CAWN~ATINN = CAWNT~ATINN
    WHERE CAWN~ATINN = V_ATINN.

  LOOP AT R_BUDAT.
    " get GRN 101 for Slitting Execution
    REFRESH: IT_TMSEG.
    SELECT MSEG~MBLNR MSEG~MJAHR MSEG~ZEILE MSEG~SMBLN MSEG~SMBLP MSEG~BWART
           MSEG~MATNR MSEG~CHARG MSEG~WERKS MSEG~LGORT MSEG~MENGE MSEG~MEINS
           MSEG~AUFNR MSEG~KDAUF MSEG~KDPOS MSEG~ABLAD MSEG~BUDAT_MKPF AS BUDAT
           MSEG~MAT_KDAUF AS KDAUF2 MSEG~MAT_KDPOS AS KDPOS2 MKPF~CPUTM
           VBAK~AUART AS AUART2 VBAK~KUNNR
      INTO CORRESPONDING FIELDS OF TABLE IT_TMSEG
      FROM MKPF
          JOIN MSEG ON MKPF~MBLNR = MSEG~MBLNR AND MKPF~MJAHR = MSEG~MJAHR
          LEFT OUTER JOIN VBAK ON MSEG~MAT_KDAUF = VBAK~VBELN "Added by Fany 18.01.2025
      WHERE MSEG~MANDT = SY-MANDT AND
            MSEG~MATNR IN R_MATNR AND
            MSEG~BWART = '101' AND
            MSEG~WERKS IN WERKS AND
            MSEG~BUDAT_MKPF = R_BUDAT-LOW.
    IF SY-SUBRC = 0.
      IF IT_TMSEG[] IS NOT INITIAL.
        APPEND LINES OF IT_TMSEG TO IT_MSEG.
      ENDIF.
    ENDIF.

    " get Condux Slitting Execution
    REFRESH: IT_TMSEG.
    SELECT MSEG~MBLNR MSEG~MJAHR MSEG~ZEILE MSEG~SMBLN MSEG~SMBLP MSEG~BWART
           MSEG~WERKS MSEG~LGORT MSEG~MEINS MSEG~MENGE MKPF~CPUTM MKPF~XABLN AS ARBPL
           MSEG~AUFNR MSEG~KDAUF MSEG~KDPOS MSEG~ABLAD MSEG~BUDAT_MKPF AS BUDAT
           MKPF~CPUTM
    INTO CORRESPONDING FIELDS OF TABLE IT_TMSEG
    FROM MKPF
          JOIN MSEG ON MKPF~MBLNR = MSEG~MBLNR AND MKPF~MJAHR = MSEG~MJAHR
    WHERE MSEG~BWART = '261'  AND
          MSEG~WERKS IN WERKS AND
          MSEG~BUDAT_MKPF = R_BUDAT-LOW AND
          MSEG~XBLNR_MKPF NOT LIKE 'SCR%'.
    IF SY-SUBRC = 0.
      IF IT_TMSEG[] IS NOT INITIAL.
        IT_TMSEG-CX = 'X'.
        MODIFY IT_TMSEG TRANSPORTING CX WHERE AUFNR IS NOT INITIAL.
        APPEND LINES OF IT_TMSEG TO IT_MSEG.
      ENDIF.
    ENDIF.

    IF R_AUFNR_MTM[] IS NOT INITIAL.
      " get GRN 531 for Transfer Mat FG to Mat FG
      REFRESH: IT_TMSEG.
      SELECT MSEG~MBLNR MSEG~MJAHR MSEG~ZEILE MSEG~SMBLN MSEG~SMBLP MSEG~BWART
         MSEG~MATNR MSEG~CHARG MSEG~WERKS MSEG~LGORT MSEG~MENGE MSEG~MEINS MKPF~CPUTM
         MSEG~AUFNR MSEG~KDAUF MSEG~KDPOS MSEG~ABLAD MSEG~BUDAT_MKPF AS BUDAT
         MKPF~CPUTM MKPF~XABLN AS ARBPL MSEG~MAT_KDAUF AS KDAUF2 MSEG~MAT_KDPOS AS KDPOS2
         VBAK~AUART AS AUART2 VBAK~KUNNR
        INTO CORRESPONDING FIELDS OF TABLE IT_TMSEG
        FROM MKPF
          JOIN MSEG ON MKPF~MBLNR = MSEG~MBLNR AND MKPF~MJAHR = MSEG~MJAHR
          LEFT OUTER JOIN VBAK ON MSEG~MAT_KDAUF = VBAK~VBELN "Added by Fany 30.01.2025
        WHERE MSEG~MANDT = SY-MANDT AND
              MSEG~BWART = '531' AND
              MSEG~WERKS IN WERKS AND
              MSEG~AUFNR IN R_AUFNR_MTM AND
              MSEG~MATNR IN R_MATNR AND
              MSEG~BUDAT_MKPF = R_BUDAT-LOW AND
              MSEG~CHARG <> ''.
      IF SY-SUBRC = 0.
        IF IT_TMSEG[] IS NOT INITIAL.
          APPEND LINES OF IT_TMSEG TO IT_MSEG.
        ENDIF.
      ENDIF.


      " get CX for Transfer Mat FG to Mat FG
      SELECT MSEG~MBLNR MSEG~MJAHR MSEG~ZEILE MSEG~SMBLN MSEG~SMBLP MSEG~BWART
           MSEG~CHARG MSEG~WERKS MSEG~LGORT MSEG~MEINS MKPF~CPUTM
           MSEG~AUFNR MSEG~KDAUF MSEG~KDPOS MSEG~ABLAD MSEG~BUDAT_MKPF AS BUDAT
           MKPF~CPUTM MKPF~XABLN AS ARBPL
      INTO CORRESPONDING FIELDS OF TABLE IT_TMSEG
      FROM MKPF
         JOIN MSEG ON MKPF~MBLNR = MSEG~MBLNR AND MKPF~MJAHR = MSEG~MJAHR
      WHERE MSEG~BWART IN ('261') AND
         MSEG~XBLNR_MKPF NOT LIKE 'SCR%'AND
         MSEG~WERKS IN WERKS AND
         MSEG~AUFNR IN R_AUFNR_MTM AND
         MSEG~BUDAT_MKPF = R_BUDAT-LOW.
    ENDIF.
    IF SY-SUBRC = 0.
      IF IT_TMSEG[] IS NOT INITIAL.
        IT_TMSEG-CX = 'X'.
        MODIFY IT_TMSEG TRANSPORTING CX WHERE AUFNR IS NOT INITIAL.
        APPEND LINES OF IT_TMSEG TO IT_MSEG.
      ENDIF.
    ENDIF.
  ENDLOOP.

  DELETE IT_MSEG WHERE AUFNR IS INITIAL.

  CLEAR : R_MBLNR.
  REFRESH : R_MBLNR.

  LOOP AT IT_MSEG.
    IF IT_MSEG-MBLNR IS NOT INITIAL.
      R_MBLNR-SIGN = 'I'.
      R_MBLNR-OPTION = 'EQ'.
      R_MBLNR-LOW = IT_MSEG-MBLNR.
      COLLECT R_MBLNR.
      CLEAR : R_MBLNR.
    ENDIF.
  ENDLOOP.

  IF R_MBLNR[] IS NOT INITIAL.
    SELECT MBLNR SMBLN
    INTO CORRESPONDING FIELDS OF TABLE IT_SMBLN
    FROM MSEG
    WHERE SMBLN IN R_MBLNR.
  ENDIF.

  LOOP AT IT_SMBLN.
    DELETE IT_MSEG WHERE MBLNR = IT_SMBLN-SMBLN.
  ENDLOOP.

  LOOP AT IT_MSEG.
    IF IT_MSEG-AUFNR IS NOT INITIAL.
      IF IT_MSEG-CX = 'X'.
        R_AUFNR_CX-SIGN = 'I'.
        R_AUFNR_CX-OPTION = 'EQ'.
        R_AUFNR_CX-LOW = IT_MSEG-AUFNR.
        COLLECT R_AUFNR_CX.
        CLEAR : R_AUFNR_CX.
      ELSE.
        R_AUFNR-SIGN = 'I'.
        R_AUFNR-OPTION = 'EQ'.
        R_AUFNR-LOW = IT_MSEG-AUFNR.
        COLLECT R_AUFNR.
        CLEAR : R_AUFNR.
      ENDIF.
    ENDIF.
    IF IT_MSEG-KUNNR IS NOT INITIAL. "Get Customer name - Added by Fany 20.01.2025
       SELECT SINGLE NAME1 INTO V_CUSTNAME FROM KNA1 WHERE KUNNR = IT_MSEG-KUNNR.
       IF SY-SUBRC EQ 0.
         IT_MSEG-NAME1 = V_CUSTNAME.
         MODIFY IT_MSEG.
       ENDIF.
    ENDIF.

     IF IT_MSEG-KDPOS2 IS NOT INITIAL. "Get Customer name - Added by Fany 21.01.2025
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = IT_MSEG-KDPOS2
        IMPORTING
          OUTPUT = IT_MSEG-KDPOS2.
      MODIFY IT_MSEG.
    ENDIF.

     IF IT_MSEG-KDAUF2 IS NOT INITIAL. "Get Customer name - Added by Fany 21.01.2025
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = IT_MSEG-KDAUF2
        IMPORTING
          OUTPUT = IT_MSEG-KDAUF2.
      MODIFY IT_MSEG.
    ENDIF.
  ENDLOOP.

  "Get Data CX
  CLEAR: IT_MSEG_CX.
  REFRESH: IT_MSEG_CX.

  IF R_AUFNR_CX[] IS NOT INITIAL.
    CLEAR: R_MILLOC.
    REFRESH: R_MILLOC.
    SELECT AFPO~MILL_OC_AUFNR_U AS LOW
      INTO CORRESPONDING FIELDS OF TABLE R_MILLOC
      FROM AFPO
     WHERE AFPO~AUFNR IN R_AUFNR_CX.
    R_MILLOC-SIGN = 'I'.
    R_MILLOC-OPTION = 'EQ'.
    MODIFY R_MILLOC TRANSPORTING SIGN OPTION WHERE SIGN = ''.
    DELETE R_MILLOC WHERE LOW = ''.

    SELECT MCH1~MATNR AS MATNR
           MCH1~CHARG AS CHARG
           MCH1~LICHA AS AUFNR
           MCH1~CUOBJ_BM AS CUOBJ_BM
           MARA~MEINS
           MARA~MATKL
           MARA~MTART
    INTO CORRESPONDING FIELDS OF TABLE IT_MSEG_CX
    FROM MCH1
      JOIN MARA ON MCH1~MATNR = MARA~MATNR
    WHERE MCH1~LICHA IN R_AUFNR_CX.
  ENDIF.

  IF R_MILLOC[] IS NOT INITIAL.
    SELECT MCH1~MATNR AS MATNR
           MCH1~CHARG AS CHARG
           MCH1~LICHA AS AUFNR
           MCH1~CUOBJ_BM AS CUOBJ_BM
           MARA~MEINS
           MARA~MATKL
           MARA~MTART
      APPENDING CORRESPONDING FIELDS OF TABLE IT_MSEG_CX
      FROM MCH1
      JOIN MARA ON MCH1~MATNR = MARA~MATNR
      WHERE MCH1~LICHA IN R_MILLOC.
  ENDIF.
  "End Get Data CX

  LOOP AT IT_MSEG_CX.
    IF IT_MSEG_CX-AUFNR IS NOT INITIAL.
      R_AUFNR-SIGN = 'I'.
      R_AUFNR-OPTION = 'EQ'.
      R_AUFNR-LOW = IT_MSEG_CX-AUFNR.
      COLLECT R_AUFNR.
      CLEAR : R_AUFNR.
    ENDIF.
  ENDLOOP.

  IF R_AUFNR[] IS NOT INITIAL.
    SELECT AUFNR AUART
      INTO CORRESPONDING FIELDS OF TABLE IT_AUART
      FROM AUFK
    WHERE AUFNR IN R_AUFNR.

    SELECT AUFNR DAUAT MILL_OC_AUFNR_U AS AUFNR_U
      INTO CORRESPONDING FIELDS OF TABLE IT_MILLOC
      FROM AFPO
      WHERE MILL_OC_AUFNR_U IN R_AUFNR.
  ENDIF.

  LOOP AT IT_MILLOC.
    IF IT_MILLOC-AUFNR IS NOT INITIAL.
      R_COMB-SIGN = 'I'.
      R_COMB-OPTION = 'EQ'.
      R_COMB-LOW = IT_MILLOC-AUFNR.
      COLLECT R_COMB.
      CLEAR : R_COMB.
    ENDIF.
  ENDLOOP.

  IF R_COMB[] IS NOT INITIAL.
    SELECT  AFRU~AUFNR
            AFRU~ARBID
            AFRU~ISM01
            AFRU~ISDD
            AFRU~ISDZ
            AFRU~IEDD
            AFRU~IEDZ
            CRHD~ARBPL
       INTO CORRESPONDING FIELDS OF TABLE IT_AFRU
       FROM AFRU
          JOIN CRHD ON AFRU~ARBID = CRHD~OBJID
       WHERE AFRU~AUFNR IN R_COMB.

    SELECT AUFNR LGORT AS ZCXLGORT
    INTO CORRESPONDING FIELDS OF TABLE IT_SLOCCX
    FROM MSEG
    WHERE AUFNR IN R_COMB AND LGORT IN R_SLOCCX.

    SELECT AUFNR LGORT AS ZCXLGORT
    APPENDING CORRESPONDING FIELDS OF TABLE IT_SLOCCX
    FROM MSEG
    WHERE AUFNR IN R_AUFNR_CX AND LGORT IN R_SLOCCX.
  ENDIF.


  UNASSIGN <FS_MSEG_CX>.
  LOOP AT IT_MSEG_CX ASSIGNING <FS_MSEG_CX>.
    CLEAR : CHAR_OF_BATCH.
    REFRESH : CHAR_OF_BATCH.

    SELECT CABN~ATNAM AS ATNAM
           AUSP~ATINN AS ATINN
           AUSP~ATWRT AS ATWRT
           AUSP~ATFLV AS ATFLV
     FROM CABN
     JOIN AUSP ON CABN~ATINN = AUSP~ATINN
     INTO CORRESPONDING FIELDS OF TABLE CHAR_OF_BATCH
     WHERE AUSP~OBJEK  = <FS_MSEG_CX>-CUOBJ_BM
     AND   CABN~ATNAM IN ('ZZNOMORROLL','ZZWIDTH','ZZCONVERSIONROLLKG','ZZLENGTH', 'ZZEXLENGTH', 'ZZALIAS', 'ZZDERIVATIVEMS', 'ZZPOSITIONMS','ZZDERIVATIVESS', 'ZZPOSITIONSS',
                          'ZZCORETYPE').  " Added by William at 20.06.2025 (Add ZZCORETYPE)

    SELECT CABN~ATNAM AS ATNAM
           AUSP~ATINN AS ATINN
           AUSP~ATWRT AS ATWRT
           CAWNT~ATWTB AS ATWTB
    FROM CABN
    JOIN AUSP ON CABN~ATINN = AUSP~ATINN
    JOIN CAWN ON  AUSP~ATINN = CAWN~ATINN
              AND AUSP~ATWRT = CAWN~ATWRT
    JOIN CAWNT ON CAWN~ATINN = CAWNT~ATINN
              AND CAWN~ATZHL = CAWNT~ATZHL
    APPENDING CORRESPONDING FIELDS OF TABLE CHAR_OF_BATCH
    WHERE AUSP~OBJEK  = <FS_MSEG_CX>-CUOBJ_BM
    AND   CABN~ATNAM IN ('ZZCODE','ZZPRODLINE','ZZTREATMENT','ZZPACKING','ZZCRITERIA','ZZGRADE',
                         'ZZCORETYPE').  " Added by William at 20.06.2025 (Add ZZCORETYPE)

    READ TABLE CHAR_OF_BATCH INDEX 1.
    CHECK SY-SUBRC = 0.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCRITERIA'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-CRIT = <FS_CHAR_OF_BATCH>-ATWTB.
      <FS_MSEG_CX>-V_LASTCRIT = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    CHECK <FS_MSEG_CX>-CRIT = 'Scrap'.

    READ TABLE IT_AUART WITH KEY AUFNR = <FS_MSEG_CX>-AUFNR.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-AUART = IT_AUART-AUART.
    ENDIF.

    IF <FS_MSEG_CX>-AUART = 'ZMM1'.
      <FS_MSEG_CX>-COMB = <FS_MSEG_CX>-AUFNR.
    ELSE.
      READ TABLE IT_MILLOC WITH KEY AUFNR_U = <FS_MSEG_CX>-AUFNR.
      IF SY-SUBRC = 0.
        <FS_MSEG_CX>-COMB = IT_MILLOC-AUFNR.
      ENDIF.
    ENDIF.

    UNASSIGN <FS_MSEG>.
    READ TABLE IT_MSEG ASSIGNING <FS_MSEG> WITH KEY AUFNR = <FS_MSEG_CX>-COMB.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-BUDAT = <FS_MSEG>-BUDAT.
      <FS_MSEG_CX>-WERKS = <FS_MSEG>-WERKS.
      <FS_MSEG_CX>-CPUTM = <FS_MSEG>-CPUTM.
      <FS_MSEG_CX>-MBLNR = <FS_MSEG>-MBLNR.
      <FS_MSEG_CX>-ARBPL = <FS_MSEG>-ARBPL.
    ENDIF.

    READ TABLE IT_SLOCCX WITH KEY AUFNR = <FS_MSEG_CX>-COMB.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-LGORT = IT_SLOCCX-ZCXLGORT.
    ENDIF.


    READ TABLE IT_AFRU WITH KEY AUFNR = <FS_MSEG_CX>-COMB.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ARBPL = IT_AFRU-ARBPL.
      <FS_MSEG_CX>-IEDZ = IT_AFRU-IEDZ.
      <FS_MSEG_CX>-IEDD = IT_AFRU-IEDD.
      <FS_MSEG_CX>-ISM01 = IT_AFRU-ISM01.

      CLEAR : FINISH_TIME, PROC_TIME, START_TIME, DAY.

      MOVE IT_AFRU-IEDZ TO FINISH_TIME.
      PROC_TIME = IT_AFRU-ISM01 * 60.
      START_TIME = FINISH_TIME - PROC_TIME.
      DAY = START_TIME - FINISH_TIME.
      <FS_MSEG_CX>-ISDZ = START_TIME.

      IF DAY GE 0. "BERKURANG 1 HARI
        <FS_MSEG_CX>-ISDD = IT_AFRU-IEDD - 1.
      ELSE.
        <FS_MSEG_CX>-ISDD = IT_AFRU-IEDD.
      ENDIF.

    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZGRADE'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-GRADE = <FS_CHAR_OF_BATCH>-ATWRT.
      <FS_MSEG_CX>-V_LASTGRADE = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCODE'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZZCODE = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZNOMORROLL'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-NOROLL = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZALIAS'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZALIAS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZDERIVATIVEMS'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZDERMS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM =  'ZZPOSITIONMS'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZPOSMS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZDERIVATIVESS'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZDERSS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPOSITIONSS'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZPOSSS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZWIDTH'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-WIDTH2 = <FS_CHAR_OF_BATCH>-ATFLV.
      <FS_MSEG_CX>-WIDTH  = <FS_MSEG_CX>-WIDTH2.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZLENGTH'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-LENGTH2 = <FS_CHAR_OF_BATCH>-ATFLV.
      <FS_MSEG_CX>-LENGTH  = <FS_MSEG_CX>-LENGTH2.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZEXLENGTH'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZEXTRA = <FS_CHAR_OF_BATCH>-ATFLV.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPRODLINE'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-LINE = <FS_CHAR_OF_BATCH>-ATWTB.

      READ TABLE IT_PRODLINE WITH KEY ATWTB = <FS_MSEG_CX>-LINE.
      IF SY-SUBRC = 0.
        <FS_MSEG_CX>-LINECD = IT_PRODLINE-ATWRT.
      ENDIF.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZTREATMENT'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-TREAT = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPACKING'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-PCKNG = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCONVERSIONROLLKG'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZCONV = <FS_CHAR_OF_BATCH>-ATFLV.
      <FS_MSEG_CX>-MENGE = <FS_CHAR_OF_BATCH>-ATFLV.
    ENDIF.

    IF <FS_MSEG_CX>-ISM01 > 0.
      <FS_MSEG_CX>-ZSPEED = ( <FS_MSEG_CX>-LENGTH + <FS_MSEG_CX>-ZEXTRA ) / <FS_MSEG_CX>-ISM01.
    ENDIF.

    IF <FS_MSEG_CX>-ZDERSS IS NOT INITIAL.
      <FS_MSEG_CX>-ZMSSS = 'SS'.
    ELSE.
      <FS_MSEG_CX>-ZMSSS = 'MS'.
    ENDIF.

    IF <FS_MSEG_CX>-CRIT = 'Scrap'.
      MOVE-CORRESPONDING <FS_MSEG_CX> TO IT_MSEG.
      APPEND IT_MSEG.
      CLEAR IT_MSEG.
    ENDIF.

    " Added by William at 20.06.2025 (Add ZZCORETYPE)
    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCORETYPE'.
    IF SY-SUBRC = 0.
      <FS_MSEG_CX>-ZZCORETYPE = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.
    " End added by William at 20.06.2025 (Add ZZCORETYPE)

  ENDLOOP.

  DELETE IT_MSEG_CX WHERE CRIT NE 'Scrap'.
  DELETE IT_MSEG WHERE CX = 'X'.
  DELETE IT_MSEG WHERE MATNR NOT IN MATNR.

  UNASSIGN <FS_MSEG>.
  LOOP AT IT_MSEG ASSIGNING <FS_MSEG> WHERE CRIT NE 'Scrap'.

    READ TABLE IT_AUART WITH KEY AUFNR = <FS_MSEG>-AUFNR.
    IF SY-SUBRC = 0.
      <FS_MSEG>-AUART = IT_AUART-AUART.
    ENDIF.

    READ TABLE V_AUARTSL WITH KEY LOW = <FS_MSEG>-AUART.
    IF SY-SUBRC <> 0.
      READ TABLE V_AUARTTR WITH KEY LOW = <FS_MSEG>-AUART.
    ENDIF.

    CHECK SY-SUBRC = 0.

    IF <FS_MSEG>-AUART = 'ZMM1'.
      <FS_MSEG>-COMB = <FS_MSEG>-AUFNR.
    ELSE.
      READ TABLE IT_MILLOC WITH KEY AUFNR_U = <FS_MSEG>-AUFNR.
      IF SY-SUBRC = 0.
        <FS_MSEG>-COMB = IT_MILLOC-AUFNR.
      ENDIF.
    ENDIF.

    READ TABLE IT_AFRU WITH KEY AUFNR = <FS_MSEG>-COMB.
    IF SY-SUBRC = 0.
      CLEAR : FINISH_TIME, PROC_TIME, START_TIME, DAY.
      <FS_MSEG>-ARBPL = IT_AFRU-ARBPL.
      <FS_MSEG>-IEDZ = IT_AFRU-IEDZ.
      <FS_MSEG>-IEDD = IT_AFRU-IEDD.
      <FS_MSEG>-ISM01 = IT_AFRU-ISM01.

      MOVE IT_AFRU-IEDZ TO FINISH_TIME.
      PROC_TIME = IT_AFRU-ISM01 * 60.
      START_TIME = FINISH_TIME - PROC_TIME.
      DAY = START_TIME - FINISH_TIME.

      <FS_MSEG>-ISDZ = START_TIME.

      IF DAY GE 0. "BERKURANG 1 HARI
        <FS_MSEG>-ISDD = IT_AFRU-IEDD - 1.
      ELSE.
        <FS_MSEG>-ISDD = IT_AFRU-IEDD.
      ENDIF.

    ENDIF.

    SPLIT <FS_MSEG>-ABLAD AT '/' INTO <FS_MSEG>-LENGTH <FS_MSEG>-GRADE <FS_MSEG>-CRIT.
    <FS_MSEG>-LENGTH2 = <FS_MSEG>-LENGTH.

    IF <FS_MSEG>-CRIT NE ''.
      PERFORM GET_ATINN USING 'ZZCRITERIA' CHANGING V_ATINN.
      CLEAR: V_ATZHL.
      SELECT SINGLE ATZHL
        INTO V_ATZHL
        FROM CAWN
       WHERE ATINN = V_ATINN AND ATWRT = <FS_MSEG>-CRIT.
      IF SY-SUBRC = 0.
        CLEAR: <FS_MSEG>-CRIT.
        SELECT SINGLE ATWTB
          INTO <FS_MSEG>-CRIT
          FROM CAWNT
         WHERE ATINN = V_ATINN AND ATZHL = V_ATZHL AND SPRAS = 'EN'.
      ENDIF.
    ENDIF.

    CLEAR: CHAR_OF_BATCH.
    REFRESH: CHAR_OF_BATCH.

    SELECT CABN~ATNAM AS ATNAM
          AUSP~ATINN AS ATINN
          AUSP~ATWRT AS ATWRT
          AUSP~ATFLV AS ATFLV
    FROM CABN
    JOIN AUSP ON CABN~ATINN = AUSP~ATINN
     JOIN MCH1 ON AUSP~OBJEK = MCH1~CUOBJ_BM
    INTO CORRESPONDING FIELDS OF TABLE CHAR_OF_BATCH
    WHERE MCH1~MATNR  = <FS_MSEG>-MATNR AND MCH1~CHARG  = <FS_MSEG>-CHARG
    AND   CABN~ATNAM IN ('ZZNOMORROLL','ZZWIDTH','ZZCONVERSIONROLLKG', 'ZZEXLENGTH', 'ZZALIAS', 'ZZDERIVATIVEMS', 'ZZPOSITIONMS','ZZDERIVATIVESS', 'ZZPOSITIONSS').

    SELECT CABN~ATNAM AS ATNAM
       AUSP~ATINN AS ATINN
       AUSP~ATWRT AS ATWRT
       CAWNT~ATWTB AS ATWTB
    FROM CABN
    JOIN AUSP ON CABN~ATINN = AUSP~ATINN
    JOIN MCH1 ON AUSP~OBJEK = MCH1~CUOBJ_BM
    JOIN CAWN ON  AUSP~ATINN = CAWN~ATINN
              AND AUSP~ATWRT = CAWN~ATWRT
    JOIN CAWNT ON CAWN~ATINN = CAWNT~ATINN
              AND CAWN~ATZHL = CAWNT~ATZHL
    APPENDING CORRESPONDING FIELDS OF TABLE CHAR_OF_BATCH
    WHERE MCH1~MATNR  = <FS_MSEG>-MATNR AND MCH1~CHARG  = <FS_MSEG>-CHARG
    AND   CABN~ATNAM IN ('ZZCODE','ZZPRODLINE','ZZTREATMENT','ZZPACKING', 'ZZGRADE', 'ZZCRITERIA',
                         'ZZCORETYPE').  " Added by William at 20.06.2025 (Add ZZCORETYPE)

    READ TABLE CHAR_OF_BATCH INDEX 1. " Add 21 January 2013
    CHECK SY-SUBRC = 0.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCODE'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZZCODE = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZNOMORROLL'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-NOROLL = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZALIAS'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZALIAS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZDERIVATIVEMS'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZDERMS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM =  'ZZPOSITIONMS'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZPOSMS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZDERIVATIVESS'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZDERSS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPOSITIONSS'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZPOSSS = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZWIDTH'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-WIDTH2 = <FS_CHAR_OF_BATCH>-ATFLV.
      <FS_MSEG>-WIDTH = <FS_MSEG>-WIDTH2.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    PERFORM GET_ATINN USING 'ZZPRODLINE' CHANGING V_ATINN.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPRODLINE'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-LINE = <FS_CHAR_OF_BATCH>-ATWTB.

      READ TABLE IT_PRODLINE WITH KEY ATWTB = <FS_MSEG>-LINE.
      IF SY-SUBRC = 0.
        <FS_MSEG>-LINECD = IT_PRODLINE-ATWRT.
      ENDIF.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZTREATMENT'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-TREAT = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZPACKING'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-PCKNG = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCONVERSIONROLLKG'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZCONV = <FS_CHAR_OF_BATCH>-ATFLV.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZEXLENGTH'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZEXTRA = <FS_CHAR_OF_BATCH>-ATFLV.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZGRADE'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-V_LASTGRADE = <FS_CHAR_OF_BATCH>-ATWRT.
    ENDIF.

    IF <FS_MSEG>-ISM01 > 0.
      <FS_MSEG>-ZSPEED = ( <FS_MSEG>-LENGTH + <FS_MSEG>-ZEXTRA ) / <FS_MSEG>-ISM01.
    ENDIF.

    IF <FS_MSEG>-ZDERSS IS NOT INITIAL.
      <FS_MSEG>-ZMSSS = 'SS'.
    ELSE.
      <FS_MSEG>-ZMSSS = 'MS'.
    ENDIF.

    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCRITERIA'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-V_LASTCRIT = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.

    " Added by William at 20.06.2025 (Add ZZCORETYPE)
    UNASSIGN <FS_CHAR_OF_BATCH>.
    READ TABLE CHAR_OF_BATCH ASSIGNING <FS_CHAR_OF_BATCH> WITH KEY ATNAM = 'ZZCORETYPE'.
    IF SY-SUBRC = 0.
      <FS_MSEG>-ZZCORETYPE = <FS_CHAR_OF_BATCH>-ATWTB.
    ENDIF.
    " End added by William at 20.06.2025 (Add ZZCORETYPE)

  ENDLOOP.

  DELETE IT_MSEG WHERE COMB IS INITIAL.
  DELETE IT_MSEG WHERE LINECD NOT IN ZLINE.


ENDFORM.                    "GET_DATA


*&---------------------------------------------------------------------*
*&      Form  TO_SCREEN
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TO_SCREEN .

  UNASSIGN <FS_MSEG>.
  READ TABLE IT_MSEG ASSIGNING <FS_MSEG> INDEX 1.
  IF SY-SUBRC NE 0.
    EXIT.
  ELSE.
    SORT IT_MSEG BY BUDAT COMB ZDERMS ZPOSMS ZDERSS ZPOSSS.
  ENDIF.

  PERFORM F_FIELD_CATALOG.
  PERFORM F_LAYOUT.
  PERFORM F_LIST_DETAIL.

ENDFORM.                    " TO_SCREEN


*&---------------------------------------------------------------------*
*&      Form  f_field_catalog
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM F_FIELD_CATALOG .
  REFRESH: T_FIELDCAT.
  PERFORM F_ALV_FIELDCATG_ICON_WT_ZERO USING 'IT_MSEG' :
   'BUDAT'  '' ''  '' '10' 'Prod.Date'         '' ' ' '' '',
   'COMB'  '' ''  '' '12' 'Combined Order'     '' ' ' '' '',
   'AUFNR'  '' ''  '' '12' 'Original Order'    '' ' ' '' '',
   'AUART'  '' ''  '' '12' 'Original Order Type'  '' ' ' '' '',
   'WERKS'  '' ''  '' '4' 'Plant'        '' ' ' '' '',
   'LGORT'  '' ''  '' '4' 'Sloc'         '' ' ' '' '',
   'LINECD'  '' ''  '' '4' 'Line'        '' ' ' '' '',
   'LINE'  '' ''  '' '30' 'Line Description'  '' ' ' '' '',
   'ARBPL'  '' ''  '' '30' 'Resource'         '' ' ' '' '',
   'MATNR'  '' ''  '' '18' 'Material'         '' ' ' '' '',
   'ZZCODE' '' ''  '' '30' 'Type Film'        '' ' ' '' '',
   'CHARG'  '' ''  '' '10' 'Batch'            '' ' ' '' '',
   'KDAUF2'  '' ''  '' '10' 'SO'            '' ' ' '' '',
   'KDPOS2'  '' ''  '' '6' 'SO Item'            '' ' ' '' '',
   'AUART2'  '' ''  '' '6' 'Sales Document Type' '' ' ' '' '',
   'KUNNR'  '' ''  '' '10' 'Customer' '' ' ' '' '',
   'NAME1'  '' ''  '' '35' 'Customer Name' '' ' ' '' '',
   'NOROLL' '' ''  '' '30' 'No Roll'          '' ' ' '' '',
   'CRIT'   '' ''  '' '30' 'Criteria'         '' ' ' '' '',
   'GRADE'  '' ''  '' '5'  'Grade'            '' ' ' '' '',
   'ZMSSS'  '' ''  '' '15' 'MS/SS'            '' ' ' '' '',
   'ZDERMS'  '' ''  '' '15' 'Turunan MS'      '' ' ' '' '',
   'ZPOSMS'  '' ''  '' '15' 'Posisi MS'       '' ' ' '' '',
   'ZDERSS'  '' ''  '' '15' 'Turunan SS'      '' ' ' '' '',
   'ZPOSSS'  '' ''  '' '15' 'Posisi SS'       '' ' ' '' '',
   'TREAT'  '' ''  '' '15' 'Treatment'        '' ' ' '' '',
   'PCKNG'  '' ''  '' '15' 'Packing'          '' ' ' '' '',
   'WIDTH'  '' ''  '' '30' 'Lebar'            '' ' ' '' '',
   'LENGTH' '' ''  '' '30' 'Panjang'          '' ' ' '' '',
   'ZEXTRA' '' ''  '' '12' 'Extra Length'     '' ' ' '' '',
   'MENGE'  '' ''  '' '16' 'Quantity'         '' ' ' '' '',
   'MEINS'  '' ''  '' '3'  'UoM'              '' ' ' '' '',
   'ISDD'  '' ''  '' '12'  'Start Date'       '' ' ' '' '',
   'ISDZ'  '' ''  '' '12'  'Start Time'       '' ' ' '' '',
   'ISM01'  '' ''  '' '12'  'Process Time'    '' ' ' '' '',
   'IEDD'  '' ''  '' '12'  'Finish Date'      '' ' ' '' '',
   'IEDZ'  '' ''  '' '12'  'Finish Time'      '' ' ' '' '',
   'CPUTM'  '' ''  '' '12'  'Entered At'       '' ' ' '' '',
   'ZSPEED'  '' ''  '' '12'  'Speed'          '' ' ' '' '',
   'ZZCORETYPE'  '' ''  '' '30'  'Core Type'  '' ' ' '' ''.

ENDFORM.                    " f_field_catalog

*&---------------------------------------------------------------------*
*&      Form  f_layout
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM F_LAYOUT .
  WA_LAYOUT-ZEBRA = 'X'.
  WA_LAYOUT-CONFIRMATION_PROMPT = 'X'.
  WA_LAYOUT-SUBTOTALS_TEXT = 'Sub Total'.
  WA_LAYOUT-TOTALS_TEXT = 'Total'.
  WA_LAYOUT-BOX_FIELDNAME = 'BOX'.
  WA_LAYOUT-CELL_MERGE = 'X'.
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
ENDFORM.                    " f_layout

*&---------------------------------------------------------------------*
*&      Form  f_list_detail
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM F_LIST_DETAIL .
  D_REPID = SY-REPID.
  T_PRINT-NO_PRINT_LISTINFOS = 'X'.
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM       = D_REPID
      I_CALLBACK_USER_COMMAND  = 'F_USER_COMMAND'
      I_CALLBACK_PF_STATUS_SET = 'F_GUI_STATUS'
      IS_LAYOUT                = WA_LAYOUT
      IT_FIELDCAT              = T_FIELDCAT[]
      IT_EVENTS                = T_EVENTS[]
      IT_EVENT_EXIT            = T_EVENT_EXIT[]
      I_DEFAULT                = 'X'
      I_SAVE                   = 'A'
      IS_VARIANT               = WA_VARIANTE
      IS_PRINT                 = T_PRINT
      IT_SORT                  = T_SORT[]
      IT_EXCLUDING             = T_EXCLUDING[]
      I_BYPASSING_BUFFER       = 'X'
    TABLES
      T_OUTTAB                 = IT_MSEG
    EXCEPTIONS
      PROGRAM_ERROR            = 1
      OTHERS                   = 2.

ENDFORM.                    " f_list_detail

*&---------------------------------------------------------------------
*&      Form  F_GUI_STATUS
*&---------------------------------------------------------------------
FORM F_GUI_STATUS USING FT_EXTAB TYPE SLIS_T_EXTAB.
  REFRESH FT_EXTAB.
  CLEAR FT_EXTAB.
  APPEND 'DETAIL' TO FT_EXTAB.

  SET PF-STATUS 'STANDARD_FULLSCREEN' EXCLUDING FT_EXTAB.
ENDFORM.                    " F_ALV_STATUS




*&---------------------------------------------------------------------*
*&      Form  WRITE_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM WRITE_DATA .

  DATA : V_PDATE  TYPE CHAR10.
  DATA : O_CX TYPE REF TO CX_ROOT,
         V_CX_MSG(500).

  DATA: V_DL_TM(20) TYPE C.

  EXEC SQL.
    CONNECT TO 'TRIASDB05' AS 'DBTRIAL'
  ENDEXEC.

  EXEC SQL.
    SET CONNECTION 'DBTRIAL'
  ENDEXEC.


  EXEC SQL.
    DELETE FROM XZPP016
  ENDEXEC.

  EXEC SQL.
    COMMIT WORK
  ENDEXEC.

  " set download time
  CONCATENATE SY-DATUM SY-UZEIT INTO V_DL_TM SEPARATED BY SPACE.

  UNASSIGN <FS_MSEG>.
  LOOP AT IT_MSEG ASSIGNING <FS_MSEG>.
    CLEAR V_PDATE.
    CONCATENATE <FS_MSEG>-BUDAT+6(2) '/' <FS_MSEG>-BUDAT+4(2) '/' <FS_MSEG>-BUDAT+0(4) INTO V_PDATE.
    CONDENSE V_PDATE NO-GAPS.

    " extend program runtime
    CALL FUNCTION 'TH_REDISPATCH'
      EXPORTING
        CHECK_RUNTIME = 0.

    " Modified by William at 20.06.2025 (Add ZZCORETYPE)
    EXEC SQL.
      INSERT INTO XZPP016( PRODDATE,COMBINEDORDER,ORIGINALORDER,ORIGINALORDERTYPE,PLANT,SLOC,PRODLINE,RESOURCE,MATERIAL,
                          FILMTYPE,BATCH,ROLLNO,CRITERIAGRADE,GRADE,MSSS,TURUNANMS,POSISIMS,TURUNANSS,POSISISS,TREATMENT,
                          PACKING,WIDTH,LENGTH,EXTRALENGTH,CORETYPE,QUANTITY,STARTDATE,STARTTIME,FINISHDATE,FINISHTIME,PROCESSTIME,SPEED,
                          LASTCRITERIA,LASTGRADE,DOWNLOADTIME,SO,SOITEM,SOTYPE,SOLDTOPARTY,CUSTOMERNAME,ENTEREDAT)
      VALUES(:<FS_MSEG>-BUDAT,:<FS_MSEG>-COMB,:<FS_MSEG>-AUFNR,:<FS_MSEG>-AUART,:<FS_MSEG>-WERKS,:<FS_MSEG>-LGORT,:<FS_MSEG>-LINECD,:<FS_MSEG>-ARBPL,:<FS_MSEG>-MATNR,
             :<FS_MSEG>-ZZCODE,:<FS_MSEG>-CHARG,:<FS_MSEG>-NOROLL,:<FS_MSEG>-CRIT,:<FS_MSEG>-GRADE,:<FS_MSEG>-ZMSSS,:<FS_MSEG>-ZDERMS,:<FS_MSEG>-ZPOSMS,:<FS_MSEG>-ZDERSS,:<FS_MSEG>-ZPOSSS,:<FS_MSEG>-TREAT,
             :<FS_MSEG>-PCKNG,:<FS_MSEG>-WIDTH,:<FS_MSEG>-LENGTH,:<FS_MSEG>-ZEXTRA,:<FS_MSEG>-ZZCORETYPE,:<FS_MSEG>-MENGE,:<FS_MSEG>-ISDD,:<FS_MSEG>-ISDZ,:<FS_MSEG>-IEDD,:<FS_MSEG>-IEDZ,:<FS_MSEG>-ISM01,:<FS_MSEG>-ZSPEED,
             :<FS_MSEG>-V_LASTCRIT,:<FS_MSEG>-V_LASTGRADE,:V_DL_TM,:<FS_MSEG>-KDAUF2,:<FS_MSEG>-KDPOS2,:<FS_MSEG>-AUART2,:<FS_MSEG>-KUNNR,:<FS_MSEG>-NAME1,:<FS_MSEG>-CPUTM)
   ENDEXEC.
  ENDLOOP.

  IF SY-SUBRC EQ 0. " call SP to merge
    CLEAR: V_CX_MSG.
    TRY.
        EXEC SQL.
          EXECUTE PROCEDURE [DBO].[SP_MERGE_ZPP016]
        ENDEXEC.
      CATCH CX_ROOT INTO O_CX.
        V_CX_MSG = O_CX->GET_TEXT( ).
        MESSAGE 'Failed to merge data' TYPE 'S' DISPLAY LIKE 'E'.
        LEAVE LIST-PROCESSING.
    ENDTRY.
  ENDIF.

  MESSAGE 'Penyimpanan Data ke SQL sukses!!!' TYPE 'I'.
ENDFORM.                    " WRITE_DATA