*&---------------------------------------------------------------------*
*& Include ZPPR_SLITTING_REKAP_PC_V2_TOP                     Report ZPPR_SLITTING_REKAP_PC_V2
*&
*&---------------------------------------------------------------------*

REPORT   ZPPR_SLITTING_REKAP_PC_V2.

TABLES: MARA, MCHB, MSEG, CAWN, VBPA.

TYPES : BEGIN OF TYPE_CHAR,
          ATWRT LIKE CAWN-ATWRT,
          ATWTB LIKE CAWNT-ATWTB,
        END OF TYPE_CHAR.

TYPES : BEGIN OF TY_MSEG,
          BOX    TYPE  CHAR1,
          MBLNR  LIKE  MSEG-MBLNR,
          MJAHR  LIKE  MSEG-MJAHR,
          ZEILE  LIKE  MSEG-ZEILE,
          SMBLN  LIKE  MSEG-SMBLN,
          SMBLP  LIKE  MSEG-SMBLP,
          BWART  LIKE  MSEG-BWART,
          MATNR  LIKE  MARA-MATNR,
          CHARG  LIKE  MSEG-CHARG,
          WERKS  LIKE  MSEG-WERKS,
          LGORT  LIKE  MSEG-LGORT,
          MENGE  LIKE  MSEG-MENGE,
          MEINS  LIKE  MSEG-MEINS,
          COMB   LIKE  AFPO-AUFNR, "Additional combine order 11 January 2013
          AUFNR  LIKE  MSEG-AUFNR,
          AUART  LIKE  AUFK-AUART, "Additional Order Type 8 January 2013
          VBELN  LIKE  MSEG-KDAUF,
          POSNR  LIKE  MSEG-KDPOS,
          ABLAD  LIKE  MSEG-ABLAD, " Unloading Point => LENGTH/GRADE/CRITERIA
          BUDAT  LIKE  MSEG-BUDAT_MKPF, " Posting Date
          CPUTM  LIKE  MKPF-CPUTM, " Time Entry
          ARBPL  LIKE  CRHD-ARBPL, " Resource
          ZZCODE LIKE  CAWN-ATWRT, " Characteristic ZZCODE
          NOROLL LIKE  CAWN-ATWRT, " Characteristic ZZNOMORROLL
          WIDTH  LIKE  CAWN-ATWRT, " Characteristic ZZWIDTH
          WIDTH2 TYPE  P LENGTH 15, " Characteristic ZZWIDTH
          LENGTH LIKE  CAWN-ATWRT, " Characteristic ZZLENGTH
          GRADE  LIKE  CAWN-ATWRT, " Characteristic ZZGRADE
          GRADETXT  LIKE  CAWNT-ATWTB, " Description Characteristic ZZGRADE
          CRIT   LIKE  CAWN-ATWRT, " Characteristic ZZCRITERIA
          LINE   LIKE  CAWN-ATWRT, " Characteristic ZZPRODLINE
          LINECD LIKE  CAWN-ATWRT, " Characteristic ZZPRODLINE Code
          TREAT  LIKE  CAWN-ATWRT, " Characteristic ZZTREATMENT
          PCKNG  LIKE  CAWN-ATWRT, " Characteristic ZZPACKING
          ZCONV TYPE P DECIMALS 2,  "LIKE  cawn-atwrt, " Characteristic ZZCONVERSIONROLLKG
          ZEXTRA TYPE P DECIMALS 2,  "LIKE  cawn-atwrt, " Extra Length
          CUOBJ_BM TYPE MCH1-CUOBJ_BM, "Object
          V_LASTGRADE LIKE  CAWN-ATWRT, "last grade
          V_LASTGRADETXT LIKE  CAWNT-ATWTB, "last grade description
          V_LASTCRIT  LIKE  CAWN-ATWRT, "last criteria grade
          V_LASTQTY TYPE P DECIMALS 3, "last qty

          "Add Sales Order by Afir 04.05.2020
          SHKZG LIKE MSEG-SHKZG,      "D/C
          XAUTO LIKE MSEG-XAUTO,      "Auto Created
          KDAUF2 LIKE MSEG-MAT_KDAUF, "Sales Order
          KDPOS2 LIKE MSEG-MAT_KDPOS, "SO item
          KUNNR  LIKE VBAK-KUNNR,     "Customer
          NAME1  LIKE KNA1-NAME1,     "Cust.Description
          "Add Sales Order by Afir 04.05.2020
          ZZCORETYPE LIKE  CAWN-ATWRT, " Characteristic ZZCORETYPE (Additional 19 October 2023)

          " Start Add 22.09.2025 by Fiqih
          ZZTAILORED TYPE CAWN-ATWRT,
          ZZLABEL TYPE CAWN-ATWRT,
          ZTYBGRADE TYPE CAWN-ATWRT, " Characteristic Grade Toyobon
          ZZNOROLLTOYOBO TYPE CAWN-ATWRT,
          ZZNOLOTTOYOBO TYPE CAWN-ATWRT,
          ZZALIAS TYPE CAWN-ATWRT, " Characteristic Alias

          NCHARG TYPE ZBATCHISTORY-NCHARG,       "Final Batch
          NOROLL2 TYPE ZBATCHISTORY-NOROLL2,     "Final Nomor Roll
          GRADE2 TYPE ZBATCHISTORY-GRADE2,       "Final Grade
          DCRITB TYPE ZBATCHISTORY-DCRITB,       "Final Criteria Grade
          NWEIGHT TYPE ZBATCHISTORY-NWEIGHT,     "Final Quantity
          " End Add 22.09.2025 by Fiqih
          NWEIGHT_A TYPE P DECIMALS 3,           "Final Quantity Actual
        END OF TY_MSEG.

TYPES : BEGIN OF TY_CRIT,
          LINE   LIKE  CAWN-ATWRT,
          ZZCODE LIKE  CAWN-ATWRT,
          GRADE  LIKE  CAWN-ATWRT,
          MENGE  LIKE  MSEG-MENGE,
          MEINS  LIKE  MSEG-MEINS,
        END OF TY_CRIT.

TYPES : BEGIN OF TY_SHIFT,
          LINE   LIKE  CAWN-ATWRT,
          MATNR  TYPE  CHAR10,
          ZZCODE LIKE  CAWN-ATWRT,
          CRIT   LIKE  CAWN-ATWRT,
          GRADE  LIKE  CAWN-ATWRT,
          LENGTH LIKE  CAWN-ATWRT, " Characteristic ZZLENGTH
          WIDTH  LIKE  CAWN-ATWRT, " Characteristic ZZWIDTH
          MENG1  LIKE  MSEG-MENGE,
          ROLL1  TYPE  P,
          MENG2  LIKE  MSEG-MENGE,
          ROLL2  TYPE  P,
          MENG3  LIKE  MSEG-MENGE,
          ROLL3  TYPE  P,
          TOTAL  LIKE  MSEG-MENGE,
          TROLL  TYPE  P,
          ARBPL  LIKE  CRHD-ARBPL,
        END OF TY_SHIFT.

TYPES : BEGIN OF TY_SALE,
          BOX    TYPE  CHAR1,
          VBELN  LIKE  MSEG-KDAUF,
          POSNR  LIKE  MSEG-KDPOS,
          ZZCODE LIKE  CAWN-ATWRT,"thick  LIKE  ausp-atwrt,
          WIDTH  LIKE  AUSP-ATWRT,
          LENGTH LIKE  AUSP-ATWRT,
          TREAT  LIKE  AUSP-ATWRT,
          KWMENG LIKE  VBAP-KWMENG,
          VRKME  LIKE  VBAP-VRKME,
          ZNAME  LIKE  PA0001-ENAME,
          NAME1  LIKE  KNA1-NAME1,
          NAME2  LIKE  KNA1-NAME2,
          ZCONV  LIKE  MSEG-MENGE,  "ausp-atwrt,
          PCONV  LIKE  AUSP-ATFLV,
          LINE   LIKE  AUSP-ATWRT,
          END OF TY_SALE.

TYPES : BEGIN OF TY_MSKA,
          MATNR  LIKE  MSEG-MATNR,
          CHARG  LIKE  MSEG-CHARG,
          VBELN  LIKE  MSEG-KDAUF,
          POSNR  LIKE  MSEG-KDPOS,
          WERKS  LIKE  MSKA-WERKS,
          LGORT  LIKE  MSKA-LGORT,
          KALAB  LIKE  MSKA-KALAB,
          KASPE  LIKE  MSKA-KASPE,
        END OF TY_MSKA.

DATA : BEGIN OF TY_STOCK,
        MATNR LIKE MSKU-MATNR,
        WERKS LIKE MSKU-WERKS,
        CHARG LIKE MSKU-CHARG,
        LGORT LIKE MSKA-LGORT,
        LABST TYPE P DECIMALS 3,
        INSME TYPE P DECIMALS 3,
        SPEME TYPE P DECIMALS 3,
        EINME TYPE P DECIMALS 3,
      END OF TY_STOCK.

RANGES: V_AUART FOR AUFK-AUART,
        V_AUARTSL FOR AUFK-AUART,    "ADDED BY FATHIR ON 28.05.2020 - Order Type Slitting
        V_AUARTTR FOR AUFK-AUART.    "ADDED BY FATHIR ON 28.05.2020 - Order Type Transfer MTM

DATA: V_ATINN LIKE CAWNT-ATINN,
      V_ATZHL LIKE CAWN-ATZHL,
      RIBUAN  TYPE C,
      PULUHAN TYPE C,
      V_AUFPL LIKE AFKO-AUFPL,
      V_ARBID LIKE AFVC-ARBID,
      V_ROLL1 TYPE I,
      V_ROLL2 TYPE I,
      V_ROLL3 TYPE I.

DATA: V_LINE   TYPE STANDARD TABLE OF TYPE_CHAR WITH HEADER LINE,
      IT_MSEG  TYPE STANDARD TABLE OF TY_MSEG,
      IT_MSEG2 TYPE STANDARD TABLE OF TY_MSEG,
      IT_MSEG3 TYPE STANDARD TABLE OF TY_MSEG,
      IT_CRIT  TYPE STANDARD TABLE OF TY_CRIT  WITH HEADER LINE,
      IT_SHIFT TYPE STANDARD TABLE OF TY_SHIFT WITH HEADER LINE,
      IT_SALE  TYPE STANDARD TABLE OF TY_SALE  WITH HEADER LINE,
      IT_DATS  TYPE STANDARD TABLE OF TY_MSEG  WITH HEADER LINE,
      IT_DATT  TYPE STANDARD TABLE OF TY_MSEG  WITH HEADER LINE,
      IT_MSKA  TYPE STANDARD TABLE OF TY_MSKA  WITH HEADER LINE,",
      IT_STOCK LIKE TY_STOCK OCCURS 0 WITH HEADER LINE,
      IT_STOCK_FINAL LIKE TY_STOCK OCCURS 0 WITH HEADER LINE.
*      CHAR_OF_BATCH LIKE CLBATCH OCCURS 0 WITH HEADER LINE.

DATA: IT_CABN         LIKE CABN OCCURS 0 WITH HEADER LINE,
      IT_ZBATCHISTORY LIKE ZBATCHISTORY OCCURS 0 WITH HEADER LINE.

DATA: V_ZZNOMORROLL        TYPE ATINN,
      V_ZZWIDTH            TYPE ATINN,
      V_ZZCONVERSIONROLLKG TYPE ATINN,
      V_ZZEXLENGTH         TYPE ATINN,
      V_ZZCORETYPE         TYPE ATINN,
      V_ZZTAILORED         TYPE ATINN,
      V_ZZLABEL            TYPE ATINN,
      V_ZZNOROLLTOYOBO     TYPE ATINN,
      V_ZZNOLOTTOYOBO      TYPE ATINN,
      V_ZZCODE             TYPE ATINN,
      V_ZZPRODLINE         TYPE ATINN,
      V_ZZTREATMENT        TYPE ATINN,
      V_ZZPACKING          TYPE ATINN,
      V_ZZCRITERIA         TYPE ATINN,
      V_ZZGRADE            TYPE ATINN,
      V_ZZALIAS            TYPE ATINN.

DATA: BEGIN OF CHAR_OF_BATCH OCCURS 0,

        CHARG TYPE CHARG_D,
        ATNAM TYPE ATNAM,
        ATINN TYPE ATINN,
        ATWRT TYPE ATWRT,
        ATWTB TYPE ATWTB,
        ATFLV TYPE ATFLV,

      END OF CHAR_OF_BATCH.

DATA: BEGIN OF CHAR_OF_BATCH_NEW OCCURS 0,

        CHARG TYPE CHARG_D,
        ATNAM TYPE ATNAM,
        ATINN TYPE ATINN,
        ATWRT TYPE ATWRT,
        ATWTB TYPE ATWTB,
        ATFLV TYPE ATFLV,

      END OF CHAR_OF_BATCH_NEW.

DATA: CHAR_OF_BATCH_DESC    LIKE CHAR_OF_BATCH OCCURS 0 WITH HEADER LINE.
DATA: CHAR_OF_LABEL         LIKE CHAR_OF_BATCH OCCURS 0 WITH HEADER LINE.

DATA: V_CUOBJ TYPE CUOBJ_BM,
      V_QTY TYPE P DECIMALS 3,
      V_MATNR TYPE MATNR,
      V_WERKS TYPE WERKS_D.

" Start Add 22.09.2025 by Fiqih
DATA: VX_ATNROL       LIKE CABN-ATINN,
      VX_ATNUOM       LIKE CABN-ATINN,
      VX_ROLNO        LIKE AUSP-ATWRT,
      VX_UOM          LIKE AUSP-ATWRT,
      VX_MATNR_JR     LIKE MCH1-MATNR,
      VX_CHARG_JR     LIKE MCH1-CHARG,
      VX_MSG(50),
      V_GRD(2).
" End Add 22.09.2025 by Fiqih

" Start Add 22.09.2025 by Fiqih
DATA: ITAB LIKE ZLABEL_TYB_WIN OCCURS 0 WITH HEADER LINE.
" End Add 22.09.2025 by Fiqih


DATA: WA_DATS  TYPE TY_MSEG.

FIELD-SYMBOLS: <FS_MSEG>  LIKE LINE OF IT_MSEG,
               <FS_MSEG2> LIKE LINE OF IT_MSEG,
               <FS_MSEG3> LIKE LINE OF IT_MSEG,
               <FS_CRIT>  LIKE LINE OF IT_CRIT,
*               <FS_CHAR_OF_BATCH> TYPE CLBATCH.
               <FS_CHAR_OF_BATCH> LIKE LINE OF CHAR_OF_BATCH,
               <FS_CHAR_OF_BATCH_NEW> LIKE LINE OF CHAR_OF_BATCH_NEW.

RANGES: R_AUART FOR AUFK-AUART. "Additional Order Type 8 January 2013

"ADDED BY FATHIR ON 28.05.2020
" variable range, fine tuning
RANGES: R_AUFNR FOR AUFK-AUFNR,
        R_DATE FOR MKPF-BUDAT,
        R_MATNO FOR MARA-MATNR,
        R_CHARG FOR MCH1-CHARG.

"ADDED BY FATHIR ON 04.06.2020
" ITAB untuk menampung Batch GRN 101
DATA: IT_CHARG TYPE STANDARD TABLE OF TY_MSEG WITH HEADER LINE.

*****************
* SELECTION AREA
*****************
SELECTION-SCREEN BEGIN OF BLOCK 1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: MATNR  FOR  MARA-MATNR,
                WERKS  FOR  MCHB-WERKS,
                MATKL  FOR  MARA-MATKL.
*  SELECT-OPTIONS: budat  FOR  mseg-budat_mkpf OBLIGATORY NO INTERVALS NO-EXTENSION. " Permintaan user,jangan input single (7 Januari 2013)
SELECT-OPTIONS: BUDAT  FOR  MSEG-BUDAT_MKPF OBLIGATORY NO-EXTENSION.
SELECTION-SCREEN SKIP.
SELECT-OPTIONS: ZLINE  FOR  CAWN-ATWRT NO INTERVALS,
                ZCHARG FOR  MSEG-CHARG NO INTERVALS.
SELECTION-SCREEN END OF BLOCK 1.

SELECTION-SCREEN BEGIN OF BLOCK 4 WITH FRAME TITLE TEXT-004.
PARAMETER: V_SCON AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK 4.

SELECTION-SCREEN BEGIN OF BLOCK 2 WITH FRAME TITLE TEXT-002.
PARAMETER: V_RB1 RADIOBUTTON GROUP RB.
PARAMETER: V_RB2 RADIOBUTTON GROUP RB.
SELECTION-SCREEN END OF BLOCK 2.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_CRIT' ITSELF
CONTROLS: TC_CRIT TYPE TABLEVIEW USING SCREEN 0100.

*&SPWIZARD: LINES OF TABLECONTROL 'TC_CRIT'
DATA:     G_TC_CRIT_LINES  LIKE SY-LOOPC.

DATA:     OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_SHIFT' ITSELF
CONTROLS: TC_SHIFT TYPE TABLEVIEW USING SCREEN 0200.

*&SPWIZARD: LINES OF TABLECONTROL 'TC_SHIFT'
DATA:     G_TC_SHIFT_LINES  LIKE SY-LOOPC.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_SALES' ITSELF
CONTROLS: TC_SALES TYPE TABLEVIEW USING SCREEN 0300.

*&SPWIZARD: LINES OF TABLECONTROL 'TC_SALES'
DATA:     G_TC_SALES_LINES  LIKE SY-LOOPC.