import path from 'node:path';
import { pathToFileURL } from 'node:url';

const userProfile = process.env.USERPROFILE || 'C:\\Users\\User';
const registryPath = path.join(
  userProfile,
  'Documents',
  'Claude',
  'MCP SAP',
  'sap-leader-mcp',
  'src',
  'tool-registry.js'
);

const reg = await import(pathToFileURL(registryPath).href);
const setActiveServer = reg.HANDLERS['set_active_server'];
const callFunction = reg.HANDLERS['call_function'];
await setActiveServer({ server_ref: 'sandbox-new' });

const prog = [
  { LINE: 'REPORT ZTMP_DEBUG_PIPE.' },
  { LINE: 'TYPES: BEGIN OF ty_mov,' },
  { LINE: '         mblnr TYPE mseg-mblnr,' },
  { LINE: '         mjahr TYPE mseg-mjahr,' },
  { LINE: '         zeile TYPE mseg-zeile,' },
  { LINE: '         bwart TYPE mseg-bwart,' },
  { LINE: '         matnr TYPE mseg-matnr,' },
  { LINE: '         werks TYPE mseg-werks,' },
  { LINE: '         charg TYPE mseg-charg,' },
  { LINE: '         menge TYPE mseg-menge,' },
  { LINE: '         meins TYPE mseg-meins,' },
  { LINE: '         aufnr TYPE mseg-aufnr,' },
  { LINE: '         smbln TYPE mseg-smbln,' },
  { LINE: '         sjahr TYPE mseg-sjahr,' },
  { LINE: '         smblp TYPE mseg-smblp,' },
  { LINE: '         budat TYPE mkpf-budat,' },
  { LINE: '         bktxt TYPE mkpf-bktxt,' },
  { LINE: '       END OF ty_mov.' },
  { LINE: 'TYPES: BEGIN OF ty_out,' },
  { LINE: '         werks       TYPE mseg-werks,' },
  { LINE: '         prodline    TYPE char20,' },
  { LINE: '         line_raw    TYPE ausp-atwrt,' },
  { LINE: '         jr_number   TYPE ausp-atwrt,' },
  { LINE: '         matnr       TYPE mseg-matnr,' },
  { LINE: '         maktx       TYPE makt-maktx,' },
  { LINE: '         gr_date     TYPE mkpf-budat,' },
  { LINE: '         aufnr       TYPE mseg-aufnr,' },
  { LINE: '         charg       TYPE mseg-charg,' },
  { LINE: '         qty_gr      TYPE mseg-menge,' },
  { LINE: '         qty_gi      TYPE p DECIMALS 3,' },
  { LINE: '         qty_diff    TYPE p DECIMALS 3,' },
  { LINE: '         meins       TYPE mseg-meins,' },
  { LINE: '         auart       TYPE aufk-auart,' },
  { LINE: '         bktxt       TYPE mkpf-bktxt,' },
  { LINE: '         cnt_261     TYPE i,' },
  { LINE: '         trace_stat  TYPE char20,' },
  { LINE: '       END OF ty_out.' },
  { LINE: 'DATA: gt_gr TYPE STANDARD TABLE OF ty_mov,' },
  { LINE: '      gt_gimov TYPE STANDARD TABLE OF ty_mov,' },
  { LINE: '      lt_mov_storno TYPE STANDARD TABLE OF ty_mov,' },
  { LINE: '      ls_mov TYPE ty_mov, ls_storno TYPE ty_mov,' },
  { LINE: '      gt_out TYPE SORTED TABLE OF ty_out' },
  { LINE: '             WITH UNIQUE KEY werks matnr charg aufnr,' },
  { LINE: '      ls_out TYPE ty_out,' },
  { LINE: '      c_gr TYPE i, c_gr_post TYPE i, c_out TYPE i,' },
  { LINE: '      c_gi TYPE i, c_no261 TYPE i, c_diff TYPE i, c_less TYPE i.' },
  { LINE: 'SELECT a~mblnr a~mjahr a~zeile a~bwart a~matnr a~werks' },
  { LINE: '       a~charg a~menge a~meins a~aufnr a~smbln a~sjahr' },
  { LINE: '       a~smblp b~budat b~bktxt' },
  { LINE: '  INTO CORRESPONDING FIELDS OF TABLE gt_gr' },
  { LINE: '  FROM mkpf AS b INNER JOIN mseg AS a' },
  { LINE: '    ON a~mblnr = b~mblnr AND a~mjahr = b~mjahr' },
  { LINE: " WHERE b~budat BETWEEN '20240101' AND '20241231'" },
  { LINE: "   AND a~werks = '2000'" },
  { LINE: "   AND ( a~bwart = '101' OR a~bwart = '102' OR" },
  { LINE: "         a~bwart = '531' OR a~bwart = '532' )" },
  { LINE: '   AND a~charg NE space.' },
  { LINE: 'DESCRIBE TABLE gt_gr LINES c_gr.' },
  { LINE: "WRITE: / '1. GR raw 2024:', c_gr." },
  { LINE: 'lt_mov_storno[] = gt_gr[].' },
  { LINE: 'DELETE lt_mov_storno WHERE smbln IS INITIAL.' },
  { LINE: 'LOOP AT lt_mov_storno INTO ls_mov.' },
  { LINE: '  DELETE gt_gr WHERE mblnr = ls_mov-smbln' },
  { LINE: '                 AND mjahr = ls_mov-sjahr' },
  { LINE: '                 AND zeile = ls_mov-smblp.' },
  { LINE: 'ENDLOOP.' },
  { LINE: 'DELETE gt_gr WHERE smbln IS NOT INITIAL' },
  { LINE: "                OR bwart = '102' OR bwart = '532'." },
  { LINE: 'DESCRIBE TABLE gt_gr LINES c_gr_post.' },
  { LINE: "WRITE: / '2. GR after local storno:', c_gr_post." },
  { LINE: 'IF gt_gr IS NOT INITIAL.' },
  { LINE: '  REFRESH lt_mov_storno.' },
  { LINE: '  SELECT mblnr mjahr zeile smbln sjahr smblp bwart' },
  { LINE: '    INTO CORRESPONDING FIELDS OF TABLE lt_mov_storno' },
  { LINE: '    FROM mseg' },
  { LINE: '    FOR ALL ENTRIES IN gt_gr' },
  { LINE: '   WHERE smbln = gt_gr-mblnr' },
  { LINE: '     AND sjahr = gt_gr-mjahr' },
  { LINE: '     AND smblp = gt_gr-zeile' },
  { LINE: "     AND ( bwart = '102' OR bwart = '532' )." },
  { LINE: '  LOOP AT lt_mov_storno INTO ls_storno.' },
  { LINE: '    DELETE gt_gr WHERE mblnr = ls_storno-smbln' },
  { LINE: '                   AND mjahr = ls_storno-sjahr' },
  { LINE: '                   AND zeile = ls_storno-smblp.' },
  { LINE: '  ENDLOOP.' },
  { LINE: 'ENDIF.' },
  { LINE: 'DESCRIBE TABLE gt_gr LINES c_gr_post.' },
  { LINE: "WRITE: / '3. GR after cross storno:', c_gr_post." },
  { LINE: 'LOOP AT gt_gr INTO ls_mov.' },
  { LINE: '  READ TABLE gt_out INTO ls_out' },
  { LINE: '    WITH TABLE KEY werks = ls_mov-werks matnr = ls_mov-matnr' },
  { LINE: '                   charg = ls_mov-charg aufnr = ls_mov-aufnr.' },
  { LINE: '  IF sy-subrc <> 0.' },
  { LINE: '    CLEAR ls_out.' },
  { LINE: '    ls_out-werks = ls_mov-werks. ls_out-matnr = ls_mov-matnr.' },
  { LINE: '    ls_out-charg = ls_mov-charg. ls_out-aufnr = ls_mov-aufnr.' },
  { LINE: '    ls_out-bktxt = ls_mov-bktxt. ls_out-meins = ls_mov-meins.' },
  { LINE: '    ls_out-gr_date = ls_mov-budat.' },
  { LINE: '    ls_out-qty_gr = ls_mov-menge.' },
  { LINE: '    INSERT ls_out INTO TABLE gt_out.' },
  { LINE: '  ELSE.' },
  { LINE: '    ls_out-qty_gr = ls_out-qty_gr + ls_mov-menge.' },
  { LINE: '    IF ls_out-gr_date IS INITIAL OR ls_mov-budat < ls_out-gr_date.' },
  { LINE: '      ls_out-gr_date = ls_mov-budat.' },
  { LINE: '    ENDIF.' },
  { LINE: '    MODIFY TABLE gt_out FROM ls_out.' },
  { LINE: '  ENDIF.' },
  { LINE: 'ENDLOOP.' },
  { LINE: 'DELETE gt_out WHERE qty_gr <= 0.' },
  { LINE: 'DESCRIBE TABLE gt_out LINES c_out.' },
  { LINE: "WRITE: / '4. gt_out count (unique batch/order):', c_out." },
  { LINE: 'IF gt_out IS NOT INITIAL.' },
  { LINE: '  SELECT a~mblnr a~mjahr a~zeile a~bwart a~matnr a~werks' },
  { LINE: '         a~charg a~menge a~meins a~aufnr a~smbln a~sjahr' },
  { LINE: '         a~smblp b~budat b~bktxt' },
  { LINE: '    INTO CORRESPONDING FIELDS OF TABLE gt_gimov' },
  { LINE: '    FROM mseg AS a INNER JOIN mkpf AS b' },
  { LINE: '      ON b~mblnr = a~mblnr AND b~mjahr = a~mjahr' },
  { LINE: '     FOR ALL ENTRIES IN gt_out' },
  { LINE: '   WHERE a~charg = gt_out-charg' },
  { LINE: "     AND ( a~bwart = '261' OR a~bwart = '262' OR" },
  { LINE: "           a~bwart = '901' OR a~bwart = '902' )." },
  { LINE: 'ENDIF.' },
  { LINE: 'DESCRIBE TABLE gt_gimov LINES c_gi.' },
  { LINE: "WRITE: / '5. gt_gimov raw count:', c_gi." },
  { LINE: 'LOOP AT gt_out INTO ls_out.' },
  { LINE: '  CLEAR: ls_out-qty_gi, ls_out-cnt_261.' },
  { LINE: '  LOOP AT gt_gimov INTO ls_mov WHERE charg = ls_out-charg.' },
  { LINE: '    ls_out-qty_gi = ls_out-qty_gi + ls_mov-menge.' },
  { LINE: '    ls_out-cnt_261 = ls_out-cnt_261 + 1.' },
  { LINE: '  ENDLOOP.' },
  { LINE: '  IF ls_out-cnt_261 = 0.' },
  { LINE: '    c_no261 = c_no261 + 1.' },
  { LINE: '  ELSE.' },
  { LINE: '    IF ls_out-qty_gr <> ls_out-qty_gi.' },
  { LINE: '      c_diff = c_diff + 1.' },
  { LINE: '    ENDIF.' },
  { LINE: '    IF ls_out-qty_gi < ls_out-qty_gr.' },
  { LINE: '      c_less = c_less + 1.' },
  { LINE: '    ENDIF.' },
  { LINE: '  ENDIF.' },
  { LINE: 'ENDLOOP.' },
  { LINE: "WRITE: / '6. Analysis: no261 =', c_no261." },
  { LINE: "WRITE: / '           diff  =', c_diff." },
  { LINE: "WRITE: / '           less  =', c_less." }
];

const res = await callFunction({
  function_name: 'RFC_ABAP_INSTALL_AND_RUN',
  parameters: {
    MODE: 'F',
    PROGRAM: prog
  }
});

console.log('Result:');
res.result?.WRITES?.forEach(w => console.log(w.ZEILE));
if (res.result?.ERRORMESSAGE) {
  console.log('Error:', res.result.ERRORMESSAGE);
}
