REPORT ZTMPAGG.
DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: N1 TYPE I, N2 TYPE I, N3 TYPE I, N4 TYPE I.
DATA: SK TYPE I.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE, W TYPE ABAPTXT255-LINE.
DATA: B1 TYPE ABAPTXT255-LINE, B2 TYPE ABAPTXT255-LINE.
DATA: B3 TYPE ABAPTXT255-LINE, B4 TYPE ABAPTXT255-LINE.

CLEAR B1.
B1(40) = '      LS_FIRST_CMICMIT = IT_ALV-CMICMIT.'.
CLEAR B2.
B2(38) = '      LV_SUM = LV_SUM + IT_ALV-MICMIT.'.
CLEAR B3.
B3(30) = '        IF LV_HAS_EMPTY = ''X''.'.
CLEAR B4.
B4(26) = '    IF LV_HAS_EMPTY = ''X''.'.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMR_COA'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED'.
  RETURN.
ENDIF.

LOOP AT LT_SRC.
  L = LT_SRC-LINE.
  IF SK > 0.
    SK = SK - 1.
    CONTINUE.
  ENDIF.
  IF L = B1.
    CLEAR W.
    W(46) = '      CLEAR: LS_FIRST_CMICMIT, LV_SUM, LV_COUN'.
    W+46(2) = 'T.'.
    PERFORM A USING W.
    CLEAR W.
    W(31) = '      IF IT_ALV-CMICMIT <> ''-''.'.
    PERFORM A USING W.
    CLEAR W.
    W(42) = '        LS_FIRST_CMICMIT = IT_ALV-CMICMIT.'.
    PERFORM A USING W.
    CLEAR W.
    W(31) = '        LV_SUM = IT_ALV-MICMIT.'.
    PERFORM A USING W.
    CLEAR W.
    W(21) = '        LV_COUNT = 1.'.
    PERFORM A USING W.
    CLEAR W.
    W(12) = '      ENDIF.'.
    PERFORM A USING W.
    SK = 7.
    N1 = N1 + 1.
    CONTINUE.
  ENDIF.
  IF L = B2.
    CLEAR W.
    W(31) = '      IF IT_ALV-CMICMIT <> ''-''.'.
    PERFORM A USING W.
    CLEAR W.
    W(40) = '        LV_SUM = LV_SUM + IT_ALV-MICMIT.'.
    PERFORM A USING W.
    CLEAR W.
    W(32) = '        LV_COUNT = LV_COUNT + 1.'.
    PERFORM A USING W.
    CLEAR W.
    W(39) = '        IF LS_FIRST_CMICMIT IS INITIAL.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '          LS_FIRST_CMICMIT = IT_ALV-CMICMIT.'.
    PERFORM A USING W.
    CLEAR W.
    W(14) = '        ENDIF.'.
    PERFORM A USING W.
    CLEAR W.
    W(12) = '      ENDIF.'.
    PERFORM A USING W.
    SK = 4.
    N2 = N2 + 1.
    CONTINUE.
  ENDIF.
  IF L = B3.
    CLEAR W.
    W(24) = '        IF LV_COUNT = 0.'.
    PERFORM A USING W.
    N3 = N3 + 1.
    CONTINUE.
  ENDIF.
  IF L = B4.
    CLEAR W.
    W(20) = '    IF LV_COUNT = 0.'.
    PERFORM A USING W.
    N4 = N4 + 1.
    CONTINUE.
  ENDIF.
  PERFORM A USING L.
ENDLOOP.

IF N1 <> 1 OR N2 <> 1 OR N3 <> 1 OR N4 <> 1.
  WRITE: / 'ABORT-ANCHOR MISMATCH'.
  WRITE: / N1, N2, N3, N4.
  RETURN.
ENDIF.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMR_COA'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.
DESCRIBE TABLE LT_OUT LINES N1.
WRITE: / 'SUCCESS=', LV_OK, ' LINES=', N1.
WRITE: / 'MSG=', LV_MSG.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.