REPORT ZTMPDECA.
DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: N1 TYPE I, N2 TYPE I.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE, W TYPE ABAPTXT255-LINE.
DATA: X1 TYPE ABAPTXT255-LINE.

CLEAR X1.
X1(37) = '  MOVE ''Program Information'' TO INFO.'.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMI_COA_F01'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED'.
  RETURN.
ENDIF.

LOOP AT LT_SRC.
  L = LT_SRC-LINE.
  IF L CS 'FORM MICFMT'.
    N2 = N2 + 1.
  ENDIF.
  PERFORM A USING L.
  IF L = X1.
    CLEAR W.
    PERFORM A USING W.
    CLEAR W.
    W(46) = '* Cache format MIC dari master QPMK: decimal p'.
    W+46(31) = 'laces (STELLEN) + unit, per MIC'.
    PERFORM A USING W.
    CLEAR W.
    W(46) = '* dan per plant. Dibaca sekali per kombinasi l'.
    W+46(25) = 'alu dilayani dari memori.'.
    PERFORM A USING W.
    CLEAR W.
    W(46) = '* Dinamis penuh - MIC baru otomatis ikut tanpa'.
    W+46(17) = ' perlu ubah kode.'.
    PERFORM A USING W.
    CLEAR W.
    W(26) = 'TYPES: BEGIN OF TY_MICFMT,'.
    PERFORM A USING W.
    CLEAR W.
    W(33) = '         MKMNR   TYPE QPMK-MKMNR,'.
    PERFORM A USING W.
    CLEAR W.
    W(33) = '         WERKS   TYPE QPMK-WERKS,'.
    PERFORM A USING W.
    CLEAR W.
    W(35) = '         STELLEN TYPE QPMK-STELLEN,'.
    PERFORM A USING W.
    CLEAR W.
    W(38) = '         UOM     TYPE QPMK-MASSEINHSW,'.
    PERFORM A USING W.
    CLEAR W.
    W(24) = '       END OF TY_MICFMT.'.
    PERFORM A USING W.
    CLEAR W.
    W(40) = 'DATA: GT_MICFMT TYPE TABLE OF TY_MICFMT,'.
    PERFORM A USING W.
    CLEAR W.
    W(31) = '      GS_MICFMT TYPE TY_MICFMT.'.
    PERFORM A USING W.
    CLEAR W.
    W(20) = 'DATA: GV_DEC TYPE I,'.
    PERFORM A USING W.
    CLEAR W.
    W(34) = '      GV_UOM TYPE QPMK-MASSEINHSW.'.
    PERFORM A USING W.
    N1 = N1 + 1.
  ENDIF.
ENDLOOP.

IF N1 <> 1 OR N2 <> 0.
  WRITE: / 'ABORT N1=', N1, ' N2=', N2.
  RETURN.
ENDIF.
CLEAR W.
PERFORM A USING W.
CLEAR W.
W(46) = '*&--------------------------------------------'.
W+46(25) = '------------------------*'.
PERFORM A USING W.
CLEAR W.
W(20) = '*&      Form  MICFMT'.
PERFORM A USING W.
CLEAR W.
W(46) = '*&--------------------------------------------'.
W+46(25) = '------------------------*'.
PERFORM A USING W.
CLEAR W.
W(46) = '* Fix (user 18/07/2026): sebelumnya semua WRIT'.
W+46(27) = 'E meng-hardcode DECIMALS 3,'.
PERFORM A USING W.
CLEAR W.
W(46) = '* sehingga value tidak mengikuti master MIC (m'.
W+46(22) = 'is. SEWESTMZ STELLEN=0'.
PERFORM A USING W.
CLEAR W.
W(46) = '* seharusnya tampil 55, bukan 54.842). Form in'.
W+46(26) = 'i mengambil STELLEN + unit'.
PERFORM A USING W.
CLEAR W.
W(46) = '* dari QPMK per MIC dan per plant, hasilnya di'.
W+46(20) = '-cache di GT_MICFMT.'.
PERFORM A USING W.
CLEAR W.
W(29) = 'FORM MICFMT USING P_MIC P_WRK'.
PERFORM A USING W.
CLEAR W.
W(30) = '         CHANGING P_DEC TYPE I'.
PERFORM A USING W.
CLEAR W.
W(24) = '                  P_UOM.'.
PERFORM A USING W.
CLEAR W.
W(22) = '  CLEAR: P_DEC, P_UOM.'.
PERFORM A USING W.
CLEAR W.
W(22) = '  IF P_MIC IS INITIAL.'.
PERFORM A USING W.
CLEAR W.
W(11) = '    RETURN.'.
PERFORM A USING W.
CLEAR W.
W(8) = '  ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(37) = '  READ TABLE GT_MICFMT INTO GS_MICFMT'.
PERFORM A USING W.
CLEAR W.
W(41) = '    WITH KEY MKMNR = P_MIC WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(19) = '  IF SY-SUBRC <> 0.'.
PERFORM A USING W.
CLEAR W.
W(20) = '    CLEAR GS_MICFMT.'.
PERFORM A USING W.
CLEAR W.
W(28) = '    GS_MICFMT-MKMNR = P_MIC.'.
PERFORM A USING W.
CLEAR W.
W(28) = '    GS_MICFMT-WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(36) = '    SELECT SINGLE STELLEN MASSEINHSW'.
PERFORM A USING W.
CLEAR W.
W(45) = '      INTO (GS_MICFMT-STELLEN, GS_MICFMT-UOM)'.
PERFORM A USING W.
CLEAR W.
W(15) = '      FROM QPMK'.
PERFORM A USING W.
CLEAR W.
W(25) = '      WHERE MKMNR = P_MIC'.
PERFORM A USING W.
CLEAR W.
W(26) = '        AND WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(21) = '    IF SY-SUBRC <> 0.'.
PERFORM A USING W.
CLEAR W.
W(46) = '      " Master belum ada di plant ini - pakai '.
W+46(30) = 'baris manapun sebagai cadangan'.
PERFORM A USING W.
CLEAR W.
W(38) = '      SELECT SINGLE STELLEN MASSEINHSW'.
PERFORM A USING W.
CLEAR W.
W(46) = '        INTO (GS_MICFMT-STELLEN, GS_MICFMT-UOM'.
W+46(1) = ')'.
PERFORM A USING W.
CLEAR W.
W(17) = '        FROM QPMK'.
PERFORM A USING W.
CLEAR W.
W(28) = '        WHERE MKMNR = P_MIC.'.
PERFORM A USING W.
CLEAR W.
W(10) = '    ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(34) = '    APPEND GS_MICFMT TO GT_MICFMT.'.
PERFORM A USING W.
CLEAR W.
W(8) = '  ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(28) = '  P_DEC = GS_MICFMT-STELLEN.'.
PERFORM A USING W.
CLEAR W.
W(24) = '  P_UOM = GS_MICFMT-UOM.'.
PERFORM A USING W.
CLEAR W.
W(8) = 'ENDFORM.'.
PERFORM A USING W.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMI_COA_F01'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.
DESCRIBE TABLE LT_OUT LINES N1.
WRITE: / 'SUCCESS=', LV_OK, ' LINES=', N1.
WRITE: / 'MSG=', LV_MSG.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.