REPORT ZTMPDECB.
DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: N1 TYPE I, N2 TYPE I, N3 TYPE I, N4 TYPE I.
DATA: N5 TYPE I, N6 TYPE I, N7 TYPE I, E TYPE I.
DATA: SK TYPE I, IDX TYPE I, J TYPE I.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE, W TYPE ABAPTXT255-LINE.
DATA: A1 TYPE ABAPTXT255-LINE.
DATA: A2 TYPE ABAPTXT255-LINE.
DATA: A3 TYPE ABAPTXT255-LINE.
DATA: A4 TYPE ABAPTXT255-LINE.
DATA: A5 TYPE ABAPTXT255-LINE.
DATA: A6 TYPE ABAPTXT255-LINE.
DATA: A7 TYPE ABAPTXT255-LINE.
DATA: A8 TYPE ABAPTXT255-LINE.
DATA: A9 TYPE ABAPTXT255-LINE.

CLEAR A1.
A1(44) = '                WRITE LT_QASE-MESSWERT TO IT'.
A1+44(44) = '_MIC1-CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUS'.
A1+88(7) = 'TIFIED.'.
CLEAR A2.
A2(44) = '              WRITE LV_MITTEL TO IT_MIC1-CMI'.
A2+44(42) = 'CMIT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFIED.'.
CLEAR A3.
A3(44) = '              WRITE IT_MIC1-MICMIT TO IT_MIC'.
A3+44(44) = '1-CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFI'.
A3+88(3) = 'ED.'.
CLEAR A4.
A4(44) = '          WRITE IT_DATA_AVG-MICMIT TO IT_DAT'.
A4+44(44) = 'A_AVG-CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUS'.
A4+88(7) = 'TIFIED.'.
CLEAR A5.
A5(44) = '        WRITE IT_DATA_AVG-MICMIT TO IT_DATA_'.
A5+44(44) = 'AVG-CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUSTI'.
A5+88(5) = 'FIED.'.
CLEAR A6.
A6(44) = '        WRITE WA_ZLOG-VALUE1 TO IT_DATA-CMIC'.
A6+44(41) = 'MIT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFIED.'.
CLEAR A7.
A7(44) = '      SELECT SINGLE MASSEINHSW INTO IT_MIC1-'.
A7+44(3) = 'UOM'.
CLEAR A8.
A8(21) = '            FROM QPMK'.
CLEAR A9.
A9(38) = '            WHERE MKMNR = IT_MIC1-MIC.'.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMI_COA_F01'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED'.
  RETURN.
ENDIF.

LOOP AT LT_SRC.
  IDX = SY-TABIX.
  L = LT_SRC-LINE.
  IF SK > 0.
    SK = SK - 1.
    CONTINUE.
  ENDIF.
  IF L = A1.
    CLEAR W.
    W(44) = '                PERFORM MICFMT USING IT_MIC1'.
    W+44(17) = '-MIC IT_LOT-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                        CHANGING GV_DEC GV_U'.
    W+44(3) = 'OM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                WRITE LT_QASE-MESSWERT TO IT'.
    W+44(44) = '_MIC1-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEF'.
    W+88(12) = 'T-JUSTIFIED.'.
    PERFORM A USING W.
    N1 = N1 + 1.
    CONTINUE.
  ENDIF.
  IF L = A2.
    CLEAR W.
    W(44) = '              PERFORM MICFMT USING IT_MIC1-M'.
    W+44(15) = 'IC IT_LOT-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                      CHANGING GV_DEC GV_UOM'.
    W+44(1) = '.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '              WRITE LV_MITTEL TO IT_MIC1-CMI'.
    W+44(44) = 'CMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFI'.
    W+88(3) = 'ED.'.
    PERFORM A USING W.
    N2 = N2 + 1.
    CONTINUE.
  ENDIF.
  IF L = A3.
    CLEAR W.
    W(44) = '              PERFORM MICFMT USING IT_MIC1-M'.
    W+44(15) = 'IC IT_LOT-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                      CHANGING GV_DEC GV_UOM'.
    W+44(1) = '.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '              WRITE IT_MIC1-MICMIT TO IT_MIC'.
    W+44(44) = '1-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JU'.
    W+88(8) = 'STIFIED.'.
    PERFORM A USING W.
    N3 = N3 + 1.
    CONTINUE.
  ENDIF.
  IF L = A4.
    CLEAR W.
    W(44) = '          PERFORM MICFMT USING IT_DATA_AVG-M'.
    W+44(20) = 'IC IT_DATA_AVG-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(41) = '                  CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '          WRITE IT_DATA_AVG-MICMIT TO IT_DAT'.
    W+44(44) = 'A_AVG-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEF'.
    W+88(12) = 'T-JUSTIFIED.'.
    PERFORM A USING W.
    N4 = N4 + 1.
    CONTINUE.
  ENDIF.
  IF L = A5.
    CLEAR W.
    W(44) = '        PERFORM MICFMT USING IT_DATA_AVG-MIC'.
    W+44(18) = ' IT_DATA_AVG-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(39) = '                CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '        WRITE IT_DATA_AVG-MICMIT TO IT_DATA_'.
    W+44(44) = 'AVG-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-'.
    W+88(10) = 'JUSTIFIED.'.
    PERFORM A USING W.
    N5 = N5 + 1.
    CONTINUE.
  ENDIF.
  IF L = A6.
    CLEAR W.
    W(44) = '        PERFORM MICFMT USING IT_DATA-MIC IT_'.
    W+44(10) = 'DATA-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(39) = '                CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '        WRITE WA_ZLOG-VALUE1 TO IT_DATA-CMIC'.
    W+44(44) = 'MIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIE'.
    W+88(2) = 'D.'.
    PERFORM A USING W.
    N6 = N6 + 1.
    CONTINUE.
  ENDIF.
  IF L = A7.
    J = IDX + 1.
    READ TABLE LT_SRC INDEX J.
    IF LT_SRC-LINE <> A8.
      E = E + 1.
    ENDIF.
    J = IDX + 2.
    READ TABLE LT_SRC INDEX J.
    IF LT_SRC-LINE <> A9.
      E = E + 1.
    ENDIF.
    CLEAR W.
    W(44) = '      PERFORM MICFMT USING IT_MIC1-MIC IT_LO'.
    W+44(7) = 'T-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(37) = '              CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(27) = '      IT_MIC1-UOM = GV_UOM.'.
    PERFORM A USING W.
    SK = 2.
    N7 = N7 + 1.
    CONTINUE.
  ENDIF.
  PERFORM A USING L.
ENDLOOP.

IF N1 <> 1 OR N2 <> 1 OR N3 <> 1 OR N4 <> 1
   OR N5 <> 1 OR N6 <> 1 OR N7 <> 1 OR E <> 0.
  WRITE: / 'ABORT'.
  WRITE: / N1, N2, N3, N4, N5, N6, N7, E.
  RETURN.
ENDIF.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMI_COA_F01'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.
DESCRIBE TABLE LT_OUT LINES N1.
WRITE: / 'SUCCESS=', LV_OK, ' LINES=', N1.
WRITE: / 'MSG=', LV_MSG.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.