REPORT ZTMPPP.
DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: N1 TYPE I, N2 TYPE I, N3 TYPE I, N4 TYPE I.
DATA: N5 TYPE I, N6 TYPE I, NG TYPE I.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE, W TYPE ABAPTXT255-LINE.
DATA: B1 TYPE ABAPTXT255-LINE.
DATA: B2 TYPE ABAPTXT255-LINE.
DATA: B3 TYPE ABAPTXT255-LINE.
DATA: B4 TYPE ABAPTXT255-LINE.
DATA: B5 TYPE ABAPTXT255-LINE.
DATA: B6 TYPE ABAPTXT255-LINE.

CLEAR B1.
B1(37) = '         MICMIT TYPE QAMR-MITTELWERT,'.
CLEAR B2.
B2(35) = '      IT_ALV-MATNR = IT_DATA-MATNR.'.
CLEAR B3.
B3(42) = '        LS_FIRST_CMICMIT TYPE C LENGTH 20.'.
CLEAR B4.
B4(35) = '      LS_CUR_MIC   = IT_UNIQUE-MIC.'.
CLEAR B5.
B5(44) = '            PERFORM MICFMT USING LS_CUR_MIC '.
B5+44(5) = 'SPACE'.
CLEAR B6.
B6(44) = '        PERFORM MICFMT USING LS_CUR_MIC SPAC'.
B6+44(1) = 'E'.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMR_COA'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED'. RETURN.
ENDIF.

LOOP AT LT_SRC.
  L = LT_SRC-LINE.
  IF L CS 'LS_CUR_WERKS'. NG = NG + 1. ENDIF.
  IF L = B5.
    CLEAR W.
    W(44) = '            PERFORM MICFMT USING LS_CUR_MIC '.
    W+44(12) = 'LS_CUR_WERKS'.
    PERFORM A USING W.
    N5 = N5 + 1.
    CONTINUE.
  ENDIF.
  IF L = B6.
    CLEAR W.
    W(44) = '        PERFORM MICFMT USING LS_CUR_MIC LS_C'.
    W+44(8) = 'UR_WERKS'.
    PERFORM A USING W.
    N6 = N6 + 1.
    CONTINUE.
  ENDIF.
  PERFORM A USING L.
  IF L = B1.
    CLEAR W.
    W(31) = '         WERKS TYPE LIPS-WERKS,'.
    PERFORM A USING W.
    N1 = N1 + 1.
  ENDIF.
  IF L = B2.
    CLEAR W.
    W(35) = '      IT_ALV-WERKS = IT_DATA-WERKS.'.
    PERFORM A USING W.
    N2 = N2 + 1.
  ENDIF.
  IF L = B3.
    CLEAR W.
    W(37) = '  DATA: LS_CUR_WERKS LIKE LIPS-WERKS.'.
    PERFORM A USING W.
    N3 = N3 + 1.
  ENDIF.
  IF L = B4.
    CLEAR W.
    W(37) = '      LS_CUR_WERKS = IT_UNIQUE-WERKS.'.
    PERFORM A USING W.
    N4 = N4 + 1.
  ENDIF.
ENDLOOP.

IF NG <> 0 OR N1 <> 1 OR N2 <> 1 OR N3 <> 1
   OR N4 <> 1 OR N5 <> 1 OR N6 <> 1.
  WRITE: / 'ABORT'.
  WRITE: / NG, N1, N2, N3, N4, N5, N6.
  RETURN.
ENDIF.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMR_COA'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.
DESCRIBE TABLE LT_OUT LINES N1.
WRITE: / 'SUCCESS=', LV_OK, ' LINES=', N1.
WRITE: / 'MSG=', LV_MSG.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.