REPORT ZTMPRDEC.
DATA: LT_SRC TYPE TABLE OF ABAPTXT255 WITH HEADER LINE,
      LT_OUT TYPE TABLE OF ABAPTXT255 WITH HEADER LINE.
DATA: NR TYPE I, NF TYPE I.
DATA: N1 TYPE I, N2 TYPE I, N3 TYPE I, N4 TYPE I, N5 TYPE I.
DATA: LV_OK TYPE C, LV_MSG TYPE STRING.
DATA: L TYPE ABAPTXT255-LINE, W TYPE ABAPTXT255-LINE.
DATA: R0 TYPE ABAPTXT255-LINE.
DATA: A1 TYPE ABAPTXT255-LINE.
DATA: A2 TYPE ABAPTXT255-LINE.
DATA: A3 TYPE ABAPTXT255-LINE.
DATA: A4 TYPE ABAPTXT255-LINE.
DATA: A5 TYPE ABAPTXT255-LINE.

CLEAR R0.
R0(16) = 'REPORT ZQMR_COA.'.
CLEAR A1.
A1(44) = '                WRITE LT_QASE-MESSWERT TO IT'.
A1+44(44) = '_ALV-CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUST'.
A1+88(6) = 'IFIED.'.
CLEAR A2.
A2(44) = '              WRITE IT_MIC-MICMIT TO IT_ALV-'.
A2+44(44) = 'CMICMIT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFIED'.
A2+88(1) = '.'.
CLEAR A3.
A3(44) = '          WRITE LT_ZLOG-VALUE1 TO IT_ALV-CMI'.
A3+44(42) = 'CMIT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFIED.'.
CLEAR A4.
A4(44) = '            WRITE LV_AVG_NUM TO IT_AVG-CMICM'.
A4+44(40) = 'IT EXPONENT 0 DECIMALS 3 LEFT-JUSTIFIED.'.
CLEAR A5.
A5(44) = '        WRITE LV_AVG_NUM TO IT_AVG-CMICMIT E'.
A5+44(36) = 'XPONENT 0 DECIMALS 3 LEFT-JUSTIFIED.'.

CALL FUNCTION 'RPY_PROGRAM_READ'
  EXPORTING
    PROGRAM_NAME    = 'ZQMR_COA'
    ONLY_SOURCE     = 'X'
  TABLES
    SOURCE_EXTENDED = LT_SRC
  EXCEPTIONS
    OTHERS          = 9.
IF SY-SUBRC <> 0.
  WRITE: / 'READ FAILED'.
  RETURN.
ENDIF.

LOOP AT LT_SRC.
  L = LT_SRC-LINE.
  IF L CS 'FORM MICFMT'.
    NF = NF + 1.
  ENDIF.
  IF L = A1.
    CLEAR W.
    W(44) = '                PERFORM MICFMT USING IT_MIC-'.
    W+44(17) = 'MIC IT_DATA-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                        CHANGING GV_DEC GV_U'.
    W+44(3) = 'OM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                WRITE LT_QASE-MESSWERT TO IT'.
    W+44(44) = '_ALV-CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT'.
    W+88(11) = '-JUSTIFIED.'.
    PERFORM A USING W.
    N1 = N1 + 1.
    CONTINUE.
  ENDIF.
  IF L = A2.
    CLEAR W.
    W(44) = '              PERFORM MICFMT USING IT_MIC-MI'.
    W+44(15) = 'C IT_DATA-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '                      CHANGING GV_DEC GV_UOM'.
    W+44(1) = '.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '              WRITE IT_MIC-MICMIT TO IT_ALV-'.
    W+44(44) = 'CMICMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUST'.
    W+88(6) = 'IFIED.'.
    PERFORM A USING W.
    N2 = N2 + 1.
    CONTINUE.
  ENDIF.
  IF L = A3.
    CLEAR W.
    W(44) = '          PERFORM MICFMT USING IT_MIC-MIC IT'.
    W+44(11) = '_DATA-WERKS'.
    PERFORM A USING W.
    CLEAR W.
    W(41) = '                  CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '          WRITE LT_ZLOG-VALUE1 TO IT_ALV-CMI'.
    W+44(44) = 'CMIT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFI'.
    W+88(3) = 'ED.'.
    PERFORM A USING W.
    N3 = N3 + 1.
    CONTINUE.
  ENDIF.
  IF L = A4.
    CLEAR W.
    W(44) = '            PERFORM MICFMT USING LS_CUR_MIC '.
    W+44(5) = 'SPACE'.
    PERFORM A USING W.
    CLEAR W.
    W(43) = '                    CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '            WRITE LV_AVG_NUM TO IT_AVG-CMICM'.
    W+44(44) = 'IT EXPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED'.
    W+88(1) = '.'.
    PERFORM A USING W.
    N4 = N4 + 1.
    CONTINUE.
  ENDIF.
  IF L = A5.
    CLEAR W.
    W(44) = '        PERFORM MICFMT USING LS_CUR_MIC SPAC'.
    W+44(1) = 'E'.
    PERFORM A USING W.
    CLEAR W.
    W(39) = '                CHANGING GV_DEC GV_UOM.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '        WRITE LV_AVG_NUM TO IT_AVG-CMICMIT E'.
    W+44(41) = 'XPONENT 0 DECIMALS GV_DEC LEFT-JUSTIFIED.'.
    PERFORM A USING W.
    N5 = N5 + 1.
    CONTINUE.
  ENDIF.
  PERFORM A USING L.
  IF L = R0.
    CLEAR W.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '* Cache format MIC dari master QPMK: decimal'.
    W+44(34) = ' places (STELLEN) per MIC + plant.'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '* Dibaca sekali per kombinasi lalu dilayani '.
    W+44(28) = 'dari memori. Dinamis penuh -'.
    PERFORM A USING W.
    CLEAR W.
    W(44) = '* MIC baru otomatis ikut tanpa perlu ubah ko'.
    W+44(25) = 'de. (Fix user 18/07/2026)'.
    PERFORM A USING W.
    CLEAR W.
    W(26) = 'TYPES: BEGIN OF TY_MICFMT,'.
    PERFORM A USING W.
    CLEAR W.
    W(33) = '         MKMNR   TYPE QPMK-MKMNR,'.
    PERFORM A USING W.
    CLEAR W.
    W(33) = '         WERKS   TYPE QPMK-WERKS,'.
    PERFORM A USING W.
    CLEAR W.
    W(35) = '         STELLEN TYPE QPMK-STELLEN,'.
    PERFORM A USING W.
    CLEAR W.
    W(38) = '         UOM     TYPE QPMK-MASSEINHSW,'.
    PERFORM A USING W.
    CLEAR W.
    W(24) = '       END OF TY_MICFMT.'.
    PERFORM A USING W.
    CLEAR W.
    W(40) = 'DATA: GT_MICFMT TYPE TABLE OF TY_MICFMT,'.
    PERFORM A USING W.
    CLEAR W.
    W(31) = '      GS_MICFMT TYPE TY_MICFMT.'.
    PERFORM A USING W.
    CLEAR W.
    W(20) = 'DATA: GV_DEC TYPE I,'.
    PERFORM A USING W.
    CLEAR W.
    W(34) = '      GV_UOM TYPE QPMK-MASSEINHSW.'.
    PERFORM A USING W.
    NR = NR + 1.
  ENDIF.
ENDLOOP.

IF NR <> 1 OR NF <> 0 OR N1 <> 1 OR N2 <> 1
   OR N3 <> 1 OR N4 <> 1 OR N5 <> 1.
  WRITE: / 'ABORT'.
  WRITE: / NR, NF, N1, N2, N3, N4, N5.
  RETURN.
ENDIF.
CLEAR W.
PERFORM A USING W.
CLEAR W.
W(44) = '*&------------------------------------------'.
W+44(27) = '--------------------------*'.
PERFORM A USING W.
CLEAR W.
W(20) = '*&      Form  MICFMT'.
PERFORM A USING W.
CLEAR W.
W(44) = '*&------------------------------------------'.
W+44(27) = '--------------------------*'.
PERFORM A USING W.
CLEAR W.
W(44) = '* Fix (user 18/07/2026): sebelumnya WRITE me'.
W+44(23) = 'ng-hardcode DECIMALS 3,'.
PERFORM A USING W.
CLEAR W.
W(44) = '* value tidak mengikuti master MIC (mis. SEW'.
W+44(26) = 'ESTMZ STELLEN=0 seharusnya'.
PERFORM A USING W.
CLEAR W.
W(44) = '* tampil 55 bukan 54.842). Ambil STELLEN dar'.
W+44(23) = 'i QPMK per MIC + plant,'.
PERFORM A USING W.
CLEAR W.
W(44) = '* di-cache di GT_MICFMT. Kalau plant kosong '.
W+44(23) = '/ tidak ketemu -> pakai'.
PERFORM A USING W.
CLEAR W.
W(43) = '* baris manapun (STELLEN sama antar plant).'.
PERFORM A USING W.
CLEAR W.
W(29) = 'FORM MICFMT USING P_MIC P_WRK'.
PERFORM A USING W.
CLEAR W.
W(30) = '         CHANGING P_DEC TYPE I'.
PERFORM A USING W.
CLEAR W.
W(24) = '                  P_UOM.'.
PERFORM A USING W.
CLEAR W.
W(22) = '  CLEAR: P_DEC, P_UOM.'.
PERFORM A USING W.
CLEAR W.
W(22) = '  IF P_MIC IS INITIAL.'.
PERFORM A USING W.
CLEAR W.
W(11) = '    RETURN.'.
PERFORM A USING W.
CLEAR W.
W(8) = '  ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(37) = '  READ TABLE GT_MICFMT INTO GS_MICFMT'.
PERFORM A USING W.
CLEAR W.
W(41) = '    WITH KEY MKMNR = P_MIC WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(19) = '  IF SY-SUBRC <> 0.'.
PERFORM A USING W.
CLEAR W.
W(20) = '    CLEAR GS_MICFMT.'.
PERFORM A USING W.
CLEAR W.
W(28) = '    GS_MICFMT-MKMNR = P_MIC.'.
PERFORM A USING W.
CLEAR W.
W(28) = '    GS_MICFMT-WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(28) = '    IF P_WRK IS NOT INITIAL.'.
PERFORM A USING W.
CLEAR W.
W(38) = '      SELECT SINGLE STELLEN MASSEINHSW'.
PERFORM A USING W.
CLEAR W.
W(44) = '        INTO (GS_MICFMT-STELLEN, GS_MICFMT-U'.
W+44(3) = 'OM)'.
PERFORM A USING W.
CLEAR W.
W(17) = '        FROM QPMK'.
PERFORM A USING W.
CLEAR W.
W(27) = '        WHERE MKMNR = P_MIC'.
PERFORM A USING W.
CLEAR W.
W(28) = '          AND WERKS = P_WRK.'.
PERFORM A USING W.
CLEAR W.
W(9) = '    ELSE.'.
PERFORM A USING W.
CLEAR W.
W(19) = '      SY-SUBRC = 4.'.
PERFORM A USING W.
CLEAR W.
W(10) = '    ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(21) = '    IF SY-SUBRC <> 0.'.
PERFORM A USING W.
CLEAR W.
W(38) = '      SELECT SINGLE STELLEN MASSEINHSW'.
PERFORM A USING W.
CLEAR W.
W(44) = '        INTO (GS_MICFMT-STELLEN, GS_MICFMT-U'.
W+44(3) = 'OM)'.
PERFORM A USING W.
CLEAR W.
W(17) = '        FROM QPMK'.
PERFORM A USING W.
CLEAR W.
W(28) = '        WHERE MKMNR = P_MIC.'.
PERFORM A USING W.
CLEAR W.
W(10) = '    ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(34) = '    APPEND GS_MICFMT TO GT_MICFMT.'.
PERFORM A USING W.
CLEAR W.
W(8) = '  ENDIF.'.
PERFORM A USING W.
CLEAR W.
W(28) = '  P_DEC = GS_MICFMT-STELLEN.'.
PERFORM A USING W.
CLEAR W.
W(24) = '  P_UOM = GS_MICFMT-UOM.'.
PERFORM A USING W.
CLEAR W.
W(8) = 'ENDFORM.'.
PERFORM A USING W.

CALL FUNCTION 'Z_RFC_PROGRAM_UPDATE'
  EXPORTING
    IV_PROGRAM_NAME = 'ZQMR_COA'
    IV_PACKAGE      = '$TMP'
    IV_CORRNUMBER   = ' '
  IMPORTING
    EV_SUCCESS      = LV_OK
    EV_MESSAGE      = LV_MSG
  TABLES
    IT_SOURCE       = LT_OUT.
DESCRIBE TABLE LT_OUT LINES NR.
WRITE: / 'SUCCESS=', LV_OK, ' LINES=', NR.
WRITE: / 'MSG=', LV_MSG.

FORM A USING P TYPE ABAPTXT255-LINE.
  LT_OUT-LINE = P.
  APPEND LT_OUT.
ENDFORM.